hyperledger/grid

docs/supply-chain-build-docs

Unpin Sphinx version

---

.gitignore
daemon/Cargo.toml
daemon/src/error.rs
daemon/src/main.rs

Adds initial daemon package within Grid and adds the generated build docs from this package to the .gitignore file. Currently, none of the contents of this package are really functional.

Add initial daemon package

---

.dockerignore
daemon/Dockerfile
docker-compose.yaml

Add a Dockerfile for `gridd` and include a container in the docker compose file.

Add gridd to docker compose file

---

docker-compose-installed.yaml
docker-compose.yaml

Signed-off-by: kulkarniamol <amol.kulkarni@intel.com>

Updated docker-compose files to Sawtooth 1.1

---

sdk/protos/pike_payload.proto
sdk/src/protocol/pike/mod.rs
sdk/src/protocol/pike/payload.rs
sdk/src/protocol/pike/state.rs

This is needed to use pike state objects in the grid schema smart contract.

Add native implementations for pike protos. 

---

contracts/track_and_trace/Dockerfile
docker-compose.yaml

Convert the Track and Trace TP's development Dockerfile to use the same multi-stage build style as the grid daemon.  This improves overall build time and developer experience when working in a docker-compose environment.

Convert TnT dev docker file to multi-stage

---

daemon/Cargo.toml
daemon/src/config.rs
daemon/src/error.rs
daemon/src/event/mod.rs
daemon/src/main.rs
daemon/src/rest_api/error.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/route_handler.rs
daemon/src/sawtooth_connection.rs

Implements POST submit_batches endpoint as specified by the openapi spec documentation.

Submit batches endpoint

---

daemon/Cargo.toml
daemon/Dockerfile
daemon/diesel.toml
daemon/migrations/00000000000000_diesel_initial_setup/down.sql
daemon/migrations/00000000000000_diesel_initial_setup/up.sql
daemon/migrations/2019-03-29-174040_create_block/down.sql
daemon/migrations/2019-03-29-174040_create_block/up.sql
daemon/src/config.rs
daemon/src/database/error.rs
daemon/src/database/mod.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/error.rs
daemon/src/event/block.rs
daemon/src/main.rs
daemon/src/schema.patch
docker-compose.yaml

This currently writes blocks to a Block table, but does not (yet) deal in fork resolution.

Configure Grid daemon to write events to a PostGreSQL instance

---

contracts/schema/Cargo.toml

Update Grid Schema to use sabre-sdk = 0.2

---

contracts/pike/src/handler.rs
docs/source/pike_transaction_family.rst
sdk/protos/pike_payload.proto
sdk/protos/pike_state.proto
sdk/src/protocol/pike/payload.rs
sdk/src/protocol/pike/state.rs

Add metadata to organizations

---

Jenkinsfile
docs/grid-build-docs
docs/source/_templates/indexcontent.html
docs/source/contents.rst
docs/source/grid_schema_family_specification.rst
docs/source/grid_track_and_trace_family_specification.rst

Also updates the name of Dockerfile used to build the docs and adds some missing Creative Commons License.

 Add Grid Schema Transaction Family Spec 

---

daemon/Cargo.toml
daemon/Dockerfile
daemon/migrations/2019-04-04-145511_create-pike-tables/down.sql
daemon/migrations/2019-04-04-145511_create-pike-tables/up.sql
daemon/src/database/error.rs
daemon/src/database/helpers/agents.rs
daemon/src/database/helpers/blocks.rs
daemon/src/database/helpers/mod.rs
daemon/src/database/helpers/organizations.rs
daemon/src/database/mod.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/event/block.rs
daemon/src/event/mod.rs
daemon/src/main.rs

Adds tables from pike to daemon
Adds initial database helper functions
Updates state delta export to handle pike organizations and agents

Integrate Pike into Grid State Delta Export

---

docs/source/pike_transaction_family.rst

Fixes a small error in the pike transaction family specification document.

Fix error in pike transaction family spec

---

daemon/migrations/2019-04-19-191743_create_grid_schema_tables/down.sql
daemon/migrations/2019-04-19-191743_create_grid_schema_tables/up.sql
daemon/src/database/models.rs
daemon/src/database/schema.rs
docs/source/grid_schema_family_specification.rst

Adds migration scripts and models for the following tables
- grid_schema
- grid_property_definition
- grid_property_value

Add grid database schemas

---

daemon/src/event/block.rs
daemon/src/event/mod.rs

Fixes event filter for Pike state delta events

Fix Pike state delta subscription

---

cli/src/main.rs
contracts/pike/src/addresser.rs
contracts/pike/src/handler.rs
contracts/pike/src/main.rs
contracts/schema/src/handler.rs
contracts/schema/src/state.rs
contracts/track_and_trace/src/addressing.rs
contracts/track_and_trace/src/handler.rs
contracts/track_and_trace/src/payload.rs
contracts/track_and_trace/src/state.rs
daemon/src/database/helpers/blocks.rs
daemon/src/database/models.rs
daemon/src/event/block.rs
daemon/src/event/mod.rs
daemon/src/rest_api/routes/batches.rs
sdk/src/lib.rs
sdk/src/permissions.rs
sdk/src/protocol/pike/payload.rs
sdk/src/protocol/pike/state.rs
sdk/src/protocol/schema/state.rs

Adding rustfmt and clippy to CI will be in a later PR

Fix rustfmt diff and clippy errors

---

Jenkinsfile
bin/run_lint
contracts/pike/src/handler.rs
contracts/schema/src/handler.rs
contracts/track_and_trace/src/handler.rs
daemon/src/event/block.rs
docker/lint

Adds a new step to Jenkins to run rustfmt and clippy, and fixes some existing errors
https://build.sawtooth.me/view/all/job/Grid-Hyperledger/job/grid/view/change-requests/job/PR-67/6/console successful build with updated Jenkinsfile

Add rustfmt and clippy to Jenkins

---

Jenkinsfile

Add jenkins uid as env var for builds

---

Jenkinsfile
bin/run_integration_tests
bin/run_unit_tests
cli/src/actions/schemas.rs
daemon/src/rest_api/routes/mod.rs
daemon/test/docker-compose.yaml
docker/compose/grid_tests.yaml
docker/tests

Updates the Jenkinsfile to run rust unit tests and integration tests.

Run unit and integration tests in Jenkins

---

cli/Cargo.toml
contracts/schema/Cargo.toml
contracts/track_and_trace/Cargo.toml
daemon/migrations/2019-05-02-191951_create_tnt_tables/down.sql
daemon/migrations/2019-05-02-191951_create_tnt_tables/up.sql
daemon/src/database/helpers/grid_schemas.rs
daemon/src/database/helpers/mod.rs
daemon/src/database/helpers/track_and_trace.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/event/block.rs
daemon/src/event/mod.rs

Adds state delta export integration, database schema, and database helpers for Track and Trace to Grid Daemon.

Track and Trace State Delta Export

---

cli/Cargo.toml
contracts/pike/Cargo.toml
contracts/schema/Cargo.toml
contracts/track_and_trace/Cargo.toml
daemon/Cargo.toml
sdk/Cargo.toml

Update cli sawtooth sdk dependency

---

contracts/track_and_trace/src/handler.rs
docs/source/transaction_family_specifications/grid_track_and_trace_family_specification.rst
sdk/protos/track_and_trace_payload.proto
sdk/protos/track_and_trace_state.proto

To test:
```
$ cd grid
$ docker build . -f docs/grid-build-docs -t grid-build-docs
$ docker run -v $(pwd):/project/grid grid-build-docs
```
Navigate to `grid/docs/build` and open up the html or pdf

Update Track and Trace spec

---

daemon/openapi.yaml
daemon/src/database/helpers/track_and_trace.rs
daemon/src/database/models.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/records.rs

Implements an endpoint that lists all records in the record collection.

Implement GET /record endpoint

---

contracts/pike/Cargo.toml
contracts/schema/Cargo.toml
contracts/track_and_trace/Cargo.toml

Replace rust-crypto fork with rust-crypto-wasm 0.3

---

daemon/migrations/2019-04-04-145511_create-pike-tables/up.sql
daemon/migrations/2019-05-23-175928_create_property_view/down.sql
daemon/migrations/2019-05-23-175928_create_property_view/up.sql
daemon/openapi.yaml
daemon/src/database/helpers/track_and_trace.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/event/block.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/agents.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/records.rs

Implements an endpoint to fetch the information on a particular property of a record, including current value and history of changes.

Implement GET /record/{record_id}/{property_name} endpoint

---

daemon/src/database/helpers/track_and_trace.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/records.rs

Adds properties to GET /record/{record_id} and GET /record endpoint

Add properties to record endpoints

---

daemon/src/event/block.rs

Add TRACK_AND_TRACE_NAMESPACE to filter

---

bin/run_lint
contracts/product/Cargo.toml
contracts/product/src/addressing.rs
contracts/product/src/handler.rs
contracts/product/src/main.rs
contracts/product/src/payload.rs
contracts/product/src/state.rs
contracts/product/src/validation.rs
sdk/protos/product_payload.proto
sdk/protos/product_state.proto

This pr adds the files for the product smart contract, protos for the data models, and support for sabre.
validation.rs contains logic for validating a gtin and is extensible 
See: https://github.com/hyperledger/grid-rfcs/pull/5 for more details

Add product smart contract

---

cli/Cargo.toml
cli/src/actions/schemas.rs
cli/src/transaction.rs
contracts/pike/Cargo.toml
contracts/pike/src/handler.rs
contracts/pike/src/main.rs
contracts/product/Cargo.toml
contracts/product/src/handler.rs
contracts/product/src/main.rs
contracts/schema/Cargo.toml
contracts/schema/src/handler.rs
contracts/schema/src/main.rs
contracts/schema/src/payload.rs
contracts/track_and_trace/Cargo.toml
contracts/track_and_trace/src/handler.rs
contracts/track_and_trace/src/main.rs
sdk/Cargo.toml
sdk/src/protocol/schema/payload.rs

You may need to blow away your local version of the Sabre TP to test.

Update Grid to use Sabre 0.4 and Add logging to Smart Contracts

---

daemon/migrations/2019-07-03-161310_create_product_table/down.sql
daemon/migrations/2019-07-03-161310_create_product_table/up.sql
daemon/src/database/helpers/mod.rs
daemon/src/database/helpers/products.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs

Adding grid product db queries, schemas, models, and helper functions.
cc: @adeebahmed

Add product db schemas/models

---

contracts/product/Dockerfile
contracts/product/product.yaml
docker-compose.yaml

Signed-off-by: AdeebAhmed <adeeb.ahmed@target.com>

Add product to Dockerfile/docker-compose

---

contracts/product/src/handler.rs
contracts/product/src/payload.rs
contracts/product/src/state.rs

Adding unit tests for Grid Product smart contract
Signed-off-by: Raphael Santo Domingo <raphael.santodomingo@target.com>
cc: @adeebahmed

Add product smart contract unit tests

---

docker-compose.yaml

Addresses refactor of [grid daemon Dockerfile](https://github.com/hyperledger/grid/commit/8668d9d53fe32f284a87f2d1fcb626833ebb36e0#diff-19f639ee45b76a90b65245120ad4df8b).

Update grid and gridd binary paths

---

daemon/migrations/2019-07-03-161310_create_product_table/down.sql
daemon/migrations/2019-07-03-161310_create_product_table/up.sql
daemon/migrations/2019-08-08-145850_create_product_property_table/down.sql
daemon/migrations/2019-08-08-145850_create_product_property_table/up.sql
daemon/src/database/helpers/products.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/event/block.rs
daemon/src/event/mod.rs

Updating the state delta subscriber to handle grid product events.
See [Jira story](https://jira.hyperledger.org/browse/GRID-21)

Add Grid product to state delta export

---

daemon/src/rest_api/routes/agents.rs
daemon/src/rest_api/routes/batches.rs
daemon/src/rest_api/routes/schemas.rs
sdk/src/protocol/product/payload.rs

Signed-off-by: Patrick-Erichsen <Patrick.Erichsen@target.com>

Add dyn traits to fix compiler deprecation errors

---

docker-compose.yaml

Rename the docker-compose build to match the name defined in contracts/product/product.yaml

Rename product -> grid_product in docker-compose

---

daemon/src/database/helpers/products.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/products.rs

see [Jira](https://jira.hyperledger.org/browse/GRID-23).

Implement Product REST API

---

cli/src/actions/mod.rs
cli/src/actions/products.rs
cli/src/actions/schemas.rs
cli/src/main.rs
cli/src/transaction.rs
cli/src/yaml_parser.rs
sdk/src/protocol/product/payload.rs
sdk/src/protocol/product/state.rs
sdk/src/protocol/schema/state.rs

This PR implements the CLI for Grid Product. 
Actions included are:
- Create
- Update
- Delete
- List
- Show

Implement Product CLI

---

.gitignore
Cargo.toml
bin/run_lint
bin/run_unit_tests

Add top-level workspace Cargo.toml

---

daemon/migrations/2019-12-09-214848_add_source_column/down.sql
daemon/migrations/2019-12-09-214848_add_source_column/up.sql
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/event/block.rs
daemon/src/rest_api/routes/mod.rs

This will initially be used to include a circuit ID with each resource if Grid is running on Splinter.

Add source column to Grid models

---

ci/grid-dev

The image built from this dockerfile will eventually replace ubuntu
in the FROM line in all grid build images.

Add dockerfile for grid-dev image

---

docker-compose-splinter.yaml

Add compose file for grid with splinter

---

Jenkinsfile

Build grid-dev image on master merges

---

daemon/src/main.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/batches.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/sawtooth/connection.rs
daemon/src/sawtooth/event.rs

Adds BatchSubmitter trait to replace Actix handlers for submitting batches, and refactors submit_batch and get_batch_status routes to use it

Splinter Mode

---

cli/src/transaction.rs
contracts/product/src/addressing.rs
contracts/product/src/handler.rs
contracts/track_and_trace/src/addressing.rs
contracts/track_and_trace/src/handler.rs
daemon/src/main.rs
daemon/src/rest_api/routes/records.rs
daemon/src/sawtooth/batch_submitter.rs

Fix clippy lint from 1.40 update

---

daemon/Cargo.toml
daemon/src/main.rs
daemon/src/rest_api/error.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/agents.rs
daemon/src/rest_api/routes/batches.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/organizations.rs
daemon/src/rest_api/routes/products.rs
daemon/src/rest_api/routes/records.rs
daemon/src/rest_api/routes/schemas.rs

Upgrade actix version to 1.0

---

daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/mod.rs

Fixes breaking issue with `/batches`

Add name resolution

---

examples/splinter/configs/key_registry_spec.yaml
examples/splinter/configs/nodes.yaml
examples/splinter/docker-compose.yaml

Add example compose file for Grid on Splinter

---

daemon/Cargo.toml
daemon/src/main.rs
daemon/src/rest_api/error.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/agents.rs
daemon/src/rest_api/routes/batches.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/organizations.rs
daemon/src/rest_api/routes/products.rs
daemon/src/rest_api/routes/records.rs
daemon/src/rest_api/routes/schemas.rs

PR to update futures library from 0.1 to 0.3. Consequently actix-web has also been updated to 2.0

Update Future and actix libraries

---

daemon/src/main.rs

Fix splinter mode ctrl c handler

---

examples/splinter/docker-compose.yaml

Build gridd with experimental features in splinter example

---

docs/grid-build-docs

This newer version fixes a docs build error.

Upgrade nodejs version in docs builder

---

cli/src/actions/agents.rs
cli/src/actions/organizations.rs
cli/src/actions/products.rs
cli/src/actions/schemas.rs
cli/src/http.rs
cli/src/main.rs

Adds service id option for all agents, organization, schema and products CLI commands.

Add service id option to Grid CLI

---

examples/splinter/configs/key_registry_spec.yaml
examples/splinter/configs/nodes.yaml
examples/splinter/docker-compose.yaml

This will make it easier to demonstrate the scoping of circuits.

Add gamma node to splinter example docker-compose 

---

cli/Cargo.toml
cli/src/error.rs
cli/src/main.rs
contracts/pike/Cargo.toml
contracts/pike/src/error.rs
contracts/pike/src/main.rs
daemon/Cargo.toml
daemon/src/error.rs
daemon/src/main.rs

This allows for further configuration with the logging messages. This pr filters out tokio and hyper logging messages.

Replace simple logger with flexi logger

---

examples/splinter/docker-compose.yaml

This is an known/caught condition that can be confusing when troubleshooting
problems with the example.

Quiet psql connection refused message in splinter example

---

examples/splinter/README.md

Add examples/splinter/README.md

---

examples/splinter/README.md

Add instructions for pulling latest images to Splinter example README

---

integration/docker-compose.yaml

Fix some minor bugs in the integration docker-compose.yaml

---

examples/splinter/README.md
integration/docker-compose.yaml

Add section on circuit scope to Grid on Splinter README

---

examples/splinter/README.md

Updates the Grid on splinter example for updates to the splinter circuit cli

Update example outputs for splinter cli in Splinter example README

---

examples/splinter/README.md

Update product to represent a simple fish product in example readme

---

contracts/schema/Dockerfile
daemon/src/splinter/app_auth_handler/sabre.rs

This PR includes updating the name of the schema scar file because it was missing an underscore.

Add deployment of grid schema to Grid App Auth Handler

---

cli/Dockerfile
contracts/pike/Dockerfile
contracts/product/Dockerfile
contracts/schema/Dockerfile
contracts/track_and_trace/Dockerfile
daemon/Dockerfile

This will allow us to version updates to the base image so significant changes
don't silently break building grid components.

Update dockerfiles based on grid-dev to include a tag

---

cli/src/error.rs
contracts/product/src/main.rs
contracts/schema/src/main.rs
contracts/track_and_trace/src/main.rs
daemon/src/main.rs

Resolves clippy errors introduced in the Rust 1.42 release.

Rust1.42 update fixes

---

grid-ui/saplings/profile/src/ActionList.scss
grid-ui/saplings/profile/src/Input.scss
grid-ui/saplings/profile/src/Loader.scss
grid-ui/saplings/profile/src/OverlayModal.scss
grid-ui/saplings/profile/src/forms/AddKeyForm.scss
grid-ui/saplings/profile/src/forms/EnterPasswordForm.scss
grid-ui/saplings/profile/src/forms/MultiStepForm.scss
grid-ui/saplings/profile/src/forms/UpdateKeyForm.scss

Scope profile css to within the #profile ID. This helps prevent styles
from affecting other saplings.

Scope profile css by ID

---

grid-ui/saplings/product/src/App.js
grid-ui/saplings/product/src/components/CircuitDropdown.js
grid-ui/saplings/product/src/components/CircuitDropdown.scss
grid-ui/saplings/product/src/components/Loading.js
grid-ui/saplings/product/src/components/Loading.scss
grid-ui/saplings/product/src/components/NotFound.js
grid-ui/saplings/product/src/components/NotFound.scss
grid-ui/saplings/product/src/components/ProductInfo.js
grid-ui/saplings/product/src/components/ProductsTable.js

Adds loading, notfound, and disabled states to various UI components.
- The CircuitDropdown is disabled if there are no scabbard services available
- If there are no products, a message will be displayed in the products table
- If a product is not available based on the URL, a message will be displayed where the product info would be
- A loader component will be displayed while new data is being loaded from the API.

State indicators

---

examples/splinter/docker-compose.yaml

Updates the docker-compose file for the splinter example to use the new
registry configuration options for splinterd.

Update splinter example registy config

---

grid-ui/saplings/profile/src/KeyCard.scss
grid-ui/saplings/profile/src/Loader.scss
grid-ui/saplings/profile/src/Profile.js
grid-ui/saplings/profile/src/forms/AddKeyForm.js
grid-ui/saplings/profile/src/forms/ChangePasswordForm.js
grid-ui/saplings/profile/src/forms/UpdateKeyForm.js

This PR updates the profile sapling with improved error handling, improved styles on the KeyCard component, updated routes corresponding to changes to the Biome routes, and functionality that updates key encryption when a user changes their password.

Update profile sapling

---

.gitignore
Jenkinsfile
examples/splinter/docker-compose.yaml
grid-ui/docker/docker-compose.yaml
grid-ui/sapling-dev-server/Dockerfile
grid-ui/saplings/product/.eslintignore
grid-ui/saplings/product/.prettierignore
grid-ui/saplings/product/package.json
grid-ui/saplings/product/scripts/compile_protobuf.js
grid-ui/saplings/product/src/App.js
grid-ui/saplings/product/src/api/transactions.js
grid-ui/saplings/product/src/components/AddProductForm.js
grid-ui/saplings/product/src/components/Input.js
grid-ui/saplings/product/src/components/MultiSelect.scss
grid-ui/saplings/product/src/components/MultiStepForm.scss
grid-ui/saplings/product/src/protobuf.js
grid-ui/saplings/product/test/Dockerfile

This PR adds functionality to the AddProductForm component to submit a Sabre transaction that adds a Grid Product to a circuit.
- Navigate to the `/grid` directory
- Run `docker-compose -f examples/splinter/docker-compose.yaml up --build`
- Once all the containers have started follow the Grid on splinter directions until step 6
- In a browser, navigate to http://localhost:3030 and create a new user
- Navigate to the profile page and add a new key pair with the keys generated while setting up Grid
- Navigate to the product sapling and make sure that the service you created shows up in the dropdown at the top.
- Add a product with one of the following valid GTINs `013600000929` or `614141000449`
There is a known bug where creating a second service or submitting to multiple services at once …

Add product gridd

---

cli/src/error.rs
cli/src/key.rs
cli/src/transaction.rs
daemon/src/rest_api/error.rs

This updates cli and daemon imports to pass lint with the most recent
version of Rust.

Fix lint issues

---

grid-ui/saplings/product/src/App.js
grid-ui/saplings/product/src/api/transactions.js
grid-ui/saplings/product/src/components/EditProductForm.js
grid-ui/saplings/product/src/components/ProductCard.js
grid-ui/saplings/product/src/components/ProductsTable.js
grid-ui/saplings/product/src/data/property-parsing.js

This PR updates the product sapling with functionality to submit edit product transactions through the product sapling UI.
- Navigate to the `/grid` directory
- Run `docker-compose -f examples/splinter/docker-compose.yaml up --build`
- Once all the containers have started follow the Grid on splinter directions until step 6
- In a browser, navigate to http://localhost:3030 and create a new user
- Navigate to the profile page and add a new key pair with the keys generated while setting up Grid
- Navigate to the product sapling and make sure that the service you created shows up in the dropdown at the top.
- Add a product with one of the following valid GTINs `013600000929` or `614141000449`
- Refresh the page and edit the newly created Product

Edit product gridd

---

daemon/src/splinter/app_auth_handler/error.rs
daemon/src/splinter/app_auth_handler/sabre.rs

Updates gridd's usage of the scabbard client to reflect recent changes
made to the client's API.

Update scabbard client usage

---

docker-compose-splinter.yaml
examples/splinter/docker-compose.yaml
grid-ui/docker/docker-compose.yaml

Updates the docker-compose for changes introduced in
Cargill/splinter#754
Also fix a missed registries update.

Update docker-compose for splinterd option changes

---

docker-compose-splinter.yaml
examples/splinter/docker-compose.yaml
grid-ui/docker/docker-compose.yaml

Splinter registry updates: https://github.com/Cargill/splinter/pull/773
Splinter rest-api-endpoint update: https://github.com/Cargill/splinter/pull/789

Registry and bind updates

---

daemon/src/main.rs

Updates the Splinter event reactor shutdown to the latest method
using the `shutdown_signaler` to signal a shutdown rather than
using the deprecated `shutdown` method.

Update Splinter event reactor shutdown

---

examples/splinter/README.md

[Signed-off-by:](url) Andrea Gunderson <agunde@bitwise.io>

Update scabbard cli to use --owners in Splinter README

---

daemon/Cargo.toml

Update scabbard dependency to 0.4

---

daemon/openapi.yaml

Fix indent error in openapi.yaml

---

sdk/protos/location_payload.proto
sdk/protos/location_state.proto
sdk/src/protocol/location/mod.rs
sdk/src/protocol/location/payload.rs
sdk/src/protocol/location/state.rs

Add protobuf definitions and structs for implementing the locations RFC

Location protos

---

cli/Dockerfile
contracts/pike/Dockerfile
contracts/product/Dockerfile
contracts/schema/Dockerfile
contracts/track_and_trace/Dockerfile
docker-compose.yaml
integration/docker-compose.yaml

Pin grid docker images to compatible version of sawtooth-sabre (0.5)

---

Cargo.toml
cli/Dockerfile
contracts/location/Cargo.toml
contracts/location/Dockerfile
contracts/location/location.yaml
contracts/location/packaging/scar/manifest.yaml
contracts/location/src/addressing.rs
contracts/location/src/handler.rs
contracts/location/src/main.rs
contracts/location/src/state.rs
contracts/pike/Dockerfile
contracts/product/Dockerfile
contracts/schema/Dockerfile
contracts/track_and_trace/Dockerfile
daemon/Dockerfile
docker-compose-splinter.yaml
docker-compose.yaml
examples/splinter/docker-compose.yaml

Adds implementation for location smart contract

Location smart contract

---

cli/src/actions/products.rs
cli/src/main.rs
cli/src/yaml_parser.rs
cli/tests/yaml/test_product_create.yaml
cli/tests/yaml/test_product_update.yaml
contracts/product/src/addressing.rs
contracts/product/src/handler.rs
contracts/product/src/payload.rs
contracts/product/src/state.rs
daemon/src/event/db_handler.rs
examples/splinter/README.md
grid-ui/saplings/product/src/api/transactions.js
sdk/protos/product_payload.proto
sdk/protos/product_state.proto
sdk/src/protocol/product/payload.rs
sdk/src/protocol/product/state.rs

Several updates to the product smart contract to align it with the RFC

Product Smart Contract Updates

---

sdk/src/grid_db/mod.rs
sdk/src/grid_db/products/error.rs
sdk/src/grid_db/products/mod.rs
sdk/src/grid_db/products/store/diesel/mod.rs
sdk/src/grid_db/products/store/diesel/models.rs
sdk/src/grid_db/products/store/diesel/operations/add_product.rs
sdk/src/grid_db/products/store/diesel/operations/delete_product.rs
sdk/src/grid_db/products/store/diesel/operations/fetch_product.rs
sdk/src/grid_db/products/store/diesel/operations/list_products.rs
sdk/src/grid_db/products/store/diesel/operations/mod.rs
sdk/src/grid_db/products/store/diesel/operations/update_product.rs
sdk/src/grid_db/products/store/diesel/schema.rs
sdk/src/grid_db/products/store/mod.rs
sdk/src/store/memory.rs
sdk/src/store/mod.rs
sdk/src/store/postgres.rs
sdk/src/store/sqlite.rs

Adds ProductStore traits and two implementations. One for Postgresql and one Sqlite.

Product Stores

---

sdk/src/grid_db/mod.rs
sdk/src/grid_db/schemas/error.rs
sdk/src/grid_db/schemas/mod.rs
sdk/src/grid_db/schemas/store/diesel/mod.rs
sdk/src/grid_db/schemas/store/diesel/models.rs
sdk/src/grid_db/schemas/store/diesel/operations/add_schema.rs
sdk/src/grid_db/schemas/store/diesel/operations/fetch_schema.rs
sdk/src/grid_db/schemas/store/diesel/operations/list_schemas.rs
sdk/src/grid_db/schemas/store/diesel/operations/mod.rs
sdk/src/grid_db/schemas/store/diesel/schema.rs
sdk/src/grid_db/schemas/store/memory.rs
sdk/src/grid_db/schemas/store/mod.rs
sdk/src/store/memory.rs
sdk/src/store/mod.rs
sdk/src/store/postgres.rs
sdk/src/store/sqlite.rs

Add schema store triat, and postgres, sqlite, and `HashMap` implementations

Schema Store

---

daemon/openapi.yaml
daemon/src/database/helpers/locations.rs
daemon/src/database/helpers/mod.rs
daemon/src/database/models.rs
daemon/src/database/schema.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/locations.rs
daemon/src/rest_api/routes/mod.rs
sdk/src/grid_db/migrations/diesel/postgres/migrations/2020-09-24-185735_add_location_table/down.sql
sdk/src/grid_db/migrations/diesel/postgres/migrations/2020-09-24-185735_add_location_table/up.sql
sdk/src/grid_db/migrations/diesel/postgres/migrations/2020-09-24-193134_add_location_property_table/down.sql
sdk/src/grid_db/migrations/diesel/postgres/migrations/2020-09-24-193134_add_location_property_table/up.sql

Implements the /location and /location/{id} routes.

Implement Location REST API

---

README.md

Also fix two "environment" typos

Fix README broken links; add grid-docs repo

---

examples/splinter/README.md

Fix doc links in grid/examples/splinter/README.md

---

ci/grid-dev
ci/grid-dev.yaml

Add location to grid-dev and increase version

---

contracts/location/location.yaml
contracts/location/packaging/scar/manifest.yaml
daemon/src/event/db_handler.rs
daemon/src/event/error.rs
daemon/src/event/mod.rs
sdk/src/grid_db/locations/store/diesel/mod.rs
sdk/src/grid_db/locations/store/diesel/models.rs
sdk/src/grid_db/locations/store/diesel/operations/delete_location.rs
sdk/src/grid_db/locations/store/diesel/operations/mod.rs
sdk/src/grid_db/locations/store/diesel/schema.rs
sdk/src/grid_db/locations/store/mod.rs
sdk/src/grid_db/migrations/diesel/postgres/migrations/2020-09-28-165102_initial_grid_tables/up.sql

This adds the SDE functionality for Grid Locations. This makes use of the new store pattern/functionality and follows similar patterns to other Grid modules.

Add Location SDE

---

cli/src/actions/locations.rs
cli/src/actions/mod.rs
cli/src/main.rs
cli/src/transaction.rs
cli/tests/locations/create_location.yaml
cli/tests/locations/create_location_schema.yaml
cli/tests/locations/update_location.yaml

Adds location create, update, delete, list, and show commands to grid cli, and sample files defining the location schema

Location CLI commands

---

ui/Dockerfile

Fixes https://github.com/hyperledger/grid/issues/382

Add gridd proxy to Dockerfile

---

cli/man/grid-location-create.md
cli/man/grid-location-delete.md
cli/man/grid-location-list.md
cli/man/grid-location-show.md
cli/man/grid-location-update.md
cli/man/grid.1.md

Add man pages for grid location commands

---

cli/src/actions/locations.rs
cli/src/actions/products.rs
cli/src/actions/schemas.rs
cli/src/error.rs
cli/src/http.rs

Closes [issue 407](https://github.com/hyperledger/grid/issues/407) and [issue 411](https://github.com/hyperledger/grid/issues/411)

Grid CLI error messages fixes

---

cli/schemas/location.yaml

Fields included in location schema were sourced from [this document](https://wiki.hyperledger.org/download/attachments/9110626/GLN%20Overview%20for%20GRID.pdf?api=v2)

Add location schema

---

contracts/location/Dockerfile
examples/sawtooth/README.md
examples/sawtooth/docker-compose.yaml

This adds a walkthrough for setting up Grid-on-Sawtooth and creating a schema and product.

Add Grid-on-Sawtooth example

---

examples/splinter/docker-compose.yaml

Fix Grid UI context in Splinter example Compose file

---

cli/src/http.rs
daemon/src/splinter/batch_submitter.rs
daemon/src/submitter.rs

Fixes [issue #398](https://github.com/hyperledger/grid/issues/398)

Fix cli wait flag in splinter mode

---

ci/publish-docker

Export ISOLATION_ID in script for untagged builds

---

cli/src/http.rs
daemon/src/splinter/batch_submitter.rs
ui/saplings/product/src/api/grid.js
ui/saplings/product/src/api/requests.js
ui/saplings/product/src/api/transactions.js

This adds protocol version headers to client and UI requests. This is currently not checked but will be in the future so this is a forward-compatibility change.

Add version headers

---

ui/saplings/product/package.json
ui/saplings/product/src/api/transactions.js

Updates the UI to use the published transact SDK.

Use published transact SDK in UI

---

Jenkinsfile
docker-compose.yaml
docker/compose/copy-artifacts.yaml

Archive grid-cli deb and .scar files in Jenkins

---

sdk/src/organizations/store/diesel/operations/add_organizations.rs

SDE now properly inserts updated organizations by incrementing the
commit num instead of rejecting them.

Insert updated organization resources

---

Jenkinsfile

Update Jenkinsfile for 0-1 branch

---

RELEASE_NOTES.md

These release notes provide a summary of the features in Grid 0.1

Add 0.1 Release Notes

---

sdk/Cargo.toml
sdk/src/lib.rs
sdk/src/workflow/mod.rs
sdk/src/workflow/state.rs
sdk/src/workflow/subworkflow.rs

Adds the experimental feature for workflows to the SDK

Add Workflow experimental feature

---

cli/Cargo.toml
cli/src/actions/database/mod.rs
cli/src/error.rs
cli/src/main.rs
contracts/location/Cargo.toml
contracts/pike/Cargo.toml
contracts/product/Cargo.toml
contracts/schema/Cargo.toml
contracts/track_and_trace/Cargo.toml
daemon/Cargo.toml
daemon/src/config.rs
daemon/src/error.rs
daemon/src/main.rs
daemon/src/sawtooth/mod.rs
daemon/src/sawtooth/run.rs
daemon/src/splinter/app_auth_handler/sabre.rs
daemon/src/splinter/mod.rs
daemon/src/splinter/run.rs
justfile
sdk/Cargo.toml
sdk/src/hex.rs
sdk/src/lib.rs

Adds a justfile. Fixes many feature guards, linting errors, etc. No intentional functional changes beyond new features being defined.
This branch passes "just build" and "just lint". It does not pass "just test", since tests need adjustment to be run without additional setup.

Add justfile

---

ui/grid-ui/package.json

Update git dependency branch from master to main (0.1 branch)

---

sdk/src/migrations/diesel/postgres/migrations/2020-09-28-165102_initial_grid_tables/up.sql
sdk/src/migrations/diesel/postgres/migrations/2021-02-02-223041_batch_table/down.sql
sdk/src/migrations/diesel/postgres/migrations/2021-02-02-223041_batch_table/up.sql

Add separate migration file for creating batch table

---

daemon/Cargo.toml
daemon/src/main.rs
daemon/src/rest_api/mod.rs
daemon/src/rest_api/routes/agents.rs
daemon/src/rest_api/routes/locations.rs
daemon/src/rest_api/routes/organizations.rs
daemon/src/rest_api/routes/products.rs
daemon/src/rest_api/routes/records.rs
daemon/src/rest_api/routes/schemas.rs
daemon/src/submitter.rs

Change offset type from `i64` to `u64`
Change limit type from `i64` to `u16`
Use serde and serde_json features to feature guard their macro uses

Pagination enhancements

---

RELEASE_NOTES.md

Add 0.1.2 Release Notes

---

examples/splinter/docker-compose-dockerhub.yaml

Add Compose file for grid on Splinter using published artifacts

---

daemon/src/rest_api/routes/agents.rs
daemon/src/rest_api/routes/locations.rs
daemon/src/rest_api/routes/mod.rs
daemon/src/rest_api/routes/organizations.rs
daemon/src/rest_api/routes/products.rs
daemon/src/rest_api/routes/records.rs
daemon/src/rest_api/routes/schemas.rs
sdk/src/rest_api/resources/paging/mod.rs
sdk/src/rest_api/resources/paging/v1/mod.rs

Move Grid daemon paging module into sdk

---

.env

Make REPO_VERSION match actual version

---

cli/src/http.rs

This cleans up the CLI batch submission output. This removes URLs from
the output, simplifies the output, and gives more descriptive output for
errors.

Clean up CLI batch submission output

---

sdk/protos/purchase_order_payload.proto
sdk/protos/purchase_order_state.proto

Add purchase order protobuf files

---

sdk/protos/purchase_order_payload.proto
sdk/protos/purchase_order_state.proto

Various update to purchase order protobufs

Po protobuf fixes

---

Jenkinsfile
bin/run_integration_tests
ci/publish-docker
examples/griddle/docker-compose.yaml
examples/sawtooth/docker-compose.yaml
examples/splinter/docker-compose.yaml
sdk/src/migrations/diesel/postgres/migrations/2021-03-24-130200_purchase_order_tables/up.sql
sdk/src/migrations/diesel/sqlite/migrations/2021-03-24-130200_purchase_order_tables/up.sql
ui/grid-ui/docker/docker-compose.yaml

The build method was changed in commit 75c9d52 but the some scripts and
Docker Compose files were not updated in the PR.

Use correct CARGO_ARGS argument for experimental

---

contracts/purchase_order/Dockerfile
contracts/purchase_order/packaging/scar/manifest.yaml
contracts/purchase_order/purchase_order.yaml
daemon/src/splinter/app_auth_handler/sabre.rs
docker-compose-splinter.yaml
docker-compose.yaml
docker/compose/copy-artifacts.yaml
examples/griddle/docker-compose.yaml
examples/sawtooth/docker-compose.yaml
examples/splinter/docker-compose.yaml

Updates AppAuthHandler and docker-compose files to build/submit the Grid Purchase Order smart contract

Add smart contract submission functionality for Purchase Order

---

sdk/src/protocol/errors.rs
sdk/src/protocol/purchase_order/mod.rs
sdk/src/protocol/purchase_order/state.rs

payloads will be added in a future PR.

Add protocol implementation for PO state

---

Jenkinsfile

Required DCO checks enabled on the repository satisfy this requirement.

Remove CI check for signed off commits

---

sdk/protos/purchase_order_payload.proto

Add missing action enum to purchase_order_payload.proto

---

cli/tests/product.rs
justfile

New commands:
just build-experimental
just lint-experimental
just test-experimental
just test-experimental-hack
Also ignores a few poorly setup tests.

Add experimental commands to justfile

---

cli/Cargo.toml
cli/Dockerfile
cli/packaging/ubuntu/completions/grid
daemon/Dockerfile

Add bash-completion file for grid-cli

---

cli/src/actions/locations.rs
cli/src/actions/products.rs
cli/src/actions/schemas.rs
sdk/src/rest_api/resources/submit/v1/payloads/location.rs
sdk/src/rest_api/resources/submit/v1/payloads/product.rs

This PR fixes several serialization issues.

Fix serialization issues

---

sdk/src/protocol/purchase_order/mod.rs
sdk/src/protocol/purchase_order/payload.rs

Add protocol traits for purchase order payloads

---

griddle/Cargo.toml
justfile
sdk/Cargo.toml
sdk/src/rest_api/actix_web_3/run.rs
sdk/src/rest_api/actix_web_3/store_state.rs

Missed that it is used in griddle, since griddle was not in justfile--so add it to justfile as well. Also fixes some issues when attempting to build griddle.

revert run removal & griddle fixes

---

sdk/Cargo.toml
sdk/src/client/mod.rs
sdk/src/client/reqwest.rs

- Update the method definition of `post_batches` in the `Client` trait.
- Implement the `post_batches` method in the reqwest based implementation of the `Client` trait.

Implement `post_batches`

---

sdk/src/protocol/purchase_order/state.rs
sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs

Fix purchase order rest api lint

---

cli/src/actions/locations.rs
cli/src/actions/products.rs
cli/src/actions/schemas.rs
contracts/pike/src/addresser.rs
contracts/pike/src/handler.rs
daemon/src/splinter/batch_submitter.rs
sdk/src/agents/store/diesel/mod.rs
sdk/src/commits/store/diesel/mod.rs
sdk/src/locations/store/diesel/mod.rs
sdk/src/organizations/store/diesel/mod.rs
sdk/src/products/store/diesel/mod.rs
sdk/src/protocol/location/payload.rs
sdk/src/protocol/location/state.rs
sdk/src/protocol/product/state.rs
sdk/src/schemas/store/diesel/mod.rs
sdk/src/track_and_trace/store/diesel/mod.rs

Fixes issues noted by new clippy lints

Fix lint issues (0.1)

---

justfile

Add purchase_order to the list of crates in justfile

---

contracts/purchase_order/Cargo.toml
contracts/purchase_order/src/main.rs
contracts/purchase_order/src/workflow.rs

Initial workflow for purchase order smart contract

PO workflows

---

ui/grid-ui/src/images/grid.svg

This updates the Grid logo used by the Grid UI. This version has a white
background instead of a transparent one.

Update Grid Logo

---

sdk/src/store/mod.rs

This replaces the StoreFactoryCreationError and ParseConnectionUriErrors
with the standard Grid InternalError type. This is more in line with the
approach used across the rest of the SDK.

Replace specific store errors with standard ones

---

ui/saplings/product/package.json

The default branch was recently changed to main.

Update Saplingjs dependency to correct branch

---

ci/grid-dev

Cache dependencies for all features in grid-dev

---

cli/src/actions/products.rs
cli/src/main.rs
sdk/src/products/gdsn/mod.rs
sdk/src/products/gdsn/test_files/gdsn_product.xml
sdk/src/products/gdsn/test_files/gdsn_product_invalid.xml
sdk/src/products/gdsn/test_files/gdsn_product_multiple.xml
sdk/src/products/gdsn/test_files/gdsn_product_poorly_formed.xml
sdk/src/products/gdsn/test_files/test_trade_item_payload_1.xml
sdk/src/products/gdsn/test_files/test_trade_item_payload_2.xml
sdk/src/products/gdsn/validate.rs

This PR cleans up some loose ends from the GDSN support feature:
- Implement product update in the CLI for multiple files and GDSN files
- Removing some unused code
- Adding unit tests to the GDSN module
- Adding docstrings to the GDSN module

Add GDSN support for CLI update, tests, and documentation

---

cli/src/main.rs

Properly wrap lines at 100 characters in grid cli

---

sdk/Cargo.toml

This PR contains a set of trivial dependency adjustments for the SDK. This is part of a larger effort to clean up the SDK dependencies.

Minor dependency cleanup

---

sdk/src/rest_api/actix_web_3/routes/agents.rs
sdk/src/rest_api/actix_web_3/routes/batches.rs
sdk/src/rest_api/actix_web_3/routes/locations.rs
sdk/src/rest_api/actix_web_3/routes/mod.rs
sdk/src/rest_api/actix_web_3/routes/organizations.rs
sdk/src/rest_api/actix_web_3/routes/products.rs
sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
sdk/src/rest_api/actix_web_3/routes/records.rs
sdk/src/rest_api/actix_web_3/routes/roles.rs
sdk/src/rest_api/actix_web_3/routes/schemas.rs
sdk/src/rest_api/actix_web_3/routes/submit.rs

Have only one DEFAULT_GRID_PROTOCOL_VERSION const

---

cli/src/actions/products.rs

Also wrap ling at 100 characters.

Remove newline from error in cli/action/product.rs

---

daemon/src/splinter/app_auth_handler/sabre.rs

A recent refactor of the app auth handler introduced some regressions. This PR fixes them.

Fix app auth handler

---

cli/src/actions/products.rs
cli/src/error.rs
cli/src/main.rs
sdk/src/product/gdsn/error.rs
sdk/src/product/gdsn/mod.rs

This PR consists of several updates for stabilization of the Product GDSN feature.

Minor updates for GDSN stabilization

---

sdk/src/product/store/mod.rs

This adds doc comments to the store methods belonging to the
`ProductStore` trait.

Add doc comments

---

daemon/Cargo.toml
daemon/src/event/error.rs
sdk/Cargo.toml
sdk/src/location/mod.rs
sdk/src/product/mod.rs
sdk/src/rest_api/actix_web_3/routes/mod.rs
sdk/src/rest_api/actix_web_3/store_state.rs
sdk/src/rest_api/resources/mod.rs
sdk/src/schema/mod.rs

This includes several fixes necessary to remove "experimental" from the daemon's default grid-sdk dependency. However, it does not yet actually remove it.

Various feature definition fixes

---

cli/man/grid-agent-create.1.md
cli/man/grid-agent-list.1.md
cli/man/grid-agent-show.1.md
cli/man/grid-agent-update.1.md
cli/man/grid-agent.1.md

Update man pages for agent commands

---

daemon/Cargo.toml
sdk/Cargo.toml
sdk/src/store/mod.rs
sdk/src/store/postgres.rs
sdk/src/store/sqlite.rs

This makes changes necessary to remove "experimental" dependency between the daemon and the sdk.

Daemon feature cleanup

---

sdk/src/product/mod.rs

This file was updated in 2021 but the header was not updated

Update header copyright

---

RELEASE_NOTES.md
contracts/product/src/validation.rs
sdk/src/protocol/location/payload.rs

Update release notes to include bug fix

---

cli/schemas/gdsn_3_1_schema.yaml

Add explanation to gdsn 3.1 grid schemas

---

cli/man/grid-location-create.1.md
cli/man/grid-location-delete.1.md
cli/man/grid-location-list.1.md
cli/man/grid-location-show.1.md
cli/man/grid-location-update.1.md
cli/man/grid-location.1.md

Update man pages for location commands

---

cli/man/grid-po-create.1.md
cli/man/grid-po-list.1.md
cli/man/grid-po-show.1.md
cli/man/grid-po-update.1.md
cli/man/grid-po-version-create.1.md
cli/man/grid-po-version-list.1.md
cli/man/grid-po-version-update.1.md
cli/man/grid-po-version.1.md
cli/man/grid-po.1.md
cli/src/main.rs

Update man pages for PO and PO Version Commands

---

cli/man/grid-role-create.1.md
cli/man/grid-role-delete.1.md
cli/man/grid-role-list.1.md
cli/man/grid-role-show.1.md
cli/man/grid-role-update.1.md
cli/man/grid-role.1.md

Update man pages for role commands

---

cli/man/grid-admin-keygen.1.md
cli/man/grid-admin.1.md
cli/man/grid-database-migrate.1.md
cli/man/grid-database.1.md
cli/man/grid-keygen.1.md
cli/man/grid.1.md

This includes admin, database, and keygen subcommands.

Update man pages for utility commands

---

cli/man/grid-schema-create.1.md
cli/man/grid-schema-list.1.md
cli/man/grid-schema-show.1.md
cli/man/grid-schema-update.1.md
cli/man/grid-schema.1.md

Update man pages for schema commands

---

cli/man/grid-organization-create.1.md
cli/man/grid-organization-update.1.md
cli/man/grid-organization.1.md

Update man pages for Organization commands

---

cli/src/actions/roles.rs

Fix line wrapping in display_role()

---

ci/publish-crates
ci/publish-grid-crates

Add files for publishing grid-sdk to crates

---

cli/schemas/gdsn_3_1_schema.yaml

This matches the name of the schema owner in the docs

Update default schema owner

---

cli/src/transaction.rs
contracts/location/location.yaml
contracts/location/packaging/scar/manifest.yaml
contracts/product/packaging/scar/manifest.yaml
contracts/product/product.yaml
contracts/purchase_order/packaging/scar/manifest.yaml
contracts/purchase_order/purchase_order.yaml
contracts/schema/packaging/scar/manifest.yaml
contracts/schema/schema.yaml
contracts/track_and_trace/packaging/scar/manifest.yaml
contracts/track_and_trace/track_and_trace.yaml
integration/docker-compose.yaml

This change is required to make them compatible with the new pike addressing.

Update smart contracts to version 2

---

justfile

Fix just ci recipe

---

cli/src/transaction.rs

Change location family name and version to constants in CLI

---

cli/man/grid-agent-list.1.md
cli/man/grid-agent-show.1.md
cli/man/grid-organization-list.1.md
cli/man/grid-organization-show.1.md

Properly wrap pike man pages at 80 characters

---

cli/man/grid-agent.1.md
cli/man/grid-organization.1.md
cli/man/grid.1.md
cli/src/actions/mod.rs
cli/src/actions/roles.rs
cli/src/error.rs
cli/src/main.rs
cli/src/transaction.rs

A few small fixes for stabilization

Small Pike CLI fixes

---

daemon/Cargo.toml
daemon/src/splinter/run.rs

This change stabilizes the feature "scabbard-event-restart" by removing the feature.

Stabilize scabbard-event-restart

---

RELEASE_NOTES.md

Add release notes for the Grid 0.2 release

Add release notes for Grid 0.2

---

cli/packaging/ubuntu/completions/grid

Add bash completion for newly stabilized subcommands

---

cli/packaging/ubuntu/completions/grid

BACKPORT 0-2: Add bash completion for newly stabilized subcommands

---

cli/src/actions/database/mod.rs
cli/src/error.rs
cli/src/key.rs
cli/src/main.rs
contracts/location/src/handler.rs
contracts/location/src/state.rs
contracts/track_and_trace/src/addressing.rs
contracts/track_and_trace/src/handler.rs
daemon/src/database/error.rs
daemon/src/event/db_handler.rs
daemon/src/main.rs
daemon/src/rest_api/routes/records.rs
daemon/src/sawtooth/connection.rs
daemon/src/sawtooth/event.rs
daemon/src/splinter/app_auth_handler/error.rs
daemon/src/splinter/app_auth_handler/mod.rs
daemon/src/splinter/app_auth_handler/sabre.rs
sdk/src/hex.rs
sdk/src/locations/store/diesel/mod.rs
sdk/src/locations/store/diesel/operations/fetch_location.rs
sdk/src/locations/store/diesel/operations/list_locations.rs
sdk/src/track_and_trace/store/diesel/operations/fetch_reported_value_reporter_to_agent_metadata.rs
sdk/src/track_and_trace/store/diesel/operations/list_associated_agents.rs
sdk/src/track_and_trace/store/diesel/operations/list_properties_with_data_type.rs
sdk/src/track_and_trace/store/diesel/operations/list_proposals.rs
sdk/src/track_and_trace/store/diesel/operations/list_records.rs
sdk/src/track_and_trace/store/diesel/operations/list_reported_value_reporter_to_agent_metadata.rs
sdk/src/track_and_trace/store/diesel/operations/list_reporters.rs

This includes several commits to address lint warnings that were introduced in Rust 1.54.0.

Fix 1.54.0 lint for Grid 0.1

---

daemon/src/event/db_handler.rs
daemon/src/event/mod.rs
daemon/src/splinter/app_auth_handler/mod.rs
daemon/src/splinter/event/mod.rs
daemon/src/splinter/event/processors.rs
daemon/src/splinter/run.rs

BACKPORT 0.2: Avoid duplicate events

---

daemon/openapi.yaml

Add REST API specification for Purchase Order

---

RELEASE_NOTES.md

Add 0.2.2 release notes

---

sdk/src/protocol/errors.rs
sdk/src/protocol/location/mod.rs
sdk/src/protocol/location/payload.rs
sdk/src/protocol/location/state.rs
sdk/src/protocol/pike/mod.rs
sdk/src/protocol/pike/payload.rs
sdk/src/protocol/pike/state.rs
sdk/src/protocol/product/mod.rs
sdk/src/protocol/product/payload.rs
sdk/src/protocol/product/state.rs
sdk/src/protocol/purchase_order/mod.rs
sdk/src/protocol/purchase_order/payload.rs
sdk/src/protocol/purchase_order/state.rs
sdk/src/protocol/schema/mod.rs
sdk/src/protocol/schema/payload.rs
sdk/src/protocol/schema/state.rs
sdk/src/protocol/track_and_trace/mod.rs
sdk/src/protocol/track_and_trace/payload.rs
sdk/src/protocol/track_and_trace/state.rs

Adds rustdoc comments to the protocol code for each smart contract.

Add API docs to protocol module

---

contracts/purchase_order/src/workflow.rs

This fixes several typos in the PO workflow.rs file.

Fix typos in PO workflow

---

cli/man/grid-po-revision-list.1.md
cli/man/grid-po-revision-show.1.md
cli/man/grid-po-revision.1.md
cli/man/grid-po-show.1.md
cli/man/grid-po-version-create.1.md
cli/man/grid-po-version-list.1.md
cli/man/grid-po-version-update.1.md
cli/man/grid-po-version.1.md

Man pages based off of REST API spec from the purchase order hackathon.

Create PO revision man pages

---

examples/splinter/docker-compose-dockerhub.yaml

Update Splinter Docker Hub compose file to use 0.2

---

examples/splinter/docker-compose-dockerhub.yaml

BACKPORT 0-2: Update Splinter Docker Hub compose file to use 0.2

---

cli/src/actions/keygen.rs
cli/src/main.rs

BACKPORT 0-2: Change keygen system default backport

---

sdk/src/pike/permissions/mod.rs

This fixes a bug in the `has_permission` check. Previously, the check was not properly validating whether an inherited role was actually allowed to be inherited by its owner.

BACKPORT: Fix `has_permission()` bug

---

contracts/purchase_order/src/state.rs

This PR adds implementations for `get_purchase_order_version` and `set_purchase_order_version` for `PurchaseOrderState`. This also adds tests for all of the state methods (including the newly implemented ones).

Add state methods to get/set purchase order versions

---

contracts/purchase_order/src/state.rs
sdk/protos/purchase_order_state.proto
sdk/src/protocol/purchase_order/state.rs

This updates the PO version proto to reflect that a version can have multiple revisions.

Update PO version protos

---

contracts/purchase_order/src/state.rs

This change updates the `set_purchase_order_version` method in the
purchase order state module to consider if a purchase order version is
being updated. This means, when the po is fetched from state, the method
will now check to see if a version with the same ID exists in the list
and then it is removed and re-inserted with the updated version.
Otherwise, a new version is simply added to the end of the purchase
order's `versions` list.

Update `add` method in state to consider updates

---

contracts/purchase_order/src/handler.rs

Addresses https://github.com/hyperledger/grid/issues/985

Update po create action

---

sdk/src/rest_api/resources/error.rs

Part of https://github.com/hyperledger/grid/issues/1012

Stabilization changes for error response

---

contracts/purchase_order/src/handler.rs

The old update po error message for is_closed was ambiguous. This change
clarifies that the error is due to the closed constraint on the state
not being in sync with the is_closed payload.

Clarify po update error message for is_closed

---

contracts/purchase_order/src/handler.rs

This change adds concern for workflow constraints to the "create
version" action of the purchase order smart contract. This also updates
the tests written for this action to re-align with the updated
implementation.

Add concern for workflow constraints to "create vers" action

---

contracts/purchase_order/src/handler.rs

This change updates the "create po" action in the purchase order smart
contract to concern itself with workflow constraints. This adds further
validation when a user attempts to create a purchase order.
This change also adds a test to validate a purchase order may not be
created if the desired workflow state has a constraint it does not
fulfill.

Update "create po" action to handle constraints

---

cli/src/error.rs
sdk/src/client/purchase_order.rs
sdk/src/client/reqwest/mod.rs
sdk/src/error/client.rs

This adds more stabilization updates for the `client` feature following a second round of reviews.

Add more `client` feature stabilization updates

---

contracts/purchase_order/src/handler.rs

This change updates the purchase order smart contract handler to use the
`workflow_state` field rather than `workflow_status`. This also updates
references of "status" to "state" to avoid confusion.

Update references of "status" to "state"

---

sdk/src/workflow/mod.rs
sdk/src/workflow/state.rs
sdk/src/workflow/subworkflow.rs

This change adds module-level and public API documentation for the
workflow module within the Grid SDK.

Add documentation comments for workflow module

---

cli/man/grid-po-create.1.md
cli/man/grid-po-list.1.md
cli/man/grid-po-revision-list.1.md
cli/man/grid-po-revision-show.1.md
cli/man/grid-po-revision.1.md
cli/man/grid-po-show.1.md
cli/man/grid-po-update.1.md
cli/man/grid-po-version-create.1.md
cli/man/grid-po-version-list.1.md
cli/man/grid-po-version-show.1.md
cli/man/grid-po-version-update.1.md
cli/man/grid-po-version.1.md
cli/man/grid-po.1.md
cli/src/main.rs

Updates the purchase order man pages to match the current implementation. This mainly included updating the formatting of arguments and updating the example responses.

Update purchase order man pages

---

cli/src/actions/product.rs
cli/src/actions/purchase_order.rs
cli/src/actions/schema.rs
cli/src/main.rs
sdk/src/backend/splinter.rs
sdk/src/batch_processor/submitter/splinter.rs
sdk/src/batches/store/mod.rs
sdk/src/client/reqwest/mod.rs
sdk/src/protocol/schema/payload.rs
sdk/src/rest_api/resources/submit/v1/payloads/schema.rs
sdk/src/rest_api/resources/track_and_trace/v1/handler.rs

Fixes linting issues introduced in Rust 1.57

Fix linting issues from rust 1.57

---

contracts/purchase_order/src/workflow.rs

Corrects an accepted workflow being built as a proposed workflow.
Resolves: #1156

Fix mislabeled workflow

---

cli/src/actions/purchase_order.rs

The purchase order batch action functions all contained the same logic.
This change consolidates that logic into two functions, and adds a test
to verify that it acts as expected.

Simplify po cli batch actions and add tests

---

cli/src/actions/products.rs
cli/src/http.rs
sdk/src/backend/splinter.rs
sdk/src/batch_processor/submitter/splinter.rs
sdk/src/batches/store/mod.rs
sdk/src/client/reqwest.rs
sdk/src/protocol/schema/payload.rs
sdk/src/rest_api/resources/submit/v1/payloads/schema.rs
sdk/src/rest_api/resources/track_and_trace/v1/handler.rs
sdk/src/workflow/mod.rs
sdk/src/workflow/state.rs

Rust 1.57 clippy updates for the 0-2 branch

v0.2 Rust 1.57 clippy updates

---

sdk/src/purchase_order/addressing.rs

Fix small typo in purchase_order/addressing

---

griddle/Cargo.toml

Update griddle version to match the rest of the repo

---

griddle/Cargo.toml

0-2: Update griddle version to match the rest of the repo

---

cli/src/actions/mod.rs
cli/src/error.rs
cli/src/transaction.rs

Update copyright to 2021 for all that were 2019 for PO CLI

---

cli/src/actions/mod.rs

Move PO CLI public modules before function definitions

---

sdk/Cargo.toml

Stabilize "workflow" feature

---

sdk/protos/purchase_order_payload.proto

Fixes protobuf numbering to be consecutive.

Fix numbers in proto messages

---

contracts/purchase_order/src/handler.rs
contracts/purchase_order/src/payload.rs

Updates the "update_purchase_order" method to handle a list of versions. This also updates the method to correctly handle versions depending on the intended update state. This also updates the related tests.

Update "update po" action in po smart contract

---

cli/src/actions/schema.rs
contracts/pike/src/handler.rs
contracts/track_and_trace/src/handler.rs
sdk/src/backend/sawtooth.rs
sdk/src/batch_processor/submitter/sawtooth.rs
sdk/src/rest_api/resources/batches/v1/handler.rs

More info regarding clippy updates:
https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-158

Address issues from linting introduced in rust 1.58

---

contracts/purchase_order/src/handler.rs

This updates the "update version" action in the purchase order smart contract handler to match the structuring of the other action handlers and adds validation of the updated state from the current transaction. This also updates the affected tests from these updates. ~This PR will be updated as ready to be reviewed once #1213 is merged.~

Update version action

---

contracts/purchase_order/src/handler.rs

This updates the `create_version` function in the purchase order smart
contract that handles the creation of a purchase order version. This
change updates the workflow state used to validate a user's permission
to create an object and enter it into a workflow and the general layout
of the function to match the layout of the other actions. This also
updates affected tests. 
This PR will need to be rebased on #1251

Update `create_version` action in handler

---

contracts/purchase_order/src/handler.rs

Validate that the po versions are consistently not accepted with the
parent po when the po is no longer accepted.

Add test to validate removing accepted version

---

cli/man/grid-download-xsd.1.md

Add instructions on what steps the utility specifically takes when
downloading and extracting the XSD files.

Add in-depth instructions for download tool

---

.github/workflows/publish-release.yaml
ci/build-contracts
docker/compose/contracts.yaml

Add files for publishing a release when a tag is pushed

---

RELEASE_NOTES.md

Add release notes for v0.3.2

---

.github/workflows/cache-xml.yaml

Cache Grid XML in Github Actions

---

cli/src/actions/purchase_order.rs
cli/src/error.rs
contracts/location/src/main.rs
contracts/product/src/main.rs
contracts/purchase_order/src/handler.rs
contracts/purchase_order/src/main.rs
contracts/schema/src/main.rs
contracts/track_and_trace/src/main.rs
sdk/src/protocol/location/payload.rs
sdk/src/protocol/location/state.rs
sdk/src/protocol/pike/payload.rs
sdk/src/protocol/pike/state.rs
sdk/src/protocol/product/payload.rs
sdk/src/protocol/product/state.rs
sdk/src/protocol/purchase_order/payload.rs
sdk/src/protocol/purchase_order/state.rs
sdk/src/protocol/schema/payload.rs
sdk/src/protocol/schema/state.rs
sdk/src/protocol/track_and_trace/payload.rs
sdk/src/protocol/track_and_trace/state.rs
sdk/src/rest_api/resources/submit/v1/payloads/location.rs
sdk/src/rest_api/resources/submit/v1/payloads/pike.rs
sdk/src/rest_api/resources/submit/v1/payloads/product.rs
sdk/src/rest_api/resources/submit/v1/payloads/schema.rs

Backport 0-3: Fix 1.59 clippy errors

---

sdk/Cargo.toml
sdk/src/batch_tracking/store/diesel/mod.rs
sdk/src/batch_tracking/store/diesel/models.rs
sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
sdk/src/batch_tracking/store/diesel/operations/mod.rs
sdk/src/batch_tracking/store/mod.rs

This adds an implementation for the `BatchTrackingStore` `get_batch()` operation. This also adds a unit test to test adding and fetching a batch.

Add `get_batch` db operation

---

RELEASE_NOTES.md

Add release notes for v0.3.3

---

ci/grid-dev-buildx
ci/grid-dev.yaml
cli/Dockerfile
contracts/location/Dockerfile
contracts/pike/Dockerfile
contracts/product/Dockerfile
contracts/purchase_order/Dockerfile
contracts/schema/Dockerfile
contracts/track_and_trace/Dockerfile
daemon/Dockerfile
docker/lint
docker/tests
griddle/Dockerfile

Bump grid-dev version to v10 to differentiate it from 0-3

---

sdk/src/batch_tracking/store/diesel/mod.rs
sdk/src/batch_tracking/store/diesel/models.rs
sdk/src/batch_tracking/store/diesel/operations/change_batch_to_submitted.rs
sdk/src/batch_tracking/store/diesel/operations/mod.rs
sdk/src/batch_tracking/store/mod.rs

This implements the `change_batch_to_submitted` DB operation for the
Batch Tracking store. This includes a couple unit tests for the
operation as well.

Add `change_batch_to_submitted` operation

---

sdk/src/batch_tracking/store/diesel/mod.rs
sdk/src/batch_tracking/store/diesel/operations/list_batches_by_status.rs
sdk/src/batch_tracking/store/diesel/operations/mod.rs

This adds an operation to get a list of batches by their DLT status. This also adds a unit test for this operation.

Add `list_batches_by_status` operation

---

sdk/src/batch_tracking/store/diesel/mod.rs
sdk/src/batch_tracking/store/diesel/operations/get_failed_batches.rs
sdk/src/batch_tracking/store/diesel/operations/mod.rs
sdk/src/batch_tracking/store/mod.rs

This adds an operation to get failed batches. This also adds a unit test for the operation.

Add `get_failed_batches` operation

---

sdk/Cargo.toml
sdk/src/batch_submission/mod.rs
sdk/src/batch_submission/submission/mod.rs
sdk/src/batch_submission/submission/url_resolver/basic_url_resolver.rs
sdk/src/batch_submission/submission/url_resolver/mod.rs
sdk/src/lib.rs

Adds the url_resolver submitter subcomponent and the batch_submission
module structure that contains it.
Resolves: #1414

Add `batch_submission` mod and `url_resolver`

---

sdk/src/batch_tracking/store/diesel/mod.rs
sdk/src/batch_tracking/store/diesel/models.rs
sdk/src/batch_tracking/store/diesel/operations/change_batch_to_submitted.rs
sdk/src/batch_tracking/store/diesel/operations/get_batch.rs
sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs
sdk/src/batch_tracking/store/diesel/operations/update_batch_status.rs
sdk/src/batch_tracking/store/mod.rs

This adds support for looking up batches by `data_change_id` to batch
tracking operations that take a batch ID as an argument.

Add support for `data_change_id`s

---

sdk/src/batch_tracking/store/diesel/models.rs
sdk/src/batch_tracking/store/mod.rs

This makes the `service_id` field on the `TrackingBatch` struct an
`Option`. This is in support of work on the batch queuer.

Make `TrackingBatch` `service_id` an `Option`

---

sdk/src/batch_tracking/store/diesel/mod.rs

This cleans up the batch tracking store tests by putting repetitive,
shared code into functions.

Clean up `BatchTrackingStore` tests

---

sdk/src/backend/splinter.rs

Update `/batches` endpoint to correctly return errors from Splinter

---

RELEASE_NOTES.md

Add release notes for v0.3.4

---

justfile

Test grid-ui docker build in CI

---

CODEOWNERS
MAINTAINERS.md

Make Chris Eckhardt a Grid maintainer

---

CODEOWNERS
MAINTAINERS.md

Signed-off-by: Amelia Bradley <bradley@bitwise.io>

Update maintainer name

---

griddle/Cargo.toml

Add copyright to Griddle's Cargo.toml file

---

sdk/src/scope_id/service/id/circuit.rs
sdk/src/scope_id/service/id/service.rs

Clean up unused imports in scope_id tests

---

justfile

Add just recipe for fixing typos

---

sdk/Cargo.toml
sdk/src/batch_submission/mod.rs
sdk/src/batch_submission/submission/mod.rs
sdk/src/batch_submission/submission/submitter/batch_submitter/async_batch_submitter.rs
sdk/src/batch_submission/submission/submitter/batch_submitter/mod.rs
sdk/src/batch_submission/submission/submitter/mod.rs
sdk/src/batch_submission/submission/submitter_observer/mod.rs
sdk/src/batch_submission/submission/url_resolver/basic_url_resolver.rs
sdk/src/batch_submission/submission/url_resolver/mod.rs
sdk/src/scope_id/mod.rs

Adds the required traits and implementations for submitting batches
to the DLT.

Add batch submitter traits and implementations

---

.github/settings.yml
README.md

[Pending vote](https://github.com/hyperledger/toc/issues/82)

Move Grid to EOL
