contracts/track_and_trace/Cargo.toml
=> Update Grid Track and Trace to use sawtooth-sdk = 0.2

docs/source/_templates/indexcontent.html
A previous commit changed the file name for the Grid Track and Trace Family
Specification, but did not change the "pathto" name in the landing page.
This commit fixes the problem.
=> Fix Grid T+T doc link in indexcontent.html

README.md
- Update repo description to explain the Hyperledger Grid project and goals
- Summarize the three main grid repos (didn't include grid-website, because it's
not about the Grid software)
- Add "How to Participate" section with information intended to encourage
high-level contributions: ideas, use case, and examples
- Remove the "Documentation" section because "how to run and extend Hyperledger
Grid" distracts from the focus on shaping the project direction
- Add "More Information" section with links
- Clean up the "License" section
=> Update and expand README.md for grid repo

CONTRIBUTING.md
- Replace obsolete project names with Hyperledger Grid
- Replace the development-centric details with an overview and a link to
the Contributing page on the Grid website.
=> Update CONTRIBUTING.md in grid repo

contracts/track_and_trace/src/handler.rs, sdk/protos/schema_payload.proto, sdk/protos/schema_state.proto, sdk/protos/track_and_trace_payload.proto, sdk/protos/track_and_trace_property.proto
This required temporarily renaming Track and Trace's PropertyValue to TrackAndTracePropertyValue because protobuf would not build two instances of PropertyValue. We plan to update Track And Trace to use Grid Schema once it has been completed.
=> Add initial Grid Schema Protos

sdk/src/protocol/mod.rs, sdk/src/protocol/schema/mod.rs, sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs
This module will be used by componets that do not
wish to use the protobuf directly. This commit
includes the protocol definations for the Grid Schema
payload and state protos.
=> Add protocol module to Grid SDK

sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs, sdk/src/protos.rs
This allows a developer to go directly from bytes to
the native implementation and from the native
implementation to the bytes. This will be useful
when writing smart contracts.
=> Add IntoBytes and FromBytes to protocol

daemon/src/config.rs, daemon/src/error.rs, daemon/src/main.rs
This PR adds a GridConfig and GridConfigBuilder to transform CLI args (and future configuration files) into a configuration object.  Defaults are all managed via the builder.
=> Add GridConfig for gridd

daemon/openapi.yaml
This PR adds initial openapi spec doc for the Grid REST API. 
It defines endpoint to submit batches, get batch status, and get schema from the reporting database. 
To visualize the document [Swagger](http://editor.swagger.io/) is a good tool.
=> Add initial REST API specs

daemon/Cargo.toml, daemon/src/config.rs, daemon/src/error.rs, daemon/src/main.rs, daemon/src/rest_api/error.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/route_handler.rs
Adds initial setup for Rest API which adds a basic Hello World
route and begins a server using Actix.
There is currently a test in place which uses a TestServer to access the index route currently in place. However, you can also test this initial route directly by running `cargo run` from the `daemon` folder. Then, run the command `curl http://localhost:8080` in a terminal, or access `http://localhost:8080` from a web browser and you should see the message "Hello world!" in the response. Use Ctrl+C to shut down this process. 
=> Add initial Rest API

daemon/src/config.rs, docker-compose.yaml
To use `localhost` as part of an address does not work with Actix. It compiles but when you try to send a request, there's no response. I found no documentation on this problem, but all Actix examples use `127.0.0.1` rather than localhost. This PR updates updates the default validator
and REST API endpoints to use `127.0.0.1` instead of `localhost`.
=> Change default validator and rest_api addresses

daemon/Cargo.toml, daemon/src/error.rs, daemon/src/main.rs, daemon/src/rest_api/error.rs, daemon/src/rest_api/mod.rs
This PR adds the `ctrlc` dependency, and creates a shutdown handle, join handle tuple to be used by the main method. 
It runs the rest api on its own thread, which allows other activities (the future event processor for example) to also be started.
=> Gracefully shutdown the REST API

.gitignore, contracts/schema/Cargo.toml, contracts/schema/Dockerfile, contracts/schema/Dockerfile-installed, contracts/schema/src/handler.rs, contracts/schema/src/main.rs, contracts/schema/src/payload.rs, contracts/schema/src/state.rs, docker-compose-installed.yaml, docker-compose.yaml, sdk/protos/schema_state.proto, sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs
This PR implements the Smart contract described in
the Grid Primitives RFC
hyperledger/grid-rfcs#4
Note this does not include the permission check of if
the agent has the permission can_create_schema for the
organization. This we will be added in a separate PR
after the implementation of Permission checker in the
Grid SDK.
=> Add Grid Schema Smart contract  

daemon/Cargo.toml, daemon/src/rest_api/route_handler.rs
Implement GET batch_statuses endpoint as defined in [openapi spec documentation](https://github.com/hyperledger/grid/blob/440d3b4e0b59d215063cdabd2342f7f32fe47c21/daemon/openapi.yaml#L66).
=> Batch statuses endpoint

daemon/Cargo.toml, daemon/openapi.yaml, daemon/src/database/helpers/agents.rs, daemon/src/database/schema.rs, daemon/src/main.rs, daemon/src/rest_api/error.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/route_handler.rs, daemon/test/docker-compose.yaml
Adds a connection for the rest API to the database created in pr #32. 
This pr is now dependent on #43 which adds the necessary agents table for this api route.
For testing, run `docker-compose.yaml` in the `daemon/test` directory. Then, run `cargo test --features test-api`
=> Connect rest API to database & get_agents route

sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/permissions.rs
PermissionChecker is a helper that can be used to check if a Pike agent has a certain permission. It can be imported from the Grid SDK into a contract to execute Pike functionality. This implementation is fairly simple, but it can be extended to allow smart permission checks later on.
In order to test the PermissionChecker, I moved the MockTransactionContext implementation from the Schema contract into the Grid SDK.  This can be used to test other contracts or SDK functionality that requires a TransactionContext. MockTransactionContext is backed by a HashMap contained in a RefCell. Due to the properties of RefCell, It should only be used in unit tests.
=> Implement Pike PermissionChecker in Grid SDK

contracts/pike/Cargo.toml, contracts/schema/Cargo.toml, contracts/track_and_trace/Cargo.toml
This will allow sabre smart contracts to be compiled on more
platforms when not compiling into wasm.
=> Replace unix with not wasm32 in platform-specific dependencies

contracts/schema/src/handler.rs, contracts/schema/src/state.rs
Based on #44 
Adds permission checks to the Schema contract. Also makes some tweaks to the PermissionChecker and GridSchemaState to cleanly integrate this functionality.
=> Update Grid Schema Smart Contract to use the Permission Checker

cli/Cargo.toml, cli/src/actions/agents.rs, cli/src/actions/mod.rs, cli/src/actions/organizations.rs, cli/src/actions/schemas.rs, cli/src/error.rs, cli/src/main.rs, cli/src/transaction.rs
This PR implements the CLI commands for creating and updating a schema. 
~It is based on PR #45. Commits `Add inputs/outputs to add_transaction method` onward are up for review in this PR~. 
To properly send create and update schema  transactions first you have to create a Pike Organization and Agent.
`cargo run -- -vv --url http://127.0.0.1:8080 --wait 30 -k {path_to_public_key} organization create org_id_1 my_org_name my_org_address`
`cargo run -- -vv --url http://127.0.0.1:8080 --wait 30 -k {path_to_key} agent create org_id_1  {path_to_public_key} true`
`cargo run -- -vv --url http://127.0.0.1:8080  --wait 30 -k  {path_to_key} schema create {path_to_yaml_file_with_schema_definition}`
```yaml
- name: "Lightbulb"
description: "Example Lightbulb schema"
properties:
- name: "size" …
```
=> CLI command for create  and update schema

daemon/openapi.yaml, daemon/src/database/helpers/organizations.rs, daemon/src/database/schema.rs, daemon/src/rest_api/error.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/organizations.rs
This PR implements the endpoints GET /organization and GET/organization/{id}.  It includes tests and updates to the REST API spec doc. 
To run the tests:
`cargo test --features test-api --  --test-threads=1 `
~Based on #56.~
=> Add organization endpoints

cli/src/actions/schemas.rs, daemon/Cargo.toml, daemon/migrations/2019-04-19-191743_create_grid_schema_tables/down.sql, daemon/migrations/2019-04-19-191743_create_grid_schema_tables/up.sql, daemon/src/database/models.rs, daemon/src/database/schema.rs, docs/source/transaction_family_specifications/grid_schema_family_specification.rst, sdk/protos/schema_state.proto, sdk/src/protocol/pike/payload.rs, sdk/src/protocol/pike/state.rs, sdk/src/protocol/schema/state.rs
This PR: 
- Adds LatLong as a DataType for a PropertyDefinition as defined in  hyperledger/grid-rfcs#4.
- Adds a new proto message definition for LatLong and implement a native version of it.
- Fixes a couple of formatting issues and typos.
- Updates the Grid schema family specification document to include information about the LatLong data type. 
~This PR might need to be updated if other changes get merged first, such as #46 and #52.~ Updated!
=> Add Latitude/Longitude to PropertyDefinition 

daemon/openapi.yaml, daemon/src/database/helpers/agents.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/routes/agents.rs, daemon/src/rest_api/routes/mod.rs
Finishes the agents route with the /agent/{public_key} route which allows the rest API to fetch an agent based on the public key. 
Test with: `cargo test --features test-api --test-threads=1`
=> Add /agent/{public_key} route

daemon/src/database/helpers/grid_schemas.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/schemas.rs
Adds the necessary functions, handlers, and implementations for the /schema and /schema/{name} routes to list and fetch grid schemas, respectively. Also adds tests for these two routes. 
To test: `cargo test --features test-api -- --test-threads=1`
=> Rest API routes for Grid Schemas

contracts/track_and_trace/src/handler.rs, contracts/track_and_trace/src/payload.rs, contracts/track_and_trace/src/state.rs, sdk/protos/deprecated_track_and_trace_payload.proto, sdk/protos/track_and_trace_payload.proto, sdk/protos/track_and_trace_property.proto, sdk/protos/track_and_trace_proposal.proto, sdk/protos/track_and_trace_record.proto, sdk/protos/track_and_trace_state.proto, sdk/src/protocol/errors.rs, sdk/src/protocol/mod.rs, sdk/src/protocol/track_and_trace/mod.rs, sdk/src/protocol/track_and_trace/payload.rs, sdk/src/protocol/track_and_trace/state.rs
Adds track and trace protobuf definition that are compatible with Pike and Schema, as well as their corresponding native objects
=> Track and Trace Protocol for SDK

sdk/src/protocol/track_and_trace/state.rs
Add into_builder methods to all Track and Trace state protocols.
Converting protocols into builders will facilitate the process to update
values and reduce chances for mistakes.
=> Add conversion from TnT state protocols to builder

cli/src/actions/schemas.rs, cli/src/main.rs
Adds the CLI commands to list all GridSchemas and show a GridSchema based on the schema name. 
~Note: running `cargo test` in the cli directory will return an error because of a typo getting fixed up in pr #69 although no unit tests were added for these commands~
PR #69 was merged, this no longer stands
=> Add CLI commands to show and list Grid Schemas

daemon/migrations/2019-04-04-145511_create-pike-tables/up.sql, daemon/migrations/2019-05-02-191951_create_tnt_tables/up.sql, daemon/openapi.yaml, daemon/src/database/helpers/track_and_trace.rs, daemon/src/database/models.rs, daemon/src/database/schema.rs, daemon/src/event/block.rs, daemon/src/rest_api/error.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/records.rs
This implements the `GET /record/{record_id}` endpoint. List endpoint will be a later PR. Does not include Properties as it will be the same query as for the `GET /record/{record_id}/property/{property_name}` endpoint, which is a different story.
=> Implement Fetch Record endpoint

daemon/migrations/2019-04-19-191743_create_grid_schema_tables/down.sql, daemon/migrations/2019-04-19-191743_create_grid_schema_tables/up.sql, daemon/migrations/2019-05-02-191951_create_tnt_tables/up.sql, daemon/src/database/helpers/grid_schemas.rs, daemon/src/database/helpers/track_and_trace.rs, daemon/src/database/models.rs, daemon/src/database/schema.rs, daemon/src/event/block.rs
This PR:
- Removes the `grid_property_table` and adds its fields to the `reported_value` table.  This change is necessary because currently is impossible to associate rows in the reported_value table to rows in the grid_property_value table. The information in the `grid_property_value` needs to be more tightly connected to the Track and Trace Record. So it makes sense to go away with that table completely and keep that information in a TnT specific table. 
- Adds `receiving_agent parameter` to the `update_proposal_end_block_num` method in the database track_and_trace helpers. To uniquely identify a proposal you need `record_id` + the receiving agent key.
=> Update TnT SDE

cli/Cargo.toml, cli/src/error.rs, cli/src/transaction.rs, contracts/pike/Cargo.toml, contracts/pike/Dockerfile, contracts/pike/pike.yaml, contracts/schema/Cargo.toml, contracts/schema/Dockerfile, contracts/schema/schema.yaml, contracts/track_and_trace/Cargo.toml, contracts/track_and_trace/Dockerfile, contracts/track_and_trace/track_and_trace.yaml, docker-compose.yaml, sdk/Cargo.toml
This is built on top of #50 
This includes the version of the sabre-sdk to 0.3 and updating the grid cli to send all transactions wrapped in a sabre transaction.
You can test this by running docker-compose
`docker-compose up --build`
move to the grid/cli and create a new pike organization with the following command:
`cargo run -- -vv --url http://localhost:8080 organization create org_1 OrgTest test_address`
You will see the sabre tp execute a transaction and then you can see the organization by checking hte restapi:
`http://localhost:8080/organization`
=> Updates the Grid CLI to send Sabre transactions

contracts/pike/src/handler.rs, contracts/schema/src/handler.rs, contracts/track_and_trace/src/handler.rs, contracts/track_and_trace/src/state.rs, sdk/src/permissions.rs, sdk/src/protocol/pike/payload.rs, sdk/src/protocol/pike/state.rs, sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs, sdk/src/protos.rs
Fix following nightly warning:
trait objects without an explicit dyn are deprecated
Note: generate protobufs will still throw this error.
=> Add dyn to trait objects

contracts/pike/src/handler.rs, docs/source/transaction_family_specifications/pike_transaction_family.rst
Admin agents should not be able to remove the admin role from
themselves. This commit adds a check and returns an InvalidTransaction
if an admin tries to submit a transaction that would remove the role
admin from themselves.
=> Fix bug in Pike contract

contracts/track_and_trace/track_and_trace.yaml, docker-compose.yaml
Add Schema and Pike namespace permissions to the Track and Trace
contract. This allows for TnT Record transactions to be submitted.
=> Update TnT contract namespace permissions

cli/src/actions/keygen.rs, cli/src/actions/mod.rs, cli/src/key.rs, cli/src/main.rs
This PR adds the keygen command to the CLI, this command generates a public/private key pair that can be used to sign transactions.
=> Add keygen command to CLI

daemon/openapi.yaml, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/records.rs
Adds the "schema" type field to record responses. This data exists in the DB but did not get put in the response. It should be there to identify the type of schema that the record is based on.
=> Add schema to record responses

contracts/pike/Dockerfile, contracts/schema/Dockerfile, contracts/track_and_trace/Dockerfile, docker/tests
The updated version of cargo in the nightly toolchain throws an error on `cargo new --bin contracts/[CONTRACT]` if the contracts directory doesn't exist.
=> Make contracts dir before cargo new

contracts/track_and_trace/src/handler.rs, daemon/src/database/helpers/grid_schemas.rs, daemon/src/database/helpers/track_and_trace.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/records.rs
Currently, if a transaction is submitted to create a new record in which all required properties are in the payload, but some of the optional properties are missing the transaction will fail, even though it should be valid. 
This PR fixes that bug and updates the REST API to accommodate these changes.
=> Fix bug in TnT transction handler

cli/Cargo.toml, cli/src/actions/database.rs, cli/src/actions/mod.rs, cli/src/error.rs, cli/src/main.rs, daemon/Dockerfile, daemon/src/database/mod.rs, daemon/src/main.rs, daemon/src/rest_api/routes/mod.rs, docker-compose.yaml
This PR:
- Adds CLI command to run db migrations 
- Removes the capability of running the database migrations when the daemon starts up. 
- Adds a check on daemon start up that the migrations have been applied, and returns an error if they have not.
=> Move DB Migrations to CLI

contracts/pike/Dockerfile, contracts/schema/Dockerfile, contracts/track_and_trace/Dockerfile, docker/tests
We no longer need rust nightly to compile into wasm.
=> Remove rust nightly from smart contract dockerfiles

contracts/product/src/handler.rs, contracts/product/src/payload.rs, contracts/product/src/state.rs, sdk/protos/product_payload.proto, sdk/src/protocol/mod.rs, sdk/src/protocol/product/mod.rs, sdk/src/protocol/product/payload.rs, sdk/src/protocol/product/state.rs
This PR contains rust native implementations of the data models and functions associated, in product
=> Add rust native implementation of product

contracts/product/src/state.rs, contracts/product/src/validation.rs
When deleting a product, if there is only a single product stored at a
given address then we should delete that entry in state. The current
implementation does not handle an address with exactly one product at an
address - this commit implements the state entry deletion in that case.
Signed-off-by: Patrick-Erichsen <Patrick.Erichsen@target.com>
=> Implement state entry deletion on Product contract

daemon/migrations/2019-07-03-161310_create_product_table/up.sql, daemon/migrations/2019-08-08-145850_create_product_property_table/up.sql, daemon/src/database/helpers/products.rs, daemon/src/database/models.rs, daemon/src/database/schema.rs, daemon/src/event/block.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/products.rs
- Detect StateChange_Type::DELETE in state delta subscriber for GRID_PRODUCT
- Add RemoveProduct(address, current_block_num) as a DbInsertOperation
- Add delete_product and delete_product_property_values functions to db helpers
- Add product_address field to product and product_property_value tables
- Add product_address field to associated Product and ProductPropertyValue structs
- Update all product properties by property_id instead of property_name
See [Jira](https://jira.hyperledger.org/browse/GRID-105)
=> Implement Product Database Operations

cli/Cargo.toml, cli/src/main.rs, cli/src/sawtooth/mod.rs, cli/src/splinter/mod.rs, daemon/Cargo.toml, daemon/src/main.rs, daemon/src/sawtooth/mod.rs, daemon/src/splinter/mod.rs
This adds sawtooth and splinter features to Cargo.toml for daemon and cli, with associated modules. The intent is that sawtooth-specific code will go into the sawtooth module and splinter-specific code will go into the splinter module.
=> Add splinter and sawtooth features

daemon/src/event/error.rs, daemon/src/event/mod.rs, daemon/src/sawtooth/event.rs
Add the `CommitEvent` struct, which will be used as a generic way to
represent a commit and its associated state changes from some arbitrary
source.
Add a `TryFrom<&[SawtoothEvent]>` implementation for `CommitEvent` that
converts Sawtooth events into a native `CommitEvent` for Grid.
=> Add generic CommitEvent

daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, daemon/src/main.rs, daemon/src/sawtooth/event.rs
- Update the EventConnection trait's recv method to return a CommitEvent
- Update the EventHandler trait to take a single CommitEvent
- Rename the BlockEventHandler to DatabaseEventHandler
- Update DatabaseEventHandler to construct database block and operations
from CommitEvent
=> Update EventHandlers to take CommitEvents

daemon/migrations/2019-12-10-231138_update-block-schema/down.sql, daemon/migrations/2019-12-10-231138_update-block-schema/up.sql, daemon/src/database/helpers/blocks.rs, daemon/src/database/models.rs, daemon/src/database/schema.rs, daemon/src/event/db_handler.rs
Adds a new primary key to the Block schema, which is just a serial ID. This is required to allow commits sourced from difference services to coexist in the database.
=> Add serial id and source to Block schema

daemon/src/config.rs, daemon/src/error.rs, daemon/src/main.rs
Adds two type of prefixes that can be added to the `--connect` url.
`--connect` now accepts the following optional prefixes:
`sawtooth` - used to specfiy that the url is for connecting to a
sawtooth validator.
`splinter` - used to specfiy that the url is for connecting to a
splinter node.
=> Add prefixes to connect endpoint

cli/Cargo.toml, cli/src/actions/admin.rs, cli/src/actions/mod.rs, cli/src/main.rs, daemon/Cargo.toml, daemon/packaging/ubuntu/postinst
This PR adds the subcommand `admin keygen` to the grid CLI.  This command generates a key for the grid daemon to use when creating scabbard services on splinter circuits and initializing the service with the necessary grid smart contracts.
It is an experimental feature guarded by the feature `"admin-keygen"`.
Additionally, 
- The deb package will create the directory `/etc/grid/keys`, where this key will be stored.
=> Add admin keygen experimental CLI command

daemon/src/config.rs
Endpoint not long prepends a protocol to the string that's passed to it,
and makes no assertions about the protocol type
=> Remove prepending of protocol

examples/splinter/docker-compose.yaml
Generate the admin keys in the docker-compose file for the grid-on-splinter example.  These are generated using the `--skip` flag, so that they are not generated if the exist.  The keys are stored in an individual volume for each grid daemon instance.
=> Generate gridd admin keys in compose

daemon/src/database/helpers/commits.rs, daemon/src/event/mod.rs, daemon/src/main.rs, daemon/src/sawtooth/event.rs, daemon/src/splinter/event.rs
The last commit id should be optional, as the decision with what to do with the value should be left to the underlying implementation of the `EventConnection`.  In Sawtooth's case, it will pass the
`NULL_BLOCK_IDENTIFIER`.  In Splinter's case, it will omit the argument when subscribing for events.
=> Make last commit id optional

cli/src/actions/admin.rs, cli/src/actions/keygen.rs, cli/src/actions/mod.rs, cli/src/key.rs
This makes the output nicer when calling `cat` on a key file.
Also updates the reading of key files to trim any whitespace, which is
necessary now that key files contain a newline.
=> Add newline to key files generated by grid CLI

cli/src/actions/admin.rs, cli/src/main.rs
This PR:
- Changes the `active` argument in the CLI command `agent create` and `agent update` to be flags: `--active` `--not-active`. Orginially the argument took a boolean value
- Changes the `--roles` argument  in the CLI command `agent create` and `agent update` so it accepts comma separated values
- Changes the `verbose` flag to be global, meaning it can be used in any of the subcommands.
- Adds a `quiet` global flag to omit the output
- Changes some printlns to debug level log
=> CLI cleanup

cli/src/actions/admin.rs, cli/src/actions/keygen.rs, cli/src/actions/mod.rs
Prior to this commit, the keygen command was writing the private key twice to the file, once without a new line, once with, creating a too-long private key string. This first write has been removed.
Additionally, removed the unnecessary wrapper function around writeln.
=> Remove double write of private key

daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, examples/splinter/README.md
This PR takes the `service_id` value from the commit event and saves it with each record in the database.
Additionally,
- add some more debug statements
- correct the example for the `gridd-beta` node.
=> Save service id to database

bin/run_integration_tests, bin/run_unit_tests, cli/Cargo.toml, cli/tests/product.rs, cli/tests/yaml/test_product_create.yaml, cli/tests/yaml/test_product_update.yaml, daemon/test/docker-compose.yaml, docker/tests, integration/.env, integration/docker-compose.yaml
- Run tests with `docker-compose -f integration/docker-compose.yaml up`
- Create tests that call CLI functions and check their effects
- Test product create success
- Test product update success
- Test product delete success
- Add these tests to the `bin/run_integration_tests` script
- Add calls for CLI unit tests in `daemon/test/docker-compose.yaml` and `docker/tests`
Note: the unit tests are called by name to avoid also calling integration tests, which
will fail without all services running.
- Format docker compose yaml
This adds a separate docker-compose.yaml (`integration/docker-compose.yaml`) to run integration tests. The compose file is the same as the default `docker-compose.yaml` with logging turned down and a `cargo test` command to run the integration tests after starting the …
=> Add integration testing for Product

cli/src/main.rs
Also updates the help to describe the format of the
key-value pairs.
=> Update metadata option to work with comma-separated values

daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, daemon/src/main.rs, daemon/src/splinter/app_auth_handler/node.rs
When a state change is received for a key that gridd does not recognize,
this should be logged as a debug message rather than an error. It's
perfectly normal for state to change in ways that aren't directly
relevant to the grid daemon.
=>  Log as debug when unknown state change received 

cli/tests/product.rs
The pike agent command was updated to have --active instead of true and --roles was replaced with --role
=> Update product cli tests for updated pike agent command

ci/grid-dev
Performing the find at the root can cause problems if components have
dependencies that can't be compiled to wasm. This should speed up builds as
well.
=> Only run wasm builds for smart contracts in dev image

cli/src/main.rs, examples/splinter/README.md, examples/splinter/docker-compose.yaml
Adds environment variables to the Splinter example docker-compose file for the key and url CLI arguments, as well as checks within the Grid CLI for these values. 
Also updates the README to remove the use of -k and --url in the commands for gridd.
=> Add env variables for key and url CLI args

daemon/src/splinter/app_auth_handler/node.rs
`get_node_id` now tries indefinitely to check the node status doubling
it's wait time after each failed attempt with a maximum wait time of 300
seconds.
=> Add exponential back-off to status check

cli/src/actions/admin.rs, cli/src/main.rs
This PR fix some of the log levels in the Grid CLI. Now the `grid keygen` and `grid admin keygen` CLI commands to display an output unless the `--quiet` flag is present.
=> Display output for keygen commands

cli/src/actions/agents.rs, cli/src/actions/organizations.rs, cli/src/actions/products.rs, cli/src/actions/schemas.rs, cli/src/main.rs, examples/splinter/README.md, examples/splinter/docker-compose.yaml
Adds a `GRID_SPLINTER_SERVICE_ID` environment variable to the gridd alpha and beta docker containers for the Splinter example. Also changes around the actions functions to expect Option<String> instead of Option<&str> because the environment variable gets returned as Option<String> but is unable to directly be converted using `deref` because the value being created is temporary when fetched using `env::var`.
=> Service-id environment variable

examples/splinter/README.md, examples/splinter/docker-compose.yaml
Add scabbard-cli services for both nodes in the grid on splinter
example and add instructions to the example's README for uploading a new
smart contract to an existing circuit.
This PR depends on https://github.com/Cargill/splinter/pull/475
=> Add .scar upload demonstration to splinter example

daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, daemon/src/sawtooth/event.rs, daemon/src/splinter/event.rs
Using docker-compose.yaml and grid-cli to create a test organization, I ended up with an empty string as service_id in the PostgreSQL db. gridd expects service_id to be null in places like <https://github.com/hyperledger/grid/blob/master/daemon/src/database/helpers/organizations.rs#L72>. Thus the gridd REST API returns nothing. This seems to fix the issue.
=> Change CommitEvent service_id to Option<String>

examples/splinter/README.md, examples/splinter/docker-compose.yaml
To test:
1. Makes sure to pull the most up to date splinter docker images 
```
docker-compose -f examples/splinter/docker-compose.yaml pull
```
2. Follow the instructions in the README.
=> Update README Grid on Splinter example

examples/splinter/README.md
Adds documentation for the environment variables defined in the Splinter example docker-compose file.
=> Add environment variable documentation

examples/splinter/README.md
The circuit create command no longer lets you chose the name
of your circuit so this commit removes or replaces all mentions
of my-grid-circuit with an env variable CIRCUIT_ID.
Also updates the version of XO that is deployed.
=> Remove last mentions of my-grid-circuit

daemon/Cargo.toml, daemon/src/splinter/app_auth_handler/error.rs, daemon/src/splinter/app_auth_handler/sabre.rs, examples/splinter/README.md
Update splinter example to use sabre build pattern
- Update the splinter example to use the new Sabre transaction builder
pattern enabled by Transact, Sawtooth SDK, and Sawtooth Sabre.
- Switch to Transact's .scar loading capability, which is more robust.
- Remove the smart permission namespace from the addresses for upload
transactions, since smart permissions aren't used by Grid smart
contracts right now.
~~This PR will not build until the splinter crate is updated to include the changes in https://github.com/Cargill/splinter/pull/522~~
=> Sabre transaction building updates

grid-ui/docker/docker-compose.yaml, grid-ui/sapling-dev-server/Dockerfile, grid-ui/sapling-dev-server/configSaplings, grid-ui/saplings/register-login/.eslintrc, grid-ui/saplings/register-login/.prettierrc, grid-ui/saplings/register-login/jest.config.js, grid-ui/saplings/register-login/package.json, grid-ui/saplings/register-login/src/index.ts, grid-ui/saplings/register-login/src/register-login.html, grid-ui/saplings/register-login/tsconfig.json, grid-ui/saplings/register-login/types/index.d.ts, grid-ui/saplings/register-login/webpack.config.js, grid-ui/src/theme/colors.scss
Adds a config sapling for logging in/registering in the Grid UI.
To test, run the following commands from the Grid repo:
1. `$ export 'CARGO_ARGS=-- --features experimental'`
2. `$ docker-compose -f grid-ui/docker/docker-compose.yaml up --build`
The UI is available on localhost:3030. The log in/register page should be visible. Try registering as a new user. Once you are logged in, the main Grid UI view will load. You have to clear the session storage to log back out (log out functionality will be in the profile sapling).
=> Implement log in/register sapling

.dockerignore
This will stop any built dependencies from being copied to a docker
container. This is good because we want a fresh rebuild of our
dependencies when running in a docker environment.
=> Add javascript dependencies to .dockerignore

daemon/openapi.yaml
Adds the necessary information for the products endpoints,
including /products and /products/{product_id}, as well as
the product definition to the openapi spec.
=> Document products endpoints

examples/splinter/README.md
The new circuit ID format is a string composed of two, 5
character base62 strings joined by a dash.
Example: aB3dE-7gH0j
The new service ID format is a 4 character base62 string.
=> Update circuit id and service ids for new format

daemon/openapi.yaml, daemon/src/rest_api/routes/agents.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/rest_api/routes/organizations.rs, daemon/src/rest_api/routes/products.rs, daemon/src/rest_api/routes/records.rs, daemon/src/rest_api/routes/schemas.rs
Adds an optional service id to all the rest api response objects. Also adds a check for this in the existing tests and adds documentation to the api spec.
=> Add service_id to rest api response objects

examples/splinter/docker-compose.yaml, grid-ui/Dockerfile, grid-ui/configs/apache/httpd.conf, grid-ui/docker/docker-compose.yaml
This allows us to test the Grid UI against the network defined in the splinter example docker-compose file.
To test: 
1. Run the splinter example as described in https://github.com/hyperledger/grid/blob/master/examples/splinter/README.md
2. Navigate to the Grid UIs, (localhost:3030, localhost:3031, localhost:3032) and register as normal. Navigate to different saplings. Ensure docker-compose logs show the correct services being called and no errors are present.
=> Add Grid UI to splinter example docker network

grid-ui/saplings/product/package.json, grid-ui/saplings/product/src/App.js, grid-ui/saplings/product/src/App.scss, grid-ui/saplings/product/src/components/ProductCard.js, grid-ui/saplings/product/src/components/ProductCard.scss, grid-ui/saplings/product/src/components/ProductInfo.js, grid-ui/saplings/product/src/components/ProductInfo.scss, grid-ui/saplings/product/src/components/ProductProperty.js, grid-ui/saplings/product/src/components/ProductProperty.scss, grid-ui/saplings/product/src/components/ProductsTable.js, grid-ui/saplings/product/src/data/property-parsing.js, grid-ui/saplings/product/src/test/mock-products.js, grid-ui/src/theme/typography.scss
Adds a product info view to the Product sapling. This view is accessible by clicking any of the product cards.
To test, run the following commands from the Grid repo:
`$ export 'CARGO_ARGS=-- --features experimental'`
`$ docker-compose -f grid-ui/docker/docker-compose.yaml up --build`
The UI is available on localhost:3030. The log in/register page should be visible. Try registering as a new user. Once you are logged in, the main Grid UI view will load.
Click the link to the product sapling on the nav bar. The UI should display several mock products. To access the product info view, click any of the product cards.
=> Add product info view

examples/splinter/README.md
Updates the `circuit create` command to `circuit propose` in the
Grid-on-Splinter documentation, since this has been changed in the
Splinter CLI.
This PR should not be merged until the corresponding change in splinter has been merged: https://github.com/Cargill/splinter/pull/609
=> Update `circuit create` to `circuit propose`

grid-ui/.prettierignore, grid-ui/saplings/product/.eslintrc, grid-ui/saplings/product/package.json, grid-ui/saplings/product/src/App.js, grid-ui/saplings/product/src/App.scss, grid-ui/saplings/product/src/components/AddProductForm.js, grid-ui/saplings/product/src/components/Chips.js, grid-ui/saplings/product/src/components/Chips.scss, grid-ui/saplings/product/src/components/FilterBar.scss, grid-ui/saplings/product/src/components/Input.js, grid-ui/saplings/product/src/components/Input.scss, grid-ui/saplings/product/src/components/MultiSelect.js, grid-ui/saplings/product/src/components/MultiSelect.scss, grid-ui/saplings/product/src/components/MultiStepForm.js, grid-ui/saplings/product/src/components/MultiStepForm.scss, grid-ui/saplings/product/src/components/ProductCard.scss, grid-ui/saplings/product/src/components/ProductsTable.js, grid-ui/saplings/product/src/components/forms.scss
This adds the view for the form to add products in the Product sapling for a selected group of services. It is not currently hooked up to gridd. This PR also includes several components and config updates required for building this form.
* Run `export 'CARGO_ARGS=-- --features experimental'` from the Grid directory
* Run `docker-compose -f grid-ui/docker/docker-compose.yaml build gridd grid-db splinter-db splinterd`
* Run `docker-compose -f grid-ui/docker/docker-compose.yaml up gridd grid-db splinter-db splinterd`
* Navigate to the `grid/grid-ui` directory
* Run `npm install`
* Navigate to any of the sapling directories that are required for testing, in this case `grid/grid-ui/saplings/product`, and run `npm install && npm run deploy` in them.
* Navigate back to the `grid/grid-ui` …
=> Add view for the AddProductForm

grid-ui/sapling-dev-server/userSaplings, grid-ui/saplings/product/package.json, grid-ui/saplings/product/product_logo.svg
This replaces the placeholder with an unofficial logo for Grid Product.
=> Add product logo

sdk/Cargo.toml, sdk/build.rs
protoc-rust::run is deprecated in 2.14. This commit updates
the build.rs files to use protoc-rust::Codegen instead.
The version requirement for protoc-rust has also been raised
from 2 to 2.14.
=> Update protoc-rust to version 2.14

examples/splinter/README.md, examples/splinter/configs/nodes.yaml
Update the Grid on Splinter readme and configuration for
the change introduced in Cargill/splinter@a3ce928
This is being changed for consistency. For example when
we have ws:// and wss:// it will match tcp:// and tcps://.
The old prefix, tls://, is still supported but is considered
deprecated.
=> Update protocol prefix for TLS transport to tcps://

docker-compose-splinter.yaml, examples/splinter/docker-compose.yaml, grid-ui/docker/docker-compose.yaml
Upgrades Grid to work with the new version of splinterd
after this change https://github.com/Cargill/splinter/pull/711
This should be merged after https://github.com/Cargill/splinter/pull/711.
=> Update Grid for the removal of --transport in splinterd

daemon/Cargo.toml, daemon/migrations/2020-04-17-190646_multiple_endpoints/down.sql, daemon/migrations/2020-04-17-190646_multiple_endpoints/up.sql, daemon/src/database/models.rs, daemon/src/database/schema.rs, examples/splinter/README.md, examples/splinter/configs/nodes.yaml
Updates Grid to reflect the change in splinter that makes node endpoints
plural. This includes updating the node registry file and adding a
database migration to update the column.
=> Reflect node endpoints change in splinter

grid-ui/saplings/product/src/App.js, grid-ui/saplings/product/src/components/AddProductForm.js, grid-ui/saplings/product/src/components/Chips.scss, grid-ui/saplings/product/src/components/EditProductForm.js, grid-ui/saplings/product/src/components/ProductCard.js, grid-ui/saplings/product/src/components/ProductsTable.js
This adds the view for the form to Edit a Grid Product. It is not yet hooked up the Grid daemon. This allows for a user to update a Product's master data and associated additional information, in this case, the product photo.
* Run `export 'CARGO_ARGS=-- --features experimental'` from the Grid directory
* Run `docker-compose -f grid-ui/docker/docker-compose.yaml build gridd grid-db splinter-db splinterd`
* Run `docker-compose -f grid-ui/docker/docker-compose.yaml up gridd grid-db splinter-db splinterd`
* Navigate to the `grid/grid-ui` directory
* Run `npm install`
* Navigate to any of the sapling directories that are required for testing, in this case `grid/grid-ui/saplings/product`, and run `npm install && npm run deploy` in them.
* Navigate back to the `grid/grid-ui` directory and run …
=> Add form to Edit a Product

grid-ui/saplings/product/src/components/ProductInfo.js, grid-ui/saplings/product/src/components/PropertyDetailsModal.js, grid-ui/saplings/product/src/components/PropertyDetailsModal.scss, grid-ui/saplings/product/src/data/property-parsing.js, grid-ui/saplings/product/src/state/service-context.js
Add a modal showing the full view of product properties when the `VIEW FULL PRODUCT INFO` button is clicked.
To support this feature, the service state was added to sessionStorage. This means that you won't have to re-select a service when you refresh the page from a product info view.
=> Add properties modal

docker-compose-splinter.yaml, examples/splinter/docker-compose.yaml, grid-ui/docker/docker-compose.yaml
Update splinter tls options to match new splinterd
Update docker-compose for the changes in
Cargill/splinter#727
This should be merged after Cargill/splinter#727
=> Update for new version of splinterd which adds "tls-" prefix

daemon/src/database/helpers/agents.rs, daemon/src/database/helpers/grid_schemas.rs, daemon/src/database/helpers/organizations.rs, daemon/src/database/helpers/products.rs, daemon/src/database/helpers/track_and_trace.rs, daemon/src/database/models.rs
This PR updates the Grid DB insert operations to account for service_id's on the items being added. Previously, some items could be overwritten if they were added to the database again but for a different service_id.
=> Update DB insert operations

grid-ui/saplings/product/src/App.js, grid-ui/saplings/product/src/components/DeleteProductForm.js, grid-ui/saplings/product/src/components/DeleteProductForm.scss, grid-ui/saplings/product/src/components/ProductCard.js, grid-ui/saplings/product/src/components/ProductCard.scss, grid-ui/saplings/product/src/components/ProductsTable.js, grid-ui/saplings/product/src/components/SimpleForm.js, grid-ui/saplings/product/src/components/SimpleForm.scss
This adds the view for the form to delete a Grid Product. It is not yet hooked up the Grid daemon. This allows for a user to delete a Product after confirming by re-entering the product's GTIN.
* Run `export 'CARGO_ARGS=-- --features experimental'` from the Grid directory
* Run `docker-compose -f grid-ui/docker/docker-compose.yaml build gridd grid-db splinter-db splinterd`
* Run `docker-compose -f grid-ui/docker/docker-compose.yaml up gridd grid-db splinter-db splinterd`
* Navigate to the `grid/grid-ui` directory
* Run `npm install`
* Navigate to any of the sapling directories that are required for testing, in this case `grid/grid-ui/saplings/product`, and run `npm install && npm run deploy` in them.
* Navigate back to the `grid/grid-ui` directory and run `npm run start`
* Once the app …
=> Add delete product form

examples/splinter/docker-compose.yaml, grid-ui/docker/docker-compose.yaml
Even numbered Splinter branches are considered "stable" so Grid should
use these instead of master.
=> Switch compose files to use Splinter 0.4 images

examples/splinter/README.md, examples/splinter/docker-compose.yaml, grid-ui/docker/docker-compose.yaml
Grid no longer require the use of experimental Splinter images.
The Grid on Splinter examples has been updated to use 0.4 images.
Also updates the README to not mention experimental.
Also updates the grid-ui docker-compose.
=> Update docker-compose files to use stable 0.4 Splinter images

cli/src/actions/keygen.rs, cli/src/key.rs
Fixes instances where `.and_then(|x| Ok(x))` is used as it can be
more succinctly written as `.map(|x| x)`.
=> Fix clippy error 'bind_instead_of_map'

daemon/src/event/mod.rs, daemon/src/sawtooth/event.rs
This change allows the grid daemon to safely handle the ping request, and any future, unrecognized messages.  It helps gridd support sawtooth 1.2.
=> Handle PING_REQUEST

ci/grid-dev, ci/grid-dev.yaml
This adds the libsqlite3-dev dependency to the grid-dev image and increments the version number from 2 to 3. This is done in support of refactoring the Grid database functionality.
=> Add sqlite dependency

sdk/src/grid_db/mod.rs, sdk/src/grid_db/organizations/mod.rs, sdk/src/grid_db/organizations/store/diesel/mod.rs, sdk/src/grid_db/organizations/store/diesel/models.rs, sdk/src/grid_db/organizations/store/diesel/operations/add_organizations.rs, sdk/src/grid_db/organizations/store/diesel/operations/fetch_organization.rs, sdk/src/grid_db/organizations/store/diesel/operations/list_organizations.rs, sdk/src/grid_db/organizations/store/diesel/operations/mod.rs, sdk/src/grid_db/organizations/store/diesel/schema.rs, sdk/src/grid_db/organizations/store/error.rs, sdk/src/grid_db/organizations/store/memory.rs, sdk/src/grid_db/organizations/store/mod.rs, sdk/src/hex.rs, sdk/src/lib.rs, sdk/src/store/memory.rs, sdk/src/store/mod.rs, sdk/src/store/postgres.rs, sdk/src/store/sqlite.rs
This adds the postgres, sqlite, and in-memory implementations of the organization store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.
=> Add organization store implementation

sdk/Cargo.toml, sdk/src/grid_db/locations/mod.rs, sdk/src/grid_db/locations/store/diesel/mod.rs, sdk/src/grid_db/locations/store/diesel/models.rs, sdk/src/grid_db/locations/store/diesel/operations/add_location.rs, sdk/src/grid_db/locations/store/diesel/operations/fetch_location.rs, sdk/src/grid_db/locations/store/diesel/operations/list_locations.rs, sdk/src/grid_db/locations/store/diesel/operations/mod.rs, sdk/src/grid_db/locations/store/diesel/operations/update_location.rs, sdk/src/grid_db/locations/store/diesel/schema.rs, sdk/src/grid_db/locations/store/error.rs, sdk/src/grid_db/locations/store/mod.rs, sdk/src/grid_db/mod.rs, sdk/src/store/memory.rs, sdk/src/store/mod.rs, sdk/src/store/postgres.rs, sdk/src/store/sqlite.rs
This adds the postgres and sqlite store implementations and stubs the in-memory implementation (to make it compile) for the location store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.
=> Add location store

sdk/src/grid_db/agents/mod.rs, sdk/src/grid_db/agents/store/diesel/mod.rs, sdk/src/grid_db/agents/store/diesel/models.rs, sdk/src/grid_db/agents/store/diesel/operations/add_agent.rs, sdk/src/grid_db/agents/store/diesel/operations/fetch_agent.rs, sdk/src/grid_db/agents/store/diesel/operations/list_agents.rs, sdk/src/grid_db/agents/store/diesel/operations/mod.rs, sdk/src/grid_db/agents/store/diesel/operations/update_agent.rs, sdk/src/grid_db/agents/store/diesel/schema.rs, sdk/src/grid_db/agents/store/error.rs, sdk/src/grid_db/agents/store/mod.rs, sdk/src/grid_db/mod.rs, sdk/src/store/memory.rs, sdk/src/store/mod.rs, sdk/src/store/postgres.rs, sdk/src/store/sqlite.rs
This adds the postgres and sqlite store implementations and stubs the in-memory implementation (to make it compile) for the agent store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.
=> Add agent store

sdk/src/grid_db/mod.rs, sdk/src/grid_db/track_and_trace/mod.rs, sdk/src/grid_db/track_and_trace/store/diesel/mod.rs, sdk/src/grid_db/track_and_trace/store/diesel/models.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/add_associated_agents.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/add_properties.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/add_proposals.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/add_records.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/add_reported_values.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/add_reporters.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/fetch_property_with_data_type.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/fetch_record.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/fetch_reported_value_reporter_to_agent_metadata.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/list_associated_agents.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/list_properties_with_data_type.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/list_proposals.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/list_records.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/list_reported_value_reporter_to_agent_metadata.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/list_reporters.rs, sdk/src/grid_db/track_and_trace/store/diesel/operations/mod.rs, sdk/src/grid_db/track_and_trace/store/diesel/schema.rs, sdk/src/grid_db/track_and_trace/store/error.rs, sdk/src/grid_db/track_and_trace/store/mod.rs, sdk/src/store/memory.rs, sdk/src/store/mod.rs, sdk/src/store/postgres.rs, sdk/src/store/sqlite.rs
This adds the postgres and sqlite store implementations and stubs the in-memory implementation (to make it compile) for the track and trace store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.
=> Add track and Trace store

daemon/src/splinter/app_auth_handler/sabre.rs, examples/splinter/docker-compose.yaml
This PR adds the Grid Location contract to the list of contracts that is automatically deployed when setting up a new Grid circuit. Since location is a foundational capability for Grid, it should be auto deployed. I also added a `tail -f /dev/null` command to the scabbard CLI so it can be used to see what contracts are deployed.
To test:
1. Follow the Grid on Splinter README instructions up to step 10 in "Create a Circuit"
2. `$ docker-compose -f examples/splinter/docker-compose.yaml exec scabbard-cli-alpha bash`
3. `# scabbard contract list --service-id <service-id> --url http://splinterd-alpha:8085`
Ensure that the CLI command in step 3 shows the location contract
=> Add location deployment to app auth handler

sdk/src/grid_db/commits/store/diesel/mod.rs, sdk/src/grid_db/commits/store/error.rs, sdk/src/grid_db/commits/store/mod.rs, sdk/src/grid_db/organizations/store/diesel/mod.rs, sdk/src/grid_db/organizations/store/error.rs, sdk/src/grid_db/organizations/store/mod.rs
Move several `impl` statements that use the diesel feature flag in the organization and commit modules into their respective diesel modules.
=> Move organization and commit store implementations into diesel modules

daemon/packaging/ubuntu/postinst, examples/splinter/docker-compose.yaml
Adds a shared-volume to the Splinter example's docker-compose file
amongst the gridd and splinterd containers to store any circuit template
files, so both the Grid daemon and Splinter daemon have access to these
files.
=> Add shared circuit-template volume

daemon/openapi.yaml
This updates the `openapi.yaml` file for gridd. The term "Sawtooth
Validator" is replaced with the DL-agnostic term "Transaction" in the
tags since Grid is no longer constrained to only using Sawtooth. This
also updates the summaries for the `POST /batches` and `GET
/batch_statuses` endpoints to both be imperative and reflect the
aforementioned terminology change.
=> Update "Sawtooth Validator" terminology

daemon/man/gridd.1.md
This adds a man page for the gridd command.
=> Add gridd man page

cli/src/main.rs
This adds the global Grid CLI options to the help output for the
Grid subcommands.
=> Add grid options to subcommand help

.gitignore, ui/Dockerfile, ui/protos/location_payload.proto, ui/protos/location_state.proto, ui/protos/pike_payload.proto, ui/protos/pike_state.proto, ui/protos/product_payload.proto, ui/protos/product_state.proto, ui/protos/schema_payload.proto, ui/protos/schema_state.proto, ui/protos/track_and_trace_payload.proto, ui/protos/track_and_trace_state.proto, ui/saplings/product/package.json, ui/saplings/product/test/Dockerfile
The protos have to be added to the ui directory since it is used as the
context directory for Grid UI builds. This also fixes the protogen
script to use these files.
This commit also fixes the gitignore since it was ignoring the artifact
of the generate proto files script twice.
=> Add protos to UI directory and add to build

cli/man/grid-product-create.md, cli/man/grid-product-delete.md, cli/man/grid-product-list.md, cli/man/grid-product-show.md, cli/man/grid-product-update.md, cli/man/grid-product.md, cli/man/grid.1.md
This adds man pages for the grid product subcommands. The subcommands
documented are: `grid product create`, `grid product delete`, `grid
product list`, `grid product show`, and `grid product update`.
=> Add man pages for grid product commands

contracts/product/src/addressing.rs, ui/saplings/product/src/App.js, ui/saplings/product/src/api/transactions.js, ui/saplings/product/src/components/ProductCard.js
This adds support for GTIN-8, GTIN-13, and GTIN-14. Previously, only
GTIN-12 was supported and other GTIN lengths would cause errors to be
thrown.
=> Fix GTIN length bug

contracts/product/src/handler.rs
Removing an incorrect check for an empty org metadata key that caused the gs1
prefix validation step during product creation to be skipped if the gs1 prefix
metadata was present. If the key was present, the smart contract would
not check if that prefix was present in the product ID.
=> Check gs1 prefix if prefix is present

cli/src/actions/admin.rs, cli/src/actions/keygen.rs
This removes the quotation marks from around the file path output in the
`grid keygen` and `grid admin keygen` commands. This is a more standard
output format.
=> Remove quotes from keygen output

cli/src/actions/products.rs
This updates the `grid product list` command's output to display a
subset of the product data in a table format. This improves readability
and enables the use of other command line utilities for searching and
filtering results.
=> Update product list output

contracts/location/src/handler.rs
The check for the gs1 company prefix in the location smart contract
should check if the prefix is contained within the location_id, not that
it is equal to the location_id.
=> Check for correct gs1_prefix in location smart contract

ui/grid-ui/package.json, ui/saplings/product/package.json
There appears to have been a breaking change in a minor ESLing version.
Updating this dependency should fix the issue.
https://github.com/airbnb/javascript/issues/2331
=> Update eslint import plugin dependency

cli/src/http.rs, cli/src/main.rs
Some Grid subcommands (create, update, delete) for various grid modules
didn't have any output when entered. This adds an output line that tells
the user that the appropriate transaction has been submitted.
=> Add output to create, update, delete subcommands

cli/src/actions/locations.rs
This updates the `grid location list` command's output to display a
subset of the location data in a table format. This improves readability
and enables the use of other command line utilities for searching and
filtering results.
=> Update location list output

daemon/openapi.yaml
This commit is a heavy edit of the Grid REST API specification. The
specification was outdated and had many structural and consistency
issues. Due to the scope of changes, the spec was rewritten from scratch
but pulls in some models and structure from the previous version as
appropriate.
In summary, the following changes were made:
- Updated the info object
- Added documentation and links to transaction routes
- Standardized summary and description format
- Removed inaccurate error types
- Organized schemas and paths by feature
=> Overhaul Grid REST API spec

cli/src/actions/schemas.rs
This updates the `grid schema list` command's output to display a
subset of the schema data in a table format. This improves readability
and enables the use of other command line utilities for searching and
filtering results.
=> Update schema list output

cli/src/actions/database.rs
The command `grid database migrate` will now check if scheme is present
when it is used with the database-url option. Currently the only scheme
that is supported is postgres.
=> Have database migrate command check for a scheme

cli/src/main.rs
Fixes small bug that was causing the location_id being passed to the
show command to not be read.
=> Have location show command correctly consume location_id

bin/run_integration_tests, daemon/Cargo.toml, daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, daemon/src/main.rs, daemon/src/rest_api/mod.rs, daemon/src/rest_api/routes/mod.rs, daemon/src/sawtooth/event.rs, daemon/src/splinter/app_auth_handler/sabre.rs, daemon/test/docker-compose.yaml, integration/docker-compose.yaml
The grid daemon's feature set is now guarded by the following features:
- pike
- product
- schema
- location
- track-and-trace
When these features are enabled the corresponding rest api routes will
be active, the app auth handler will upload corresponding smart
contracts to created circuits and the database handler will listen for
corresponding events. Pike, product, schema, and location are considered
stable features and will be included by default or if the daemon is
compiled with the stabled flag. Track and trace is considered
experimental and will only be included if the daemon is compiled with
the experimental flag.
When only location and product are enabled, pike and schema will be
included as well because those features are  required to properly use
product and location. Similarly, …
=> Grid daemon feature guards

cli/src/main.rs, cli/tests/product.rs
This moves the key and service-id args one level deeper. These args were previously global to all grid commands but were not relevant to keygen and admin subcommands. Now these args must be specified after the grid subcommand rather than the grid command and are only available on relevant subcommands. This also updates the Grid-on-Splinter example README to reflect these changes.
=> Fix global CLI options

daemon/src/splinter/app_auth_handler/sabre.rs
Removes the hard-coded consts for version numbers and instead uses the
cargo env var to get the actual version number of the package. This
number lines up with the number that the docker-compose file passes to
the contract builders.
=> Pass cargo package version to contract constructor

cli/Cargo.toml, cli/src/main.rs, daemon/test/docker-compose.yaml, integration/docker-compose.yaml
The grid cli feature set is now guarded by the following features:
- pike
- product
- schema
- location
When these features are enabled the corresponding set of cli commands
will be enabled. Pike, product, schema, and location are considered
stable features and will be included if the cli is compiled with the
stable flag.
When only location and product are enabled, pike and schema will be
included as well because those features are required to properly use
product and location. Similarly, if schema is enabled pike will also be
included for the same reason.
=> Add feature guards to CLI

contracts/pike/packaging/scar/manifest.yaml, contracts/pike/src/handler.rs, contracts/product/packaging/scar/manifest.yaml, contracts/product/product.yaml, contracts/product/src/handler.rs, contracts/schema/packaging/scar/manifest.yaml, contracts/schema/schema.yaml, contracts/schema/src/handler.rs, contracts/track_and_trace/packaging/scar/manifest.yaml, contracts/track_and_trace/src/handler.rs, contracts/track_and_trace/track_and_trace.yaml
Changing this to a non-semver value makes it more clear than this value
specifies the protocol version and is separate from the repository's
packaging version.
=> Standardize protocol version in smart contracts

daemon/Cargo.toml, sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/migrations/diesel/postgres/mod.rs, sdk/src/migrations/diesel/sqlite/mod.rs, sdk/src/store/memory.rs, sdk/src/store/mod.rs, sdk/src/store/postgres.rs, sdk/src/store/sqlite.rs
Adds the following features to the grid sdk
- pike
- product
- schema
- location
- track-and-trace
Pike, product, schema, and location are considered
stable features and will be included if the sdk is compiled with the stabled
flag. Track and trace is considered experimental and will only be included if
the sdk is compiled with
the experimental flag.
When only location and product are enabled, pike and schema will be
included as well because those features are  required to properly use
product and location. Similarly, if schema is enabled pike will also be
included for the same reason.
=> SDK Feature Guards

cli/src/main.rs
This adds the option to use the long `--key` form to pass the key
argument to grid commands. Previously, only the short `-k` form was
accepted which didn't align with the other arguments.
=> Add `--key` option to grid command arg

cli/Cargo.toml, cli/src/actions/keygen.rs, cli/src/actions/mod.rs, cli/src/main.rs
This updates the `grid keygen` command to work similarly to its Splinter
counterpart. This change adds a `--system` argument that causes the
action to generate the keys in a system defined directory.
=> Update keygen command

cli/src/transaction.rs, cli/tests/product.rs, cli/tests/products/create_product.yaml, contracts/pike/pike.yaml
These version numbers were changed to be integers so the Pike version
should just be "1".
=> Fix Pike version in Grid CLI

cli/Cargo.toml, contracts/location/Cargo.toml, contracts/pike/Cargo.toml, contracts/pike/src/handler.rs, contracts/product/Cargo.toml, contracts/track_and_trace/Cargo.toml, daemon/Cargo.toml, daemon/src/rest_api/routes/batches.rs, daemon/src/sawtooth/batch_submitter.rs, daemon/src/sawtooth/event.rs, sdk/Cargo.toml, sdk/src/protocol/location/payload.rs, sdk/src/protocol/location/state.rs, sdk/src/protocol/pike/payload.rs, sdk/src/protocol/pike/state.rs, sdk/src/protocol/product/payload.rs, sdk/src/protocol/product/state.rs, sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs, sdk/src/protocol/track_and_trace/payload.rs, sdk/src/protocol/track_and_trace/state.rs
protobuf::parse_from_bytes has been deprecated.
=> Use Message::parse_from_bytes instead of protobuf::parse_from_bytes

daemon/Cargo.toml, sdk/Cargo.toml
These need to be stable in 0.1, but they will still go through the stabilization process for 0.2
=> Stabilize database and splinter-support in 0.1

daemon/src/sawtooth/event.rs, ui/grid-ui/package.json
1. The canopyjs branch changed from master to main so I updated it in the grid UI package.json
2. Strange issue with features. The `GRID_NAMESPACE` const was removed from the event.rs module in a previous commit and the build passed, but builds after this broke due to it not being defined. I changed it to pull in the proper consts from the relevant addressing modules and guarding it by feature. Not entirely sure why it passed to begin with.
=> Fix builds

contracts/location/src/handler.rs, contracts/location/src/state.rs, contracts/pike/Cargo.toml, contracts/pike/src/handler.rs, contracts/product/src/addressing.rs, contracts/product/src/handler.rs, contracts/product/src/state.rs, contracts/schema/src/handler.rs, sdk/src/permissions.rs
Updates the has_permission check to include `record_owner`, which is the Pike ID of the org that owns the record that we are checking permissions for.  This also adds a check to make sure the agent actually belongs to that org and removes it from the smart contract. This is part of an effort to move common code from the contracts to the SDK.
=> Include record owner in has_permission check

ui/Dockerfile
Update the docker-compose file in examples/splinter to clone the 0-1 splinter-ui branch to ensure grid-ui has a functioning profile page.
=> Update splinter-ui branch used in docker-compose

cli/Cargo.toml, daemon/Cargo.toml, sdk/Cargo.toml
This removes the unnecessary `grid_db` and `database` features from the
SDK. These features just wrapped other features but weren't actually
used to guard any code. The wrapped features that actually guard code
are now just moved up one level.
=> Remove unnecessary SDK features

daemon/src/event/mod.rs
Removes the `Result` return type of this function, as it is unnecessary
and causes a clippy lint error.
=> Remove unnesecessary result in `handle_message`

daemon/src/event/mod.rs
Removes the `Result` return type of this function, as it is unnecessary
and causes a clippy lint error.
=> Remove unnesecessary result in `handle_message` for 0-1 Grid branch

cli/src/actions/roles.rs, cli/src/main.rs, contracts/pike/src/handler.rs, daemon/src/event/db_handler.rs, daemon/src/rest_api/routes/mod.rs, sdk/src/migrations/diesel/postgres/migrations/2021-02-05-160000_pike_2_tables/down.sql, sdk/src/migrations/diesel/postgres/migrations/2021-02-05-160000_pike_2_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-02-05-160000_pike_2_tables/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-02-05-160000_pike_2_tables/up.sql, sdk/src/pike/store/diesel/mod.rs, sdk/src/pike/store/diesel/models.rs, sdk/src/pike/store/diesel/operations/add_role.rs, sdk/src/pike/store/diesel/operations/delete_role.rs, sdk/src/pike/store/diesel/operations/mod.rs, sdk/src/pike/store/diesel/schema.rs, sdk/src/pike/store/mod.rs
This adds the functionality to delete roles. This includes updating the DB record to set the `end_commit_num` SCD column to the current commit number, essentially making that record no longer current.
=> Add roles delete functionality

daemon/src/rest_api/routes/mod.rs, sdk/src/migrations/diesel/sqlite/migrations/2021-02-05-160000_pike_2_tables/up.sql, sdk/src/pike/store/diesel/mod.rs, sdk/src/pike/store/diesel/models.rs, sdk/src/pike/store/diesel/operations/add_organization.rs
This fixes some of the Rest API tests that were breaking due to the updates to locations storage in Pike 2. This also updates the add_organization database operation to properly store location association records.
=> Fix rest api tests

cli/schemas/GridTradeItems.xsd
This file can be used to validate product definitions in XML format. It
references the GDSN TradeItem schema.
=> Add GridTradeItems.xsd for XML schema validation

cli/src/main.rs, cli/tests/product.rs, contracts/location/src/handler.rs, contracts/pike/src/handler.rs, contracts/product/src/handler.rs, daemon/src/event/db_handler.rs, sdk/protos/pike_state.proto, sdk/src/pike/addressing.rs, sdk/src/pike/store/diesel/mod.rs, sdk/src/pike/store/diesel/models.rs, sdk/src/pike/store/diesel/operations/add_organization.rs, sdk/src/protocol/pike/state.rs
This adds alternate ID support to the Pike, Product, and Location smart contracts. This replaces the functionality of the special case of organization metadata that was being checked for GS1 company prefixes with a more flexible field on the Organization object. This field can be used for any number of alternate identifiers for an organization.
- Follow grid walkthrough directions to set up a circuit
- create an organization and add the `gs1_company_prefixes` ID with the `--alternate-ids` flag
- create a role to create schemas, products, and locations
- Add the role to the agent
- create schemas for products and locations
- create a product and create a location
=> Add alternate ID support

daemon/test/docker-compose.yaml
Adds sqlite tests to integration docker compose and chains together
commands using "&". Chaining commands together is necessary because
without chaining, the Jenkins build will pass as long as the last set of
tests pass, regardless as to whether or not the other test suits
failed leading to Jenkins falsely reporting that all the tests passeed.
=> Add sqlite tests to integration test and add chain commands

.dockerignore, examples/griddle/docker-compose-dockerhub.yaml, examples/griddle/docker-compose.yaml, griddle/Dockerfile, load-balancer/Dockerfile, load-balancer/nginx.conf
1) Run the griddle docker compose file
```
docker-compose -f examples/griddle/docker-compose.yaml up --build
```
2) Send requests to either the alpha griddle network via port 9000 or the beta griddle network via port 9001
```
POST http://localhost:9000/submit
{}
```
3) Observer that traffic is being routed to different griddle instances via docker's terminal output
=> Griddle docker compose files

sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/purchase_order/mod.rs
This change adds the purchase_order module to the SDK.  It is initialized with an empty mod.rs.
This module is guarded by the feature "purchase-order".
=> Add purchase_order SDK module

sdk/src/purchase_order/addressing.rs, sdk/src/purchase_order/mod.rs
This change adds the address prefixes and functions for computing the complete merkle address for purchase orders and alternate ids.
=> Add purchase order address consts & functions

sdk/src/purchase_order/addressing.rs
This change renames the uid to uuid to be more explicit about the meaning of an ID of a PO.
=> Rename uid to uuid in address computation

Cargo.toml, ci/grid-dev, ci/grid-dev.yaml, cli/Dockerfile, contracts/location/Dockerfile, contracts/pike/Dockerfile, contracts/product/Dockerfile, contracts/purchase_order/Cargo.toml, contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/main.rs, contracts/purchase_order/src/state.rs, contracts/schema/Dockerfile, contracts/track_and_trace/Dockerfile, daemon/Dockerfile, griddle/Dockerfile
Includes the ability to build as a wasm smart contract
but the handling of the transaction is left unimplemented.
=> Add skeleton for Grid Purchase Order smart contract

sdk/src/migrations/diesel/postgres/migrations/2021-03-24-130200_purchase_order_tables/down.sql, sdk/src/migrations/diesel/postgres/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-03-24-130200_purchase_order_tables/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-03-24-130200_purchase_order_tables/up.sql
This adds the initial postgres and sqlite migrations for the purchase
order module.
=> Add initial PO migrations

cli/Cargo.toml, cli/src/main.rs
This PR: 
- Adds the experimental `purchase-order` feature to the grid CLI
- Adds an outline for the purchase order CLI subcommands, unimplemented currently
=> Add CLI subcommands

README.md, cli/Dockerfile, daemon/Dockerfile, griddle/Dockerfile
The cargo deb subcommand is not fully compatible with workspaces, so
using it for deb package creation only provides us with more consistent
results.
=> Compile crates with cargo build instead of cargo deb

sdk/Cargo.toml, sdk/src/client/mod.rs, sdk/src/lib.rs
Create a `Client` trait in a `client` module in sdk/src/ that can be implemented with different backends. The initial implementation of this client trait contains method definitions for purchase order related interactions. This client is guarded by the `client` experimental feature.
=> Create `Client` trait

sdk/src/purchase_order/store/diesel/models.rs, sdk/src/purchase_order/store/diesel/schema.rs
This adds the first draft of the purchase order database table schemas and corresponding Rust implementations.
=> Add purchase order DB schema and models

sdk/src/purchase_order/mod.rs, sdk/src/purchase_order/store/error.rs, sdk/src/purchase_order/store/mod.rs
This adds the PurchaseOrderStore trait and associated structs. This includes the native models of PurchaseOrder and PurchaseOrderAlternateID as well as the PurchaseOrderStoreError type.
=> Add purchase order store trait and structs

sdk/Cargo.toml, sdk/src/client/mod.rs, sdk/src/client/reqwest.rs
Update the Client trait to have `add_purchase_order_version` `update_purchase_order_version` and `add_purchase_order_revision` method definitions.
Add an outline for the reqwest based implementation of the `Client` trait. All methods are unimplemented. The `reqwest` module is guarded by the experimental feature `client-reqwest`
Fix the `PurchaseOrderRevision` and `PurchaseOrderVersion` structs to match protos. Update the `PurchaseOrderRevision` struct to have `revision_id` instead of `revision_number` and update the `PurchaseOrderVersion` to have `current_revision_id` instead of `current_revision_number`
=> Add reqwest stub

sdk/src/client/mod.rs, sdk/src/client/reqwest.rs
- Replace the existing `add` and `update` methods in the `Client` trait with a `post_batches` method.
- Update the reqwest implementation to match the `Client` trait by removing `add`/`update` methods and add the new `post_batches` method.
=> Update Client trait and reqwest stub

cli/src/main.rs
This change adds the Clap code to add the `po` subcommand to the Grid
CLI. This initial subcommand includes the `list`, `show`, `create`, and
`update` subcommands.
=> Add clap code for `grid po` subcommand

cli/man/grid-po-list.1.md, cli/man/grid-po.1.md, cli/man/grid.1.md
This change adds the man page for listing purchase orders.  It also adds the base man page for `grid po`.
=> Add po list command man page

cli/src/main.rs
This change updates the Grid CLI's `po update` subcommand's `rm_id`
argument's help section to clarify this argument takes the full
alternate id, meaning `<alternate_id_type>:<alternate_id>` rather than
just the alternate id's type.
This change also updates the `value_name` of the `rm_id` argument from
`alternate_id_type` to `alternate_id`, to clarify what value is expected
for this argument.
=> Update `po update` subcommand `rm_id` arg

sdk/src/purchase_order/mod.rs, sdk/src/purchase_order/store/diesel/mod.rs, sdk/src/purchase_order/store/diesel/models.rs, sdk/src/purchase_order/store/diesel/operations/add_alternate_id.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/fetch_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/list_alternate_ids_for_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_orders.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs, sdk/src/purchase_order/store/mod.rs
This adds the add_purchase_order, fetch_purchase_order, and list_purchase_orders_for_organization db operations. This also implements the conversion methods to and from the database models. Additionally, stubs are added for the unimplemented operations.
=> Add operations and stubs

cli/src/main.rs
This change adds the `version` subcommand to the Grid CLI's `po`
subcommand.
=> Add `po version` subcommand

cli/src/actions/roles.rs, cli/src/main.rs
This adds a command to the Grid CLI to list roles for a given org ID.
This command lists basic information about the roles. More detailed info
can be fetched with the `grid role show` command.
=> Add Roles list CLI command

cli/src/main.rs
This updates the `--key_dir` keygen argument to replace the underscore
with a dash. This brings the arg more in line with others.
=> Update key dir cli arg

cli/Cargo.toml, cli/Dockerfile, cli/schemas/xsd_schema.yaml, cli/src/actions/products.rs, cli/src/error.rs, cli/src/main.rs, daemon/Dockerfile, docker/lint, docker/tests, sdk/Cargo.toml, sdk/src/error/invalid_argument.rs, sdk/src/error/mod.rs, sdk/src/products/gdsn/error.rs, sdk/src/products/gdsn/mod.rs, sdk/src/products/mod.rs, sdk/src/protocol/errors.rs
This is the first PR to implement XML support for product. The code was getting a bit complex so I am submitting this one first to keep it incremental. Remaining tasks include:
- Implementing update
- Validation
- Fetching alternate ID to fill in the owner
To test: 
1. start up the `examples/splinter/docker-compose.yaml` network and create a Grid circuit between alpha and beta
2. Set up agents and organizations as follows:
```
grid keygen alpha-agent
export GRID_SERVICE_ID=<circuit ID>::gsAA
grid organization create crgl Cargill --metadata gs1_company_prefixes=0
grid role create crgl productowner --permissions schema::can-create-schema,product::can-create-product --active
grid agent update crgl $(cat ~/.grid/keys/alpha-agent.pub) --active --role productowner --role admin
```
3. submit a …
=> Implement create product using XML data

cli/man/grid-agent-create.1.md, cli/man/grid-agent-update.1.md, cli/man/grid-agent.1.md, cli/man/grid-organization-create.1.md, cli/man/grid-organization-update.1.md, cli/man/grid-organization.1.md, cli/man/grid-role-create.1.md, cli/man/grid-role-delete.1.md, cli/man/grid-role-list.1.md, cli/man/grid-role-show.1.md, cli/man/grid-role-update.1.md, cli/man/grid-role.1.md
This adds man pages for all the Pike 2 CLI commands. This includes
man pages pertaining to the `grid role`, `grid agent`, and `grid
organization` commands and their respective subcommands.
=> Add Pike 2 man pages

ui/grid-ui/public/index.html, ui/sapling-dev-server/userSaplings
This fixes the sidebar for the grid UI to correctly show icons for the
different saplings. This change depends on the PR to splinter-canopyjs:
https://github.com/Cargill/splinter-canopyjs/pull/21.
=> Fix UI sidebar

cli/man/grid-po-version-create.1.md, cli/man/grid-po-version-list.1.md, cli/man/grid-po-version-update.1.md, cli/man/grid-po-version.1.md
This PR adds the man pages for the following grid subcommands:
* grid po version
* grid po version create
* grid po version update
* grid po version list
=> Add grid po version man pages

cli/schemas/gdsn_3_1_schema.yaml, cli/src/actions/products.rs, cli/src/main.rs, sdk/src/products/gdsn/mod.rs
This PR is based on #640 
This PR updates the product create CLI command to take any number of occurrences of --file. The resulting payloads will have all properties specified across the files for each product ID.
For instance, you can submit an XML file with a GDSN trade item definition in one file, and then submit a yaml file with the same GTIN as the product ID to supply additional attributes.
To test:
1. start up the `examples/splinter/docker-compose.yaml` network and create a Grid circuit between alpha and beta
2. Set up agents and organizations as follows:
```
grid keygen alpha-agent
export GRID_SERVICE_ID=<circuit ID>::gsAA
grid organization create crgl Cargill --alternate-ids gs1_company_prefix:0
grid role create crgl productowner --permissions …
```
=> Implement multiple file handler for product CLI

sdk/src/purchase_order/mod.rs
This updates the DieselPurchaseOrderStore feature to be guarded by the
`diesel` feature rather than the `postgres` feature. This brings the
module in line with the other Grid data stores. This is part of stabilizing the
postgres and sqlite features.
=> Update PurchaseOrderStore feature guard

cli/src/error.rs, sdk/Cargo.toml, sdk/src/products/gdsn/mod.rs, sdk/src/products/gdsn/validate.rs
The rust-libxml bindings library did not handle validation errors properly. Instead of reporting all of the validation errors for a file, the library would return the correct number of errors but all of the error messages would be the same. This issue seems to be due to the implementation of the StructuredError handler in the rust-libxml bindings library.
This PR removes the bindings library and just implements bindings for the specific libxml2 functions needed for validation.
This PR also moves the validation step to after the XML files have been parsed so that parsing errors can be reported before validation.
Example output:
```
$ grid product create --owner crgl --file .myfiles/valid_example.xml --file .myfiles/invalid_example.xml 
Entity: line 10: Schemas validity error : Element …
```
=> Improve validation error reporting

Jenkinsfile
Cron builds running at 2am are failing regularly. Moving the build to
run earlier will either fix the problem or disprove a theory.
=> Run cron builds at 1am

docker/compose/.env, examples/sawtooth/.env, examples/splinter/.env, ui/grid-ui/docker/.env
As of version 1.28.0, Docker Compose expects .env files to reside in the same
directory as the compose files or to have their path specicified with an
additional argument to the compose command. Duplicating the .env files
whereever they're needed was deemed to be the least disruptive solution.
=> BACKPORT 0-1:  Fix Grid docker builds with Docker Compose 1.28+

daemon/openapi.yaml, daemon/src/event/db_handler.rs, daemon/src/rest_api/mod.rs, sdk/src/locations/store/diesel/mod.rs, sdk/src/locations/store/diesel/models.rs, sdk/src/locations/store/diesel/schema.rs, sdk/src/locations/store/mod.rs, sdk/src/migrations/diesel/postgres/migrations/2021-04-23-151946_add_timestamp/down.sql, sdk/src/migrations/diesel/postgres/migrations/2021-04-23-151946_add_timestamp/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-04-23-151946_add_timestamp/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-04-23-151946_add_timestamp/up.sql, sdk/src/pike/store/diesel/models.rs, sdk/src/pike/store/diesel/schema.rs, sdk/src/pike/store/mod.rs, sdk/src/products/store/diesel/mod.rs, sdk/src/products/store/diesel/models.rs, sdk/src/products/store/diesel/schema.rs, sdk/src/products/store/mod.rs, sdk/src/rest_api/resources/agents/v1/payloads.rs, sdk/src/rest_api/resources/locations/v1/payloads.rs, sdk/src/rest_api/resources/organizations/v1/payloads.rs, sdk/src/rest_api/resources/products/v1/payloads.rs, sdk/src/rest_api/resources/roles/v1/payloads.rs, sdk/src/rest_api/resources/schemas/v1/payloads.rs, sdk/src/schemas/store/diesel/mod.rs, sdk/src/schemas/store/diesel/models.rs, sdk/src/schemas/store/diesel/schema.rs, sdk/src/schemas/store/mod.rs
Adds database generated timestamp to agent, role, organization, product, location, and schema endpoints.
Example:
```
GET /agent/021bab739fce4133204c8c0bd939d48e4d32e5b29eb87ed871d2666fcd3f51bb3e
{
"public_key": "021bab739fce4133204c8c0bd939d48e4d32e5b29eb87ed871d2666fcd3f51bb3e",
"org_id": "crg",
"active": true,
"roles": [
"admin"
],
"metadata": {},
"last_updated": 1619707637
}
```
=> Add last_updated field to rest api resources

sdk/Cargo.toml, sdk/src/locations/mod.rs, sdk/src/migrations/diesel/postgres/mod.rs, sdk/src/migrations/diesel/sqlite/mod.rs, sdk/src/products/mod.rs, sdk/src/schemas/mod.rs, sdk/src/store/mod.rs, sdk/src/store/postgres.rs, sdk/src/store/sqlite.rs
This adds cross-cutting features to the Grid SDK for the locations, products, and schemas modules. These features control whether the db code for each module gets compiled.
=> Add cross-cutting db features

cli/man/grid-agent-create.1.md, cli/man/grid-agent-list.1.md, cli/man/grid-agent-show.1.md, cli/man/grid-agent-update.1.md, cli/src/actions/agents.rs, cli/src/actions/mod.rs, cli/src/main.rs
Includes man-pages. List includes formatting human and csv types, along
with the ability to list roles on their own lines. The Show command
gives additional information, and requires a public key as the
identifier. (Agent ID is synonymous with public key.)
=> List and show agents in the CLI

contracts/pike/src/handler.rs
This change fixes several typos present in the Pike smart contract's
`handler` module.
=> Fix typos in Pike smart contract

daemon/src/event/db_handler.rs, sdk/src/batches/store/diesel/operations/change_batch_to_submitted.rs, sdk/src/commits/store/diesel/operations/add_commit.rs, sdk/src/commits/store/diesel/operations/create_db_commit_from_commit_event.rs, sdk/src/commits/store/diesel/operations/get_commit_by_commit_num.rs, sdk/src/commits/store/diesel/operations/get_current_commit_id.rs, sdk/src/commits/store/diesel/operations/get_next_commit_num.rs, sdk/src/commits/store/diesel/operations/resolve_fork.rs, sdk/src/commits/store/error.rs, sdk/src/locations/store/diesel/operations/add_location.rs, sdk/src/locations/store/diesel/operations/get_location.rs, sdk/src/locations/store/diesel/operations/list_locations.rs, sdk/src/locations/store/diesel/operations/update_location.rs, sdk/src/pike/store/diesel/operations/get_role.rs, sdk/src/pike/store/diesel/operations/list_roles_for_organization.rs, sdk/src/products/store/diesel/operations/get_product.rs, sdk/src/products/store/diesel/operations/list_products.rs, sdk/src/products/store/diesel/operations/update_product.rs, sdk/src/schemas/store/diesel/operations/get_property_definition_by_name.rs, sdk/src/schemas/store/diesel/operations/get_schema.rs, sdk/src/schemas/store/diesel/operations/list_property_definitions.rs, sdk/src/schemas/store/diesel/operations/list_property_definitions_with_schema_name.rs, sdk/src/schemas/store/diesel/operations/list_schemas.rs
This makes all operations atomic. Previously, this was done in a sort of
piecemeal fashion. This just cleans this up and makes sure all
operations are wrapped in the generic diesel transaction. This is
available for all Diesel backends that implement Diesel::Connection.
This depends on PR #656.
=> Make all operations atomic

sdk/src/commits/store/diesel/operations/add_commit.rs, sdk/src/commits/store/diesel/operations/get_commit_by_commit_num.rs, sdk/src/commits/store/diesel/operations/get_current_commit_id.rs
This updates the commit store operations to use the `optional()` method
to handle Diesel Results. This method handles converting the results
into Options or the appropriate NotFound errors.
=> Use `optional()` method to convert results

sdk/src/commits/store/diesel/mod.rs, sdk/src/commits/store/diesel/operations/add_commit.rs, sdk/src/commits/store/diesel/operations/create_db_commit_from_commit_event.rs, sdk/src/commits/store/diesel/operations/resolve_fork.rs, sdk/src/commits/store/error.rs, sdk/src/commits/store/mod.rs
This updates the commit store error module. This removes the
CommitEventError error type as it was a duplicate of CommitStoreError.
This also moves the From implementations of CommitStoreError to the
error.rs file to be in line with the best practices. Lastly, this
updates the CommitStore implementations to use the From implementations.
=> Update Commit store errors

sdk/src/commits/store/diesel/mod.rs, sdk/src/commits/store/diesel/operations/resolve_fork.rs
This adds a brief CommitStore module doc comment to the diesel commit
store mod.rs file. This also adds a doc comment explaining the
`resolve_fork` db operation.
=> Add brief CommitStore module doc comment

cli/src/actions/agents.rs, cli/src/actions/organizations.rs, cli/src/actions/roles.rs, sdk/protos/pike_payload.proto, sdk/src/protocol/pike/payload.rs
PikePayload protocol object now has a single action object instead of
multiple payload objects. The Action enum has been updated to hold a
payload object that corresponds to each enum type.
=> Refactor pike protocol payload

cli/src/actions/locations.rs
This was causing location transactions to fail when the smart contract
attempted to read the location schema.
=> Add Schema namespace to location txn inputs

sdk/Cargo.toml, sdk/src/lib.rs
This top-level "rest-api" feature prevents the rest_api module from
existing unless a REST API feature is enabled.
This is part of a larger effort to cleanup dependencies in the SDK.
=> Add "rest-api" feature to guard top-level module

daemon/src/rest_api/mod.rs, daemon/src/sawtooth/run.rs, daemon/src/splinter/run.rs, sdk/Cargo.toml, sdk/src/backend/error.rs, sdk/src/backend/mod.rs, sdk/src/backend/sawtooth.rs, sdk/src/backend/splinter.rs, sdk/src/lib.rs, sdk/src/rest_api/actix_web_3/backend_state.rs, sdk/src/rest_api/actix_web_3/mod.rs, sdk/src/rest_api/actix_web_3/routes/batches.rs, sdk/src/rest_api/actix_web_3/routes/mod.rs, sdk/src/rest_api/actix_web_3/store_state.rs, sdk/src/rest_api/resources/batches/v1/handler.rs, sdk/src/rest_api/resources/batches/v1/payloads.rs, sdk/src/rest_api/resources/mod.rs
The trait formerly known as "BatchSubmitter" was really a client to the backend (Sawtooth or Splinter). This gives it distinction from other batch-related functionality within the sdk and daemon.
=> Rename batch submitter to backend client

sdk/protos/pike_payload.proto, sdk/protos/pike_state.proto, sdk/src/migrations/diesel/postgres/mod.rs, sdk/src/migrations/diesel/sqlite/mod.rs, sdk/src/pike/store/diesel/operations/add_agent.rs, sdk/src/pike/store/diesel/operations/add_organization.rs, sdk/src/pike/store/diesel/operations/add_role.rs, sdk/src/pike/store/diesel/operations/get_agent.rs, sdk/src/pike/store/diesel/operations/get_organization.rs, sdk/src/pike/store/diesel/operations/get_role.rs, sdk/src/pike/store/diesel/operations/list_agents.rs, sdk/src/pike/store/diesel/operations/list_organizations.rs, sdk/src/pike/store/diesel/operations/list_roles_for_organization.rs, sdk/src/pike/store/diesel/operations/update_agent.rs, sdk/src/protocol/pike/payload.rs, sdk/src/protocol/pike/state.rs
All of these files were substantially updated in 2021 and the copyright
header needs to reflect that.
=> Update copyright for pike modules

griddle/Cargo.toml, griddle/src/main.rs, sdk/Cargo.toml, sdk/src/batches/store/mod.rs, sdk/src/rest_api/actix_web_3/store_state.rs
This removes sqlite and postgres from the sdk's rest-api-actix-web-3
feature, which will make it possible to conditionally use the sqlite or
postgresql when using the rest api.
This commit makes BatchList pub, because without pub, it would be
necessary to put a conditional of the underlying implementations being
enabled; it seems cleaner to simply make it pub since it does not seem
intentional to prevent creation of BatchList (which itself is pub).
Features are added to griddle for sqlite/postgres to pull in the
associated sdk features.
=> Remove sqlite and postgres from rest api feature

sdk/Cargo.toml
This was an error in the dependency list for rest-api-actix-web-3 and
isn't intended to be a functional change (other than fixing compilation
if specifying this feature in isolation).
=> Add "backend" as dependency for "rest-api-actix-web-3"

griddle/Cargo.toml, sdk/Cargo.toml, sdk/src/rest_api/actix_web_3/mod.rs, sdk/src/rest_api/actix_web_3/routes/mod.rs, sdk/src/rest_api/actix_web_3/run.rs, sdk/src/rest_api/resources/mod.rs
This adds several features which guard the REST API endpoint; this
will allow the daemon processes to individually pull in the specific
endpoints supported. It also allows enabling the underlying features
without enabling the associated endpoints.
=> Add feature guards for each REST API endpoint

daemon/Cargo.toml, daemon/src/event/db_handler.rs, daemon/src/main.rs, daemon/src/sawtooth/run.rs, daemon/src/splinter/run.rs
This adds feature guards for the separate database backends to the Grid
daemon. This allows for conditional compilation of code that pertains to
database functionality. At least one active backend is required for the
daemon to work.
=> Add database-* feature guards to the daemon

daemon/src/splinter/app_auth_handler/error.rs, daemon/src/splinter/app_auth_handler/mod.rs, daemon/src/splinter/app_auth_handler/node.rs, daemon/src/splinter/app_auth_handler/sabre.rs
This change updates the copyright headers of files in the `splinter`
module to reflect the current year.
=> Update copyright headers in `splinter` module

cli/man/grid-product-create.md, cli/man/grid-product-update.md
Update explanation for --file flag for product
Remove `--owner` option from `grid product update` man page
=> Update product man pages

sdk/src/product/gdsn/GridTradeItems.xsd
The GridTradeItems schema doesn't need to pull in SharedCommon.xsd and GdsnCommon.xsd because TradeItem.xsd already imports it. This was causing some duplicate import errors in product definitions that imported these modules.
=> Update GridTradeItems.xsd imports

daemon/src/rest_api/mod.rs, sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/migrations/diesel/postgres/mod.rs, sdk/src/migrations/diesel/sqlite/mod.rs, sdk/src/migrations/mod.rs, sdk/src/testing/mod.rs, sdk/src/testing/postgres/mod.rs, sdk/src/testing/sqlite/mod.rs
This moves the `clear_database` functions for clearing the postgres and
sqlite databases to a new testing module. These are guarded behind new
features `test-postgres` and `test-sqlite` respectively. This does not
change any functionality.
=> Move `clear_database` fns to new `testing` module

cli/src/main.rs
The Man page specifies that there would be both a draft - which is by
default, and a not-draft flag. Updated this implementation to match the
man-page, because draft is a flag and is set to true by default, there
would be no way of setting it to false. Also draft and not-draft is
the convention used for other components. This method is not yet
implemented so it should have no impact on the application.
=> Update CLI PO create to include not-draft option

sdk/src/product/gdsn/mod.rs, sdk/src/product/gdsn/validate.rs
This fixes a typo in the function name `validate_product_definitons` to
`validate_product_definitions`
=> Fix typo in gdsn product

daemon/src/event/db_handler.rs
This change updates the messages used to log Pike-related database
operations. Updates include adding a log message when a Role is removed
and added parenthesis around the pluralization around objects inserted,
as these lists may have one or more objects.
=> Update Pike database operation logging messages

sdk/src/batches/store/diesel/mod.rs, sdk/src/batches/store/diesel/models.rs
This moves the batch store struct conversion implementations to the
models.rs file. This is part of the batch store stabilization effort and
brings the store in line with the others.
=> Move batch struct conversion to models file

daemon/src/event/db_handler.rs
This adds a `database-postgres` feature guard to the database event
handler implementations in the daemon's db handler that was missing.
=> Add missing feature guard

contracts/location/src/handler.rs, contracts/pike/src/handler.rs, contracts/product/src/handler.rs, contracts/schema/src/handler.rs, sdk/src/lib.rs, sdk/src/pike/mod.rs, sdk/src/pike/permissions/error.rs, sdk/src/pike/permissions/mod.rs
/sdk/src/permissions.rs was split apart into two separate files,
"/sdk/pike/permissions/mod.rs" which contains the PermissionChecker
implementation, and "/sdk/pike/permissions/error.rs" which contains the
PermissionCheckerError implementation. This means also that the import
path changed from grid_sdk::permissions to grid_sdk::pike::permissions,
so the handler files requesting permissions has also updated.
=> Move sdk permissions into pike/permissions module

daemon/src/event/db_handler.rs, daemon/src/event/error.rs, daemon/src/rest_api/mod.rs, sdk/src/product/store/error.rs, sdk/src/product/store/mod.rs, sdk/src/rest_api/resources/products/v1/handler.rs, sdk/src/rest_api/resources/products/v1/payloads.rs
This adds public accessor methods with doc strings for each of the
public data structures in the Product module. This also makes the
corresponding fields private.
=> Add accessor methods for data structures

sdk/src/pike/addressing.rs, sdk/src/pike/store/diesel/mod.rs, sdk/src/pike/store/diesel/models.rs, sdk/src/pike/store/diesel/operations/add_agent.rs, sdk/src/pike/store/diesel/operations/add_organization.rs, sdk/src/pike/store/diesel/operations/add_role.rs, sdk/src/pike/store/diesel/operations/delete_role.rs, sdk/src/pike/store/diesel/operations/get_agent.rs, sdk/src/pike/store/diesel/operations/get_organization.rs, sdk/src/pike/store/diesel/operations/get_role.rs, sdk/src/pike/store/diesel/operations/list_agents.rs, sdk/src/pike/store/diesel/operations/list_organizations.rs, sdk/src/pike/store/diesel/operations/list_roles_for_organization.rs, sdk/src/pike/store/diesel/operations/mod.rs, sdk/src/pike/store/diesel/operations/update_agent.rs, sdk/src/pike/store/error.rs, sdk/src/pike/store/mod.rs
Adds module-level comments and docstrings to the Pike module in the Grid
SDK. Mainly adds comments to describe the functionality provided by the
`PikeStore`.
=> Add Pike documentation to Grid SDK

cli/src/actions/locations.rs
This was causing location transactions to fail when the smart contract
attempted to read the location schema.
=> BACKPORT: Add Schema namespace to location txn inputs

cli/src/main.rs
`Key` option help information updated to include GRID_DAEMON_KEY and
CYLINDER_PATH defaults. `service_id` option help was updated to include
GRID_SERVICE_ID environment variable. URL option help was updated to
include GRID_SERVICE_ENDPOINT default.
=> Update help with env var defaults

sdk/src/pike/store/diesel/operations/add_agent.rs, sdk/src/pike/store/diesel/operations/add_organization.rs, sdk/src/pike/store/diesel/operations/add_role.rs
This fixes the update_* operations for the Pike module to properly set
the `end_commit_num` for the record being updated. Previously, the
`end_commit_num` was not being updated because the diesel query builder
was not properly checking for the `service_id` or lack thereof.
=> Fix Pike update ops for Sawtooth

cli/src/actions/keygen.rs, cli/src/main.rs, examples/sawtooth/docker-compose.yaml, examples/splinter/docker-compose.yaml
subsequent runs of docker compose up in the example projects would fail
due to keys created in previous runs. Adding a --skip flag allows us to
reuse previously-created keys. Also updated docker-compose in example
projects
=> Add --skip flag to keygen CLI

contracts/schema/src/handler.rs
This fixes a typo in an error message in the schema smart contract
caused by attempting to update a smart contract with a duplicate
property.
=> Fix typo in schema contract error msg

cli/src/signing.rs
current_user_search_path() would look in root/.cylinder/keys, whereas we
have documentation that leads us to root/.grid/keys. This change aligns
code to the documentation.
=> Fix CLI signing path for --key

cli/Cargo.toml, sdk/Cargo.toml
This stabilizes the "sqlite" sdk feature by moving it into stable. This
also moves its associated "database-sqlite" feature in other parts of
Grid into stable.
=> Stabilize sqlite features

daemon/Cargo.toml, daemon/src/config.rs, daemon/src/main.rs, daemon/src/sawtooth/run.rs, daemon/src/splinter/run.rs
This changes the `endpoint` value in the GridConfig to a string.
Previously, this was an `Endpoint` value using the `Endpoint` type from
the `actix_web_3` module in the sdk. Now the conversion is done in the
`run_splinter` and `run_sawtooth` functions and is guarded behind the
`rest-api` feature.
=> Remove rest api Endpoint from config

daemon/src/sawtooth/run.rs, daemon/src/splinter/run.rs
This change creates an `Endpoint` object from the `GridConfig`'s
`endpoint` immediately as it is passed into the daemon's `run` methods
for Splinter and Sawtooth backends. This allows for the backend rest
API URL to be correctly formatted as it is returned by the
config object with a `splinter:` or `sawtooth:` prefix to allow the
daemon to start correctly. This fixes the issue where the `splinter:`
and `sawtooth:` prefixes are being passed in with the URL, returning
an error as this creates an invalid URL scheme.
To test: run `docker-compose -f examples/splinter/docker-compose.yaml up` and ensure that the logs start as normal
=> Fix rest API URL handling in `run` methods

sdk/src/rest_api/actix_web_3/service.rs
Fixes an error message produced when the Grid daemon verifies the `service_id`. The `service_id` should be present if Grid is running on Splinter and should not be present if Grid is running on Sawtooth. The error message fixed in this PR is produced if the service id is present while on sawtooth and the other instance when it is not present on splinter. In each case, the errors produced stated that the `Circuit ID` was/was not present. However, this message should state `Service ID` as this is actually the value being checked.
=> Fix Rest API error message

daemon/src/event/db_handler.rs, daemon/src/rest_api/mod.rs, sdk/src/pike/store/builder.rs, sdk/src/pike/store/error.rs, sdk/src/pike/store/mod.rs, sdk/src/rest_api/resources/agents/v1/payloads.rs
This PR makes a few changes in order to allow the fields of the `Agent` Pike struct to be private, rather than public. Store objects should have private fields and accessor methods, hence the change. Also, this PR adds a new `builder` module within the Pike store which currently holds an `AgentBuilder` used to construct agents. This PR also implements the use of the `AgentBuilder`.
=> Add accessor methods to Pike `Agent`

sdk/Cargo.toml, sdk/src/commits/store/diesel/mod.rs, sdk/src/commits/store/diesel/operations/get_current_service_commits.rs, sdk/src/commits/store/diesel/operations/mod.rs, sdk/src/commits/store/mod.rs
This change adds a method to the `CommitStore` to provide the current commits for all services.
It also adds the implementation for the `DieselCommitStore`, supplying the query via an operation trait.  The operation implementation itself requires using a raw SQL query, as the query cannot be generated using the diesel DSL (as of diesel 1.4.x releases).
It is guarded behind the experimental feature `"commit-store-service-commits"`.
=> Add get_current_service_commits

cli/man/grid-organization-create.1.md, cli/man/grid-organization-list.1.md, cli/man/grid-organization-show.1.md, cli/man/grid-organization-update.1.md, cli/man/grid-organization.1.md, cli/src/actions/organizations.rs, cli/src/main.rs
This change adds commands to list organizations and to show a specific organization based on the `org_id`. This also adds the man page entries for each of these commands.
=> Add grid organization `list` and `show` commands 

daemon/src/event/db_handler.rs, sdk/src/pike/store/builder.rs, sdk/src/pike/store/mod.rs, sdk/src/rest_api/resources/roles/v1/payloads.rs
This change updates the Role struct in the PikeStore to have private fields, with public accessor methods. This PR also adds a `RoleBuilder` implementation that may be used to create a `Role`.
=> Add private fields to Pike store's Role

examples/splinter/docker-compose.yaml
This adds the `contracts-shared` volume to the scabbard-cli containers
for the grid on splinter example. This is necessary for the smart
contract upgrade process to work.
=> Add contracts volume to scabbard-cli containers

daemon/src/event/db_handler.rs, daemon/src/rest_api/mod.rs, sdk/src/pike/store/builder.rs, sdk/src/pike/store/mod.rs, sdk/src/rest_api/resources/organizations/v1/payloads.rs
This PR removes public fields from the remaining Pike store structs, including Organization, AlternateId, and OrganizationMetadata. The public fields are replaced by public accessor methods. Creating these objects has been replaced by each struct's builder, which are implemented in the PikeStore's builder module.
=> Remove public fields from Pike Organization, Alternate ID, and metadata

cli/src/actions/agents.rs, cli/src/actions/locations.rs, cli/src/actions/organizations.rs, cli/src/actions/products.rs, cli/src/actions/roles.rs, cli/src/actions/schemas.rs, cli/src/transaction.rs, contracts/pike/packaging/scar/manifest.yaml, contracts/pike/pike.yaml, contracts/pike/src/handler.rs, contracts/track_and_trace/src/handler.rs, daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, daemon/src/splinter/app_auth_handler/sabre.rs, integration/docker-compose.yaml, sdk/src/pike/addressing.rs
The rest of the grid contracts are prefixed with grid_, this change updates
pike to match.
=> Rename pike to grid_pike

daemon/Cargo.toml, daemon/src/splinter/run.rs, sdk/src/error/invalid_state.rs, sdk/src/error/mod.rs
To Test:
Start up a network using
```
$ docker-compose -f examples/splinter/docker-compose.yaml up --build
```
Follow the guide for [creating circuits](https://grid.hyperledger.org/docs/0.2/creating_splinter_circuits.html).
`ctrl+c`  the compose run, followed by 
```
$ docker-compose -f examples/splinter/docker-compose.yaml up
```
Attempt to create a role (via the [pike guid](https://grid.hyperledger.org/docs/0.2/using_pike.html))
Before this PR, this would not receive state delta events.  After, the state delta events should still be applied.
~Depends on #801~
=> Reconnect scabbard event processors on restart

sdk/src/batches/store/mod.rs
This adds some brief doc comments to the Batch store methods. These
comments give a brief description of the operation and the arguments for
that function.
=> Add doc comments for the batch store methods

daemon/Cargo.toml, sdk/Cargo.toml, sdk/src/commits/store/diesel/mod.rs, sdk/src/commits/store/diesel/operations/mod.rs, sdk/src/commits/store/mod.rs
This change stabilizes the feature "commit-store-service-commits" by removing the feature. The method it guards will now be part of the complete store API for commits, as a result.
=> Stabilize commit-store-service-commits

sdk/src/batches/store/builder.rs, sdk/src/batches/store/error.rs, sdk/src/batches/store/mod.rs, sdk/src/rest_api/resources/submit/v1/handler.rs
This updates the Batches store to use the builder pattern established in
other stores. This updates the structs with builders and accessor
methods to help stabilize the feature.
=> Use builder pattern for Batch store

cli/Cargo.toml, daemon/Cargo.toml
In the CLI and gridd we want the default experience to include all Grid business functionality. This set of commits moves pike, product, schema, and location to default for these two components.
=> Move Grid features to default in CLI and gridd

examples/sawtooth/docker-compose.yaml
This updates the `pike-contract-builder` for the Sawtooth example
Docker-compose file to account for the name change from `pike` to
`grid-pike`.
=> Update Sawtooth dockerfile for grid_pike

sdk/src/pike/store/diesel/operations/add_agent.rs
This fixes an issue with updating a role that belongs to an agent. The
pike_agent_role_assoc table was not updating correctly when roles that
already belonged to an agent were updated.
=> Fix agent-role update

examples/sawtooth/docker-compose.yaml
backport to 0.2
This updates the `pike-contract-builder` for the Sawtooth example
Docker-compose file to account for the name change from `pike` to
`grid-pike`.
=> BACKPORT: Update Sawtooth dockerfile for grid_pike

sdk/src/pike/store/diesel/operations/add_agent.rs
Backport to 0.2
This fixes an issue with updating a role that belongs to an agent. The
pike_agent_role_assoc table was not updating correctly when roles that
already belonged to an agent were updated.
=> BACKPORT: Fix agent-role update

ui/saplings/product/src/components/ProductsTable.js
The namespace numbers are not guaranteed for these XML documents, so we
can't have that namespace prefix hardcoded in the parsing functionality.
`fast-xml-parser` has an option to ignore these namespace prefixes. We
do lose the namespace prefixes in the downloaded XML from the table due
to this.
=> Remove namespaces from XML parsing

ui/saplings/product/src/components/ProductsTable.js, ui/saplings/product/src/components/Table.js, ui/saplings/product/src/components/Table.scss
Add a loading indicator on the products table. This load can take a few seconds since we are brute force searching for Org names. This should be optimized eventually, but either way we should add an indicator when we are loading data.
=> Add Product table loading indicator

ui/saplings/product/src/components/ProductsTable.js
The namespace numbers are not guaranteed for these XML documents, so we
can't have that namespace prefix hardcoded in the parsing functionality.
`fast-xml-parser` has an option to ignore these namespace prefixes. We
do lose the namespace prefixes in the downloaded XML from the table due
to this.
=> BACKPORT: Remove namespaces from XML parsing

ui/saplings/product/src/components/ProductsTable.js, ui/saplings/product/src/components/Table.js, ui/saplings/product/src/components/Table.scss
This load can take a few seconds since we are brute force searching for
Org names. This should be optimized eventually.
=> BACKPORT: Add loading indicator for Table

daemon/Cargo.toml, daemon/src/splinter/run.rs, sdk/Cargo.toml, sdk/src/backend/splinter.rs
This adds support for using Cylinder JWTs as an Auth header in requests
to submit batches. This new functionality is guarded behind the
experimental `cylinder-jwt-support` feature. This creates the Signer in
the the `run_splinter` function which is then passed through to the
REST API when that is set up.
=> Add experimental support for Cylinder JWTs

daemon/src/event/db_handler.rs, daemon/src/event/mod.rs, daemon/src/splinter/app_auth_handler/mod.rs, daemon/src/splinter/event/mod.rs, daemon/src/splinter/event/processors.rs, daemon/src/splinter/run.rs
This PR introduces an EventProcessors struct to manages that event processors are only created once per circuit/service instance.
It also introduces a work-around for an issue with database transaction creation while handling commit events. It serializes the events received from event processors into a channel and handle the events serially.  This fix ensures that duplicate events won't result in duplicate entries in the DB.  This second commit may be rolled back when a proper fix for transactions is introduced.
=> Avoid duplicate events

cli/src/main.rs
Work done involved verifying that the CLAP definitions align with man
pages. The CLAP definitions were already aligned, but the `--key` option
required updating throughout all of main.rs
=> Update CLAP definitions to align with man pages.

sdk/src/migrations/diesel/postgres/migrations/2021-03-30-164015_update_batch_tables/down.sql, sdk/src/migrations/diesel/postgres/migrations/2021-07-22-161800_drop_unused_tables/down.sql, sdk/src/migrations/diesel/postgres/migrations/2021-07-22-161800_drop_unused_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-03-30-164015_update_batch_tables/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-07-22-161800_drop_unused_tables/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-07-22-161800_drop_unused_tables/up.sql
This PR adds a migration folder to both the sqlite and postgres migration modules to correct a few migration data inconsistencies. Mainly, this addresses two issues: 
- Down unused tables in the newly added `up.sql` file
(This includes tables meant to store circuit data that are currently not being used to store any data)
- Correctly down some tables that are incorrectly downed in their respective migration modules 
(The tables are downed in the original migration file using the command `DROP` rather than `DROP TABLE`)
=> Fix some incorrect migration data

contracts/purchase_order/src/state.rs
This PR adds implementations for a few methods on the Purchase Order state that are used by the smart contract actions. This pr adds implementations for the methods `get_purchase_order`, `set_purchase_order`, `get_agent`, and `get_organization`.
=> Implement some methods for Purchase Order state

.gitignore, ci/grid-dev, cli/Cargo.toml, cli/Dockerfile, cli/build.rs, cli/packaging/man/README.md, daemon/Dockerfile
Uses pandoc to convert markdown files from cli/man to manfiles in
cli/packaging/man. This follows the same pattern found in the Splinter
project's cli.
=> Generate man pages for cli

cli/build.rs
This change removes unneeded references from the CLI's `build.rs` file.
These references caused errors when running `just lint`.
=> Fix clippy error in CLI build file

contracts/purchase_order/src/state.rs, sdk/protos/purchase_order_payload.proto, sdk/protos/purchase_order_state.proto, sdk/src/protocol/purchase_order/payload.rs, sdk/src/protocol/purchase_order/state.rs
This change makes various updates to the Purchase Order smart contract's
state and payload protobuf messages, as several necessary attributes
were left out of these messages.
=> Update purchase order protos

sdk/src/workflow/mod.rs
This change makes a few updates across workflow tests implemented using purchase order objects. These changes include removing unused imports from the workflow module's tests in the purchase order smart contract. This also includes updating the workflow module's tests in the SDK to match the updated permission/aliases for purchase order based on the most updated RFC.
=> Update purchase-order specific workflow tests

contracts/purchase_order/src/state.rs, sdk/protos/purchase_order_payload.proto, sdk/protos/purchase_order_state.proto, sdk/src/protocol/purchase_order/payload.rs, sdk/src/protocol/purchase_order/state.rs
This PR updates the `PurchaseOrderPayload` to remove the `org_id` field, as the organizations are now being recorded in the purchase order itself. This also updates the `CreatePurchaseOrderPayload` and `PurchaseOrder` struct in state to support a `buyer_org` and `seller_org` fields for the purchase order.
=> Add `buyer` and `seller` org fields to Purchase Order

sdk/src/migrations/diesel/postgres/migrations/2021-09-10-131000_update_purchase_order_tables/down.sql, sdk/src/migrations/diesel/postgres/migrations/2021-09-10-131000_update_purchase_order_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-09-10-131000_update_purchase_order_tables/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-09-10-131000_update_purchase_order_tables/up.sql, sdk/src/purchase_order/store/diesel/mod.rs, sdk/src/purchase_order/store/diesel/models.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/list_alternate_ids_for_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_orders.rs, sdk/src/purchase_order/store/diesel/schema.rs, sdk/src/purchase_order/store/mod.rs, sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs, sdk/src/rest_api/resources/purchase_order/v1/handler.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
This updates the PO store to account for the changes to the PO protobuf messages. This updates the schemas, DB models, Grid structs, DB operations, and REST API to account for the different fields in the updated messages.
=> Update PO store for updated protos

sdk/src/purchase_order/store/error.rs, sdk/src/purchase_order/store/mod.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
This adds public accessor methods to the PurchaseOrderStore structs
and makes the structs' fields private. This also adds builders for the
structs. This brings the module in-line with the other Grid stores.
=> Add Purchase Order store struct accessors and builders

sdk/src/client/pike/reqwest.rs
This change updates the `ROLES_ENDPOINT` const, defined for the
`ReqwestPikeClient`, to `ROLE_ENDPOINT` and updates the value from
"roles" to "role". The role endpoint is singular.
=> Fix Client `ROLES_ENDPOINT` const

contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/main.rs, contracts/purchase_order/src/permissions.rs, contracts/purchase_order/src/state.rs, contracts/purchase_order/src/workflow.rs, sdk/src/pike/permissions/mod.rs
This change adds an implementation to the purchase order smart contract's "create po" action. This action is implemented using the workflow-aware permission check.
=> Add workflow-aware "Create PO" action

sdk/src/purchase_order/store/diesel/mod.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order_version.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs, sdk/src/purchase_order/store/mod.rs
This adds a `get_purchase_order_version` operation. This fetches a PO
version and its associated revisions and returns the Grid representation
of them.
=> Add `get_purchase_order_version` operation

sdk/src/purchase_order/store/diesel/mod.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_versions.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs, sdk/src/purchase_order/store/mod.rs
This adds a `list_purchase_order_versions` operation to the purchase
order store. This operation gets a list of purchase order versions for a
gived purchase order. This also includes that version's revisions.
=> Add `list_purchase_order_versions` operation

daemon/src/event/db_handler.rs, daemon/src/event/error.rs
This sets up the state delta export for purchase order events. This PR also adds the conversion methods to `EventError` for the purchase order store errors.
=> Hookup PO SDE

sdk/src/purchase_order/store/diesel/models.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order_version.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order_version_revision.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs
This updates the `add_purchase_order` operation to properly add/update POs, versions, and revisions while avoiding unnecessary db updates.
=> Update `add_purchase_order` operation

ui/saplings/product/src/components/CircuitDropdown.scss
To conform to the CSS standard, plus and minus characters must be
surrounded by whitespace within the calc function. The lack of
whitespace caused the docker image build to fail when creating
grid-ui-alpha. This change fixes that by adding the appropriate
whitespace.
=> Add whitespace to conform to calc CSS standard

ui/saplings/product/src/components/CircuitDropdown.scss
To conform to the CSS standard, plus and minus characters must be
surrounded by whitespace within the calc function. The lack of
whitespace caused the docker image build to fail when creating
grid-ui-alpha. This change fixes that by adding the appropriate
whitespace.
=> BACKPORT 0-2: Conform whitespace to calc CSS standard

examples/griddle/docker-compose-dockerhub.yaml, examples/griddle/docker-compose-sawtooth.yaml, examples/griddle/docker-compose-splinter.yaml
These docker examples are likely to be rerun many times. The --skip
option will allow the entrypoint command to run without throwing an
error if the keys are already generated.
=> Add `--skip` to griddle examples

sdk/src/client/pike/reqwest.rs, sdk/src/pike/store/diesel/models.rs
This fixes a bug where roles' `inherit_from` roles were not being
displayed correctly. This fixes it so roles now properly display their
inherited roles.
$ grid keygen alpha-agent
$ grid keygen beta-agent
$ export GRID_DAEMON_KEY="beta-agent" && grid organization create beta BetaOrg --alternate-ids gs1_company_prefix:0 --wait 10
$ export GRID_DAEMON_KEY="alpha-agent" && grid organization create alpha AlphaOrg --alternate-ids gs1_company_prefix:1 --wait 10
$ grid role create alpha productowner --permissions schema::can-create-schema,product::can-create-product,product::can-delete-product,schema::can-update-schema,product::can-update-product --active --wait 10
$ export GRID_DAEMON_KEY="beta-agent"
$ $ grid role create beta alpha-po --permissions product::can-update-product --inherit-from …
=> Fix get/list role display bug

contracts/purchase_order/src/handler.rs, sdk/protos/purchase_order_payload.proto, sdk/src/protocol/purchase_order/payload.rs
This adds a `workflow_status` field to the `CreatePurchaseOrder` payload
which brings the create payload in line with its update counterpart.
=> Add `workflow_status` to `CreatePurchaseOrder` payload

cli/Cargo.toml, cli/src/actions/keygen.rs
Add tests to validate the behavior of key generation given various
permutations of the configuration values.
=> Test keygen

sdk/src/migrations/diesel/postgres/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/purchase_order/store/diesel/mod.rs, sdk/src/purchase_order/store/diesel/models.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order_version_revision.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_version_revisions.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs, sdk/src/purchase_order/store/diesel/schema.rs, sdk/src/purchase_order/store/mod.rs
This adds database operations to the `PurchaseOrderStore` to get and list `PurchaseOrderVersionRevisions`. The list operation lists revisions filtered by `po_uid` and `version_id` and the get operation fetches a revision filtered by `po_uid`, `version_id`, and `revision_id`. This also includes migrations and updates to the revisions table to add a `purchase_order_uid` column. This is necessary to be able to properly get revisions in case of overlap in version IDs between different POs.
=> Add list/get revision operations

daemon/openapi.yaml, sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs, sdk/src/rest_api/resources/purchase_order/v1/handler.rs, sdk/src/rest_api/resources/purchase_order/v1/mod.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
Add a purchase order REST endpoint to retrieve a version provided a
version id and a purchase order.
Related to: https://github.com/hyperledger/grid/issues/867
=> Add purchase order version REST endpoint

daemon/openapi.yaml, sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs, sdk/src/rest_api/resources/purchase_order/v1/handler.rs, sdk/src/rest_api/resources/purchase_order/v1/mod.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
Add an endpoint to obtain purchase order versions at
/purchase-order/{UUID}/versions.
Related: #866
=> Add purchase order version list endpoint

cli/src/main.rs
This makes the `workflow_status` and `order_xml` CLI args required for
the PO version create and update commands. A version/revision doesn't
provide much utility without these values.
=> Require `workflow_status` and `order_xml` args

cli/Cargo.toml, cli/man/grid-po-create.1.md, cli/src/actions/purchase_orders.rs, cli/src/main.rs
Adding functionality to create purchase order. Based on the updated RFC,
we need buyer-org and seller-org instead of owning org. Changes are
reflected in the man pages as well as code.
=> Create PO in cli

sdk/src/purchase_order/store/diesel/schema.rs
This change updates the `PurchaseOrder` database table schema to match
the order the fields exist in the `PurchaseOrderModel` struct.
Previously, this caused an error when diesel attempted to insert the
database model into the table, as the native model does not match the
table's schema.
=> Match the db schema to model for Purchase Order

contracts/purchase_order/src/main.rs, contracts/purchase_order/src/payload.rs
This change adds a `payload` module to the purchase order smart contract
for basic validation of the various PurchaseOrderPayload`s that are
handled. These new functions validate that the payload has all the
required fields defined.
=> Add simple validation for po payloads

cli/man/grid-po-revision-show.1.md, cli/man/grid-po-version-show.1.md, cli/src/actions/purchase_orders.rs, cli/src/main.rs, sdk/src/client/purchase_order/mod.rs, sdk/src/client/purchase_order/reqwest.rs, sdk/src/client/reqwest.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
This adds CLI commands for listing and showing Grid Purchase Order versions and revisions. In support of this, the purchase order client's functions and structs are also brought up-to-date with the rest of the module's pieces.
=> Add PO version and revision `list` and `show` CLI commands

cli/man/grid-po-version-create.1.md, cli/man/grid-po-version-update.1.md, cli/man/grid-product-create.1.md, cli/man/grid-product-update.1.md, cli/src/actions/mod.rs, cli/src/actions/products.rs, cli/src/actions/purchase_orders.rs, cli/src/main.rs, sdk/src/data_validation/mod.rs, sdk/src/data_validation/xml/mod.rs, sdk/src/data_validation/xml/xml_ffi.rs, sdk/src/data_validation/xml/xsd/po/gs1/ecom/Order.xsd, sdk/src/data_validation/xml/xsd/po/gs1/ecom/eComCommon.xsd
This change updates the loading of the schema to be done in the
directory where schemas are specified. This directory is able to be set
with the `GRID_ORDER_SCHEMA_DIR` environment variable, or it is set by
default.
=> Update schema loading for Order.xsd

contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/payload.rs
This change passes a reference to the payload, once it is converted to
the PurchaseOrderPayload, to the `validate_po_payload` function. This
function will validate the timestamp within the payload and the
associated action's payload.
=> Validate payloads in `apply` method

cli/Cargo.toml, cli/man/grid-po-list.1.md, cli/man/grid-po-show.1.md, cli/src/actions/purchase_orders.rs, cli/src/error.rs, cli/src/main.rs, sdk/src/client/location/reqwest.rs, sdk/src/client/pike/reqwest.rs, sdk/src/client/product/reqwest.rs, sdk/src/client/purchase_order/mod.rs, sdk/src/client/purchase_order/reqwest.rs, sdk/src/client/reqwest.rs, sdk/src/client/schema/reqwest.rs
This PR updates the Grid CLI to include functionality to list and show a Grid Purchase Order. This includes changes to the Purchase Order client to update the structs and functions to align with the RFC and current discussions. It also includes updates to the version and revision list/show commands to use the new display utility functions/patterns introduced here.
=> Add PO list/show CLI functionality

sdk/src/workflow/mod.rs, sdk/src/workflow/state.rs
This change updates the workflow state module's `can_transition` method,
which validates whether an agent has the correct permissions to
transition to a new workflow state, to check the workflow state's name.
This covers a case in which an agent is not attempting to transition a
workflow, but rather update an object. 
Previously, the `can_transition`
method would return false if it did not have it's own name within it's
transitions. Rather than add all of the workflow states as transitions
to their own state, this will check if we are staying in the same
workflow state and return `true`, as we are not transitioning.
This PR also updates a test to change the name of the workflow state used. This allows an alias' transitions to be validated, while avoiding a situation where the alias is …
=> Validate self workflow state in `can_transition`

daemon/Cargo.toml, sdk/Cargo.toml
This change removes the `sawtooth-compat` feature from the SDK. The
dependencies pulled in by this feature are already pulled in based on
the `target_arch` and the `sawtooth-compat` feature itself does not
protect any code within the SDK.
This also updates the `sawtooth-support` feature in the daemon to pull
in the Sabre and Sawtooth SDKs individually.
=> Remove `sawtooth-compat` from SDK

ui/Dockerfile, ui/grid-ui/docker/test/Dockerfile, ui/saplings/product/test/Dockerfile
This change updates the image used by node within the UI Dockerfiles,
from `lts-alpine` to `14.18.1-alpine3.11`.
This change also updates the copyright headers within the affected files
to include the current year.
=> Backport 0-2: Update the image used by node

cli/src/main.rs
Fixes bug related to location_id.
Resolves: #1013
=> Fix bug in cli `grid location show`

daemon/Cargo.toml, daemon/src/splinter/app_auth_handler/mod.rs, daemon/src/splinter/app_auth_handler/node.rs, daemon/src/splinter/event/mod.rs, daemon/src/splinter/event/processors.rs, daemon/src/splinter/run.rs, sdk/Cargo.toml, sdk/src/backend/splinter.rs
This change backports the updates made to add Cylinder JWT authorization to Grid, to allow it to run with current versions of Splinter.
=> Backport 0-2: Backport the cylinder-jwt-support feature

daemon/src/splinter/app_auth_handler/mod.rs
This change adds a `SplinterProtocolVersion` to the app auth handler's registration to allow for backwards compatibility.
=> Backport 0-2: Backport adding a protocol version for Splinter

cli/src/actions/keygen.rs
Changes private key file perms from 640 to 600. This matches
ssh-keygen (as a standard).
Resolves: #1020
=> Change keygen priv key file permissions

contracts/purchase_order/src/handler.rs
This adds an implementation to the po smart contract for the "update version" action.
=> Add update version action to po smart contract

sdk/Cargo.toml, sdk/src/client/reqwest.rs, sdk/src/rest_api/actix_web_3/mod.rs, sdk/src/rest_api/actix_web_3/routes/agents.rs, sdk/src/rest_api/actix_web_3/routes/locations.rs, sdk/src/rest_api/actix_web_3/routes/organizations.rs, sdk/src/rest_api/actix_web_3/routes/products.rs, sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs, sdk/src/rest_api/actix_web_3/routes/records.rs, sdk/src/rest_api/actix_web_3/routes/roles.rs, sdk/src/rest_api/actix_web_3/routes/schemas.rs, sdk/src/rest_api/resources/agents/v1/handler.rs, sdk/src/rest_api/resources/locations/v1/handler.rs, sdk/src/rest_api/resources/organizations/v1/handler.rs, sdk/src/rest_api/resources/paging/v1/mod.rs, sdk/src/rest_api/resources/products/v1/handler.rs, sdk/src/rest_api/resources/purchase_order/v1/handler.rs, sdk/src/rest_api/resources/roles/v1/handler.rs, sdk/src/rest_api/resources/schemas/v1/handler.rs, sdk/src/rest_api/resources/track_and_trace/v1/handler.rs
This is a rewrite of the paging module with several notable differences
from the original.
The first and most notable change is the addition of arbitary query
string support in the base URL, so we can add filters to the paging
URLs. To facilitate this, this change uses the Rust url crate for both
the external API and internal URL representation. This change also adds
the serde feature to the url library to allow the Paging object to
serialize.
The second change is to modify the returned object to make the "prev"
link optional. This mirrors "next" which was already optional.
Other notable changes include splitting up the internal structure for
ease of reading and testing, added tests to verify offset and
serialization output, and added documentation in anticipation of
Paging module …
=> Add paging query string support, tests, and docs

cli/man/grid-po-version-update.1.md, cli/src/actions/purchase_orders.rs, cli/src/main.rs, sdk/src/client/purchase_order/mod.rs
This adds and implements the `grid po version update` CLI command. This
command is used to update one or more of the editable PO version fields.
This command handles for adding a new revision if new PO XML is
submitted.
=> Add `grid po version update` CLI command

cli/src/main.rs
Implements a fix regarding values of global options being
unavailable to subcommands.
While clap propagates global argument values down to the
subcommand level, they are not available in intermediate levels.
This is in contrast to how we must define them in the app.
Previously, the CLI tried to access global arg values at the level
that they were defined. This fix gets the values at the lowest
subcommand level.
These changes also changed the formatting required by `cargo fmt`.
Resolves: #1026
=> Fix CLI values of global options

cli/src/actions/purchase_orders.rs, cli/src/main.rs, sdk/src/client/purchase_order.rs, sdk/src/client/reqwest/purchase_order/data.rs, sdk/src/client/reqwest/purchase_order/mod.rs
This change fixes the po update cli command by changing it to use the alternate id from the po get endpoint (which is already called earlier and therefore its result is available) instead of the unimplemented `list_alternate_ids` REST client fn.
=> Fix po update cli command

cli/man/grid-po-create.1.md, cli/src/main.rs, daemon/src/event/db_handler.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order_version_revision.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order_version.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order_version_revision.rs, sdk/src/purchase_order/store/diesel/operations/get_uid_from_alternate_id.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_version_revisions.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_versions.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs, sdk/src/purchase_order/store/mod.rs
This updates the Grid PO store, SDE, and CLI to support PO creation and lookup using a properly formatted (`<id_type>:<id>`) alternate ID. This change includes an update to the `grid create po` CLI command to update the flag for specifying an alternate ID to `--alternate-id` from the less descriptive `--id`.
=> Support `alternate_id` for PO creation and lookup

daemon/Cargo.toml, sdk/Cargo.toml
This change removes the `pike-rest-api` feature from the SDK. This
feature is a duplicate of the `rest-api-resources-agent` feature.
=> Remove `pike-rest-api` feature

sdk/src/rest_api/actix_web_3/mod.rs
This updates the logic for extracting the base URL so that filters will be passed along to paging.
=> Fix pagination filters

daemon/Cargo.toml, daemon/src/splinter/run.rs, sdk/Cargo.toml, sdk/src/backend/splinter.rs
This change stabilizes the "cylinder-jwt-support" feature by removing it
from the Grid SDK.
=> Stabilize SDK's "cylinder-jwt-support" by removing it

cli/man/grid-po-create.1.md, cli/man/grid-po-show.1.md, cli/man/grid-po-update.1.md, cli/man/grid-po-version-create.1.md, cli/man/grid-po-version-show.1.md, cli/man/grid-po-version-update.1.md, cli/src/actions/purchase_orders.rs, cli/src/main.rs, contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/payload.rs, contracts/purchase_order/src/permissions.rs, contracts/purchase_order/src/state.rs, daemon/openapi.yaml, daemon/src/event/db_handler.rs, sdk/protos/purchase_order_payload.proto, sdk/protos/purchase_order_state.proto, sdk/src/client/purchase_order.rs, sdk/src/client/reqwest/purchase_order/data.rs, sdk/src/migrations/diesel/postgres/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/protocol/purchase_order/payload.rs, sdk/src/protocol/purchase_order/state.rs, sdk/src/purchase_order/store/diesel/models.rs, sdk/src/purchase_order/store/diesel/schema.rs, sdk/src/purchase_order/store/mod.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
This replaces all references/arguments/variables called
`workflow_status` with the name `workflow_state`. This is for
consistency and accuracy.
=> Replace `workflow_status` with `workflow_state`

daemon/Cargo.toml, daemon/src/splinter/app_auth_handler/mod.rs, daemon/src/splinter/app_auth_handler/node.rs, daemon/src/splinter/event/mod.rs, daemon/src/splinter/event/processors.rs, daemon/src/splinter/run.rs
This change stabilizes the grid daemon's experimental
"cylinder-jwt-support" feature by removing it.
=> Stabilize gridd "cylinder-jwt-support" by removing

cli/src/actions/purchase_orders.rs, cli/src/main.rs, sdk/src/client/purchase_order.rs, sdk/src/client/reqwest/purchase_order/mod.rs, sdk/src/purchase_order/store/diesel/operations/get_uid_from_alternate_id.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_orders.rs, sdk/src/purchase_order/store/mod.rs
This updates the purchase order code to enforce uniqueness for alternate IDs. This adds checks to both the client and PO store to make sure that alternate IDs are only used once per splinter circuit or sawtooth instance.
=> Enforce uniqueness for PO alternate IDs

sdk/Cargo.toml
This stabilizes the `client` feature by moving it to `stable` from
`experimental`.
=> Stabilize client feature

cli/src/actions/purchase_order.rs
Adds workflow type to display fields in CLI when user fetches
information about purchase orders. Renames "workflow type"
to "workflow name" and "workflow status" to "workflow state"
in display formatting. Adds clarity to "Accepted" display field.
=> Update purchase order CLI display

cli/src/actions/purchase_order.rs, contracts/purchase_order/src/handler.rs
This change adds the Pike namespace to the Purchase Order smart
contract's transaction inputs. This allows the purchase order smart
contract to access the state within the Pike namespace.
Before this change, the sawtooth example would be unable to submit a purchase order smart contract action without receiving an error about attempting to access an unauthorized namespace (Pike Organization namespace, specifically).
```
sawtooth-sabre-tp                  | 2021-11-19 21:29:53,500 INFO  [sawtooth_sdk::processor] TP_PROCESS_REQUEST sending TpProcessResponse: ExternalsError { message: "Trap(Trap { kind: Host(ExternalsError { message: \"AuthorizationError(\\\"Tried to get unauthorized addresses: [\\\\\\\"621dee0501ba3ce58667ca9b12b3c0cdcc4da57f9962aeca7065c43a7d9c027332fdb9\\\\\\\"]\\\")\" }) …
```
=> Add Pike namespace to transaction inputs

sdk/src/data_validation/xml/xml_ffi.rs
Update the drop implementations to use the as_ptr method instead of
self.0 for clarity.
=> Use as_ptr method for clarity

sdk/Cargo.toml
This stabilizes the `client-reqwest` feature by moving it into "stable"
in the sdk/Cargo.toml file.
=> Stabilize `client-reqwest` feature

cli/src/actions/product.rs, cli/src/main.rs, daemon/Dockerfile
Adds product and purchase order xsd files to default locations so users running through the examples can create products and purchase order versions. Previously, users would have to copy the files from the Grid directory into the running container and in the correct location.
Resolves: #1141, #1155
=> Add xsd files to docker images

cli/man/grid-po-version-create.1.md, cli/man/grid-po-version-update.1.md, cli/src/main.rs
This updates the `grid po version create` and `grid po version update`
cli commands to take the po number as the first positional argument
rather than a required flag. This seems more natural and is the pattern
used for the list and show version commands.
=> Update po version create and update commands

contracts/purchase_order/src/handler.rs, sdk/src/purchase_order/store/diesel/operations/add_purchase_order.rs
This fixes a couple bugs related to alternate IDs for purchase orders. There were two separate bugs that affected the ability to update the alternate IDs for a purchase order. One bug prevented adding new IDs and one prevented properly removing IDs.
=> Fix alternate ID bugs

sdk/src/client/purchase_order.rs, sdk/src/protocol/purchase_order/payload.rs, sdk/src/purchase_order/addressing.rs, sdk/src/purchase_order/store/diesel/models.rs
This PR includes several updates to the SDK code guarded by the `purchase-order` feature. These changes were requested during the first round of stabilization reviews.
=> `purchase-order` SDK feature stabilization work

sdk/src/pike/permissions/mod.rs, sdk/src/workflow/mod.rs, sdk/src/workflow/state.rs, sdk/src/workflow/subworkflow.rs
This adds a few more stabilization updates, including beefed up module lvl and rustdoc comments and an update to the `can_transition` method.
=> Stabilization updates for `workflow`

contracts/purchase_order/src/workflow.rs
This change adds permissions for the "po::partner" permission alias.
This allows the partner permission alias to create and update a po
within the collaborative subworkflow. Previously, only the "po::buyer"
and "po::seller" had permissions to create and update a purchase order.
=> Add po::partner permissions to po subworkflow

sdk/src/rest_api/resources/purchase_order/v1/handler.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
This adds doc comments to the structs in the purchase order rest api
code. This also adds doc comments to the functions in the same module.
=> Add doc comments to purchase_order rest api code

daemon/Cargo.toml, daemon/src/splinter/app_auth_handler/mod.rs, daemon/src/splinter/app_auth_handler/node.rs, daemon/src/splinter/app_auth_handler/sabre.rs, daemon/src/splinter/event/mod.rs, daemon/src/splinter/event/processors.rs, daemon/src/splinter/run.rs, sdk/Cargo.toml, sdk/src/backend/splinter.rs
This includes the commit used to stabilize the `cylinder-jwt-support` feature in both the SDK and the daemon.
Also backports #1188
=> Backport: Stabilize `cylinder-jwt-support` to 0-2 branch & adding ScabbardClient auth

daemon/src/rest_api/mod.rs, sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
Mainly, this PR is a response to a request made in the stabilization process for the Grid Daemon's `purchase-order` feature. This PR adds tests to the purchase-order-specific rest endpoints. This also adds a field to the return objects, `service_id`, as this field allows for more thorough testing and is info that some clients may want or need.
=> Add tests for the purchase order endpoints provided by the daemon

sdk/Cargo.toml
This stabilizes the `purchase-order` feature in the Grid SDK by moving
the feature from `experimental` to `stable`.
=> Stabilize `purchase-order` feature in sdk

daemon/Cargo.toml, daemon/Dockerfile
Including these in the package ensures they're available if the package
is copied out of the Docker image and installed elsewhere.
=> Add xsd files to gridd .deb package

cli/src/actions/purchase_order.rs, daemon/openapi.yaml, daemon/src/rest_api/mod.rs, sdk/src/client/purchase_order.rs, sdk/src/client/reqwest/mod.rs, sdk/src/client/reqwest/purchase_order/data.rs, sdk/src/client/reqwest/purchase_order/mod.rs, sdk/src/purchase_order/store/diesel/mod.rs, sdk/src/purchase_order/store/diesel/operations/get_latest_revision_id.rs, sdk/src/purchase_order/store/diesel/operations/mod.rs, sdk/src/purchase_order/store/mod.rs, sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs, sdk/src/rest_api/resources/purchase_order/v1/handler.rs, sdk/src/rest_api/resources/purchase_order/v1/mod.rs
This fixes the performance of the CLI when attempting to display many purchase order results. Previously, no results would be shown until all records were fetched from storage. With this update, a special iterator is used to take advantage of the REST API's paging and cache records so the CLI can print as soon as the first result comes back. This required significant rewrites to the CLI printing functionality.
=> Fix CLI display of many results

contracts/purchase_order/src/handler.rs, sdk/src/pike/permissions/mod.rs
This change updates the `check_permission_with_workflow` method to take a reference to the workflow state. Ownership is not required for this function. This allows the smart contract to maintain ownership over the workflow state for further processing.
=> Make `check_permission_with_workflow` take reference

sdk/src/purchase_order/store/diesel/operations/list_purchase_order_versions.rs
Fixes bug in which versions would be printed multiple times.
Resolves: #1179
=> Fix duplicate printing in `po version list`

cli/src/actions/purchase_order.rs, contracts/purchase_order/src/handler.rs, sdk/protos/purchase_order_payload.proto, sdk/src/protocol/purchase_order/payload.rs
This change  makes updates to the "CreatePurchaseOrderPayload" and "UpdatePurchaseOrderPayload". The "create" payload has a new field, `workflow_type`, which allows a user to select which workflow the purchase order should be in. The "update" payload also has a new field, `version_updates`. This new field is a list of `UpdateVersionPayload`s to allow a user to update multiple versions of a purchase order within a single transaction.
=> Purchase Order protobuf updates

daemon/src/rest_api/mod.rs, sdk/src/rest_api/resources/purchase_order/v1/mod.rs
This removes the `pub` re-export of the `handler` and `payloads`
modules. Only the required elements from these modules are now exported.
=> Re-scope REST API modules

cli/src/main.rs
Several imports that should be enabled for the purchase order feature
were disabled. This change enables them.
=> Enable missing imports for purchase order feature

sdk/src/purchase_order/store/diesel/operations/get_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/get_purchase_order_version.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_versions.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_orders.rs
Adds filter to select only revisions of the same purchase order.
Previously, if versions of different purchase orders had the same
version ID, the revision count would include all revisions of
versions with that name.
Resolves: #1170
=> Fix revision count in po and po version `list` and `show` commands

sdk/Cargo.toml
This stabilizes the `rest-api-resources-purchase-order` feature by
moving it from `experimental` to `stable`.
=> Stabilize `rest-api-resources-purchase-order`

cli/src/actions/purchase_order.rs, sdk/src/client/purchase_order.rs, sdk/src/client/reqwest/purchase_order/data.rs
This replaces any remaining instances of `workflow_type` with the new terminology `workflow_id`.
=> Rename remaining `workflow_type`s to `workflow_id`

cli/man/grid-po-create.1.md, cli/src/main.rs, contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/payload.rs
Adds a required arg to specify the po workflow when
creating a PO. Previously, all POs defaulted to the
collaborative workflow. Uses workflow-name instead
of workflow-type to be consistent with the CLI
display.
Resolves: #1201
Requires: https://github.com/hyperledger/grid/pull/1199
=> Add `workflow_id` arg to `grid po create`

cli/man/grid-po-version-create.1.md, cli/man/grid-po-version-update.1.md, cli/man/grid-product-create.1.md, cli/man/grid-product-update.1.md, cli/src/actions/mod.rs, daemon/Cargo.toml, daemon/Dockerfile
XML schema files now go into /usr/share, which is for
architecture-independent shareable files.
=> Update schema directory to /usr/share/grid/schemas

cli/src/actions/mod.rs, cli/src/actions/product.rs, cli/src/actions/purchase_order.rs, cli/src/main.rs
All external references to the schema directory should be based on both
the base schema dir and environment variables. This change creates
functions to facilitate that, and removes the public modifier from the
schema const.
=> Use functions as opposed to pub schema const

contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/payload.rs
This updates the structure and layout of the purchase order smart contract's create po action. This also updates the tests to be valid with the additional validation checks happening in the smart contract.
=> Update "create purchase order" action in po handler

cli/man/grid-po-update.1.md, cli/src/main.rs
Adds options and flags to enable simultaneous changes to purchase orders and
versions in situations where step-wise updates would lead to invalid states.
Users may only update the components of the version workflow state that must
be changed to avoid invalid states when updating purchase orders.
Resolves: #1202, #1183
Requires: #1199
=> Update `po update` command to allow simultaneous version updates

cli/src/actions/purchase_order.rs, cli/src/main.rs, sdk/Cargo.toml, sdk/src/data_validation/mod.rs, sdk/src/data_validation/purchase_order.rs
Adds tests to validate alt ID parsing. Enforces format of alt ID inputs.
Previously, invalid alt IDs were accepted. Also, users would receive
`status_code:500` errors when invalid alt IDs were provided.
Resolves: #1212
=> Validate alternate ID formats

cli/Cargo.toml
This stabilizes the `purchase-order` feature by moving it from
experimental to stable.
=> Stabilize Grid CLI `purchase-order` feature

cli/src/actions/purchase_order.rs, cli/src/main.rs
This adds the ability to update POs, add/update PO versions, and look up revisions using a PO's alternate ID.
=> Add ability to add/update POs/versions by alternate ID

sdk/src/location/store/diesel/operations/list_locations.rs, sdk/src/pike/store/diesel/operations/list_agents.rs, sdk/src/pike/store/diesel/operations/list_organizations.rs, sdk/src/pike/store/diesel/operations/list_roles_for_organization.rs, sdk/src/product/store/diesel/operations/list_products.rs, sdk/src/purchase_order/store/diesel/operations/list_alternate_ids_for_purchase_order.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_version_revisions.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_order_versions.rs, sdk/src/purchase_order/store/diesel/operations/list_purchase_orders.rs, sdk/src/schema/store/diesel/mod.rs, sdk/src/schema/store/diesel/operations/list_schemas.rs, sdk/src/schema/store/error.rs, sdk/src/track_and_trace/store/diesel/operations/list_records.rs
This updates the way the `total` is calculated for Grid DB operations.
This simplifies the way the number of records is calculated to make it
both more accurate and reduce the number of DB queries.
=> Fix paging `total` count across Grid modules

contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/workflow.rs, sdk/src/pike/permissions/mod.rs, sdk/src/workflow/mod.rs, sdk/src/workflow/state.rs, sdk/src/workflow/subworkflow.rs
This adds a new struct to Workflow state, `StartWorkflowState`. This is specifically used to validate a user's permissions to create an object within a workflow.
Also updates the methods within the permission checker to better specify between checking a user's permission within a workflow and when entering a workflow. This updates the `check_permission_with_workflow` method to be `check_permission_within_workflow` and adds a new method, `check_permission_to_enter_workflow` which inspects a `StartWorkflowState` rather than a `WorkflowState`. 
This also updates the purchase order smart contract handler to use the correct permission checking method (the create_X actions now use the `check_permission_to_enter_workflow` method) and updates an affected test that was specifying the "create" …
=> Add `StartWorkflowState`

sdk/src/migrations/diesel/postgres/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/migrations/diesel/postgres/migrations/2022-01-17-100000_purchase_order_tables_0_3/down.sql, sdk/src/migrations/diesel/postgres/migrations/2022-01-17-100000_purchase_order_tables_0_3/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2021-03-24-130200_purchase_order_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-01-17-100000_purchase_order_tables_0_3/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-01-17-100000_purchase_order_tables_0_3/up.sql
This updates the PO migrations by adding a new migrations file for the
0.3 version of the tables and reverts the original file back to its
original 0.2 state.
=> Fix PO migrations

daemon/Cargo.toml, griddle/Cargo.toml, sdk/Cargo.toml
This change updates the actix-web dependencies used across Grid to
disable default features. As Grid's Splinter dependency uses another
version of actix-web, multiple versions of a default compression
feature were being pulled in which caused a build error pertaining to
multiple definitions of the same things across the different versions
of the brotli compression feature. As Grid does not currently use these
default compression features, it is safe to turn these features off.
=> Remove actix-web default features

contracts/purchase_order/src/handler.rs
This change adds a check if the purchase order does not have the
`accepted_version_number` set to validate the list of versions for that
purchase order do not contain versions that exist in an
`accepted`-constrained state.
This addresses this bug: https://github.com/hyperledger/grid/issues/1246
=> Add check if po doesn't have accepted version

cli/Cargo.toml, cli/man/grid-download-xsd.1.md, cli/man/grid-po-version-create.1.md, cli/man/grid-po-version-update.1.md, cli/man/grid-product-create.1.md, cli/man/grid-product-update.1.md, cli/src/actions/mod.rs, cli/src/actions/product.rs, cli/src/actions/purchase_order.rs, cli/src/actions/xsd_downloader/downloader.rs, cli/src/actions/xsd_downloader/extractor.rs, cli/src/actions/xsd_downloader/mod.rs, cli/src/actions/xsd_downloader/validator.rs, cli/src/main.rs, daemon/Dockerfile
Add an XSD download CLI command, along with several utility methods for
downloading, extracting, and validating the files within the schema
archive.
=> Add `download-xsd` CLI command

cli/src/main.rs
This change updates how the revision ID is fetched for a version being
created. As this version is being created, the revision ID should be '1'
rather than the most recent revision ID of the version. The most recent
revision ID should not exist, as a version being created should not
already exist.
Testing instructions:
1. Create a PO & a PO version
2. Attempt to create the same version made previously
3. You should receive an error that that version already exists. Previously, you would receive the error I pasted in a comment below.
=> Check if version exists in create version command

cli/Cargo.toml
This change stabilizes the `xsd-downloader` feature, which enables the
user to download XSDs using the `grid download-xsd` subcommand.
=> Stabilize `xsd-downloader` feature

cli/src/main.rs, sdk/src/data_validation/xml/mod.rs
Checks to see if XSD and user-provided po XML files exist before attempting to read. Previously, the user would get a generic os error message, as these errors weren't mapping to ours.
Resolves: #1169
=> Add file checks to avoid "os error: file not found"

daemon/Cargo.toml
On docker build, puts the product xsd file in /var/lib/grid/...
instead of /usr/share/grid/...
Resolves an issue in which the data validation could not find the
file.
=> Fix product XSD location

cli/src/error.rs, cli/src/main.rs
Previously required arguments were retrieved via a call to unwrap(),
which had the capacity to panic at runtime. This change removes those
unwrap() calls and replaces them with a function that sends back a
standard CliError type.
=> Remove unwraps for required arguments

examples/splinter/docker-compose-dockerhub.yaml
This bumps the versions of the smart contracts downloaded in the
`docker-compose-dockerhub` file to `0.3.1` from `0.2.2`.
=> Update contract versions in Dockerhub docker-compose

justfile
Starting with version 0.11.0, just ignores .env files by default. This
breaks some recipes because we read docker environment variables from
the .env file.
=> Set dotenv-load to true in justfile

cli/man/grid-keygen.1.md
This adds the `KEY_NAME` argument to the `grid keygen` man page.
=> Update `grid keygen` man page

cli/Dockerfile, cli/src/actions/schemas.rs, contracts/pike/src/handler.rs, contracts/track_and_trace/src/handler.rs, daemon/Cargo.toml, griddle/Cargo.toml, sdk/Cargo.toml, sdk/src/backend/sawtooth.rs, sdk/src/batch_processor/submitter/sawtooth.rs, sdk/src/rest_api/resources/batches/v1/handler.rs
This change updates the actix-web dependencies used across Grid to
disable default features. As Grid's Splinter dependency uses another
version of actix-web, multiple versions of a default compression
feature were being pulled in which caused a build error pertaining to
multiple definitions of the same things across the different versions
of the brotli compression feature. As Grid does not currently use these
default compression features, it is safe to turn these features off.
=> BACKPORT 0-2: Remove actix-web default features & 1.58.1 clippy fixes & update grid-cli Dockerfile to not be based on sabre-cli

justfile
Starting with version 0.11.0, just ignores .env files by default. This
breaks some recipes because we read docker environment variables from
the .env file.
=> BACKPORT 0-2: Set dotenv-load to true in justfile

README.md
There are a number of libraries unlikely to be present on reader's
systems that must be installed before `cargo build` will successfully
build the project. These changes clarify prerequisites so that readers
following the README build instuctions can successfully build the
project without hitting roadblocks or guessing Grid's dependencies.
=> Add prerequisites to readme build instructions

cli/tests/data_validation.rs, docker/compose/grid-tests.yaml
Previously the tests used $CARGO_MANIFEST/tmp as a temporary directory
by default. This change updates the tests to instead create and use a
dir grid-integration-tests/ in the standard Rust environment temp
directory.
This change also updates the tests to optionally use an environment
variable for the cache directory, and updates the test dockerfile to set
the variable to /var/cache/grid. This should allow CI to persist the
cache from a stable and standard location between runs.
=> Update grid integration test cache dirs

cli/src/actions/purchase_order.rs, cli/src/error.rs, contracts/location/src/main.rs, contracts/product/src/main.rs, contracts/purchase_order/src/handler.rs, contracts/purchase_order/src/main.rs, contracts/schema/src/main.rs, contracts/track_and_trace/src/main.rs, sdk/src/protocol/location/payload.rs, sdk/src/protocol/location/state.rs, sdk/src/protocol/pike/payload.rs, sdk/src/protocol/pike/state.rs, sdk/src/protocol/product/payload.rs, sdk/src/protocol/product/state.rs, sdk/src/protocol/purchase_order/payload.rs, sdk/src/protocol/purchase_order/state.rs, sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs, sdk/src/protocol/track_and_trace/payload.rs, sdk/src/protocol/track_and_trace/state.rs, sdk/src/rest_api/resources/submit/v1/payloads/location.rs, sdk/src/rest_api/resources/submit/v1/payloads/pike.rs, sdk/src/rest_api/resources/submit/v1/payloads/product.rs, sdk/src/rest_api/resources/submit/v1/payloads/schema.rs
This fixes the clippy formatting errors introduced with Rust v1.59
=> Fix 1.59 clippy errors

ui/Dockerfile
Without this change, the sapling stage fails with an error about
missing python.
=> Fix grid-ui build on M1

cli/src/actions/schemas.rs, cli/src/error.rs, cli/src/yaml_parser.rs, cli/tests/product.rs, contracts/location/src/main.rs, contracts/product/src/main.rs, contracts/purchase_order/src/main.rs, contracts/schema/src/main.rs, contracts/track_and_trace/src/main.rs, daemon/src/rest_api/mod.rs, daemon/src/sawtooth/event.rs, sdk/src/pike/permissions/mod.rs, sdk/src/product/gdsn/mod.rs, sdk/src/protocol/location/payload.rs, sdk/src/protocol/location/state.rs, sdk/src/protocol/pike/payload.rs, sdk/src/protocol/pike/state.rs, sdk/src/protocol/product/payload.rs, sdk/src/protocol/product/state.rs, sdk/src/protocol/purchase_order/state.rs, sdk/src/protocol/schema/payload.rs, sdk/src/protocol/schema/state.rs, sdk/src/protocol/track_and_trace/payload.rs, sdk/src/protocol/track_and_trace/state.rs, sdk/src/rest_api/resources/submit/v1/payloads/location.rs, sdk/src/rest_api/resources/submit/v1/payloads/pike.rs, sdk/src/rest_api/resources/submit/v1/payloads/product.rs, sdk/src/rest_api/resources/submit/v1/payloads/schema.rs
This fixes the clippy formatting errors introduced with Rust v1.59
=> Backport 0-2: Fix 1.59 clippy errors

cli/Cargo.toml
Latest version of mockito replaces unmaintained difference library with
similar.
=> Bump `mockito` from 0.30 -> 0.31

docker-compose-installed.yaml
Prepares griddle for publishing to dockerhub during releases.
=> Add Griddle to docker-compose-installed

sdk/src/migrations/diesel/postgres/migrations/2022-02-09-212341_add_batch_tracking_tables/down.sql, sdk/src/migrations/diesel/postgres/migrations/2022-02-09-212341_add_batch_tracking_tables/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-02-09-212341_add_batch_tracking_tables/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-02-09-212341_add_batch_tracking_tables/up.sql
This adds postgres and sqlite migrations for updated batch tracking
tables. These migrations remove the unused and outdated tables of the
same name and add updated ones.
=> Add migrations for new batch tracking tables

cli/Cargo.toml
Latest version of dirs adds support for XDG_DATA_HOME.
=> Bump dirs library from 0.3 -> 0.4

cli/Cargo.toml, contracts/pike/Cargo.toml, daemon/Cargo.toml, griddle/Cargo.toml
The latest version of flexi_logger includes a number of API improvements
and fixes over 0.17.
=> Bump flexi_logger from 0.17 -> 0.22

sdk/Cargo.toml, sdk/src/batch_tracking/mod.rs, sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/schema.rs, sdk/src/batch_tracking/store/error.rs, sdk/src/batch_tracking/store/mod.rs, sdk/src/lib.rs
This PR adds several things: a diesel DB schema file for the Batch Tracking store db, DB struct models and their associated Rust struct representations along with conversion methods, and the initial BatchTrackingStore trait and several associated methods.
=> Add initial setup for the Batch Tracking Store

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/add_batches.rs, sdk/src/batch_tracking/store/diesel/operations/mod.rs, sdk/src/batch_tracking/store/mod.rs
This implements the `add_batches` operation for the Batch Tracking
store. As this is the first operation implemented for this store, some
additional initial setup is included as well.
=> Add `add_batches` Batch Tracking store operation

.github/labeler.yml, .github/workflows/label-prs.yaml
Adding the backport-triage label to new pull requests will help ensure
that changes are backported when appropriate.
=> Add GHA to label pull requests

cli/Cargo.toml, cli/src/actions/keygen.rs, cli/src/actions/xsd_downloader/downloader.rs, cli/src/actions/xsd_downloader/extractor.rs, cli/src/actions/xsd_downloader/mod.rs, cli/src/actions/xsd_downloader/validator.rs
Replace tempdir library with tempfile:3 because tempdir is no longer
maintained. See advisory: https://rustsec.org/advisories/RUSTSEC-2018-0017
=> BACKPORT 0.3: Replace tempdir library with tempfile

README.md
There are a number of libraries unlikely to be present on reader's
systems that must be installed before `cargo build` will successfully
build the project. These changes clarify prerequisites so that readers
following the README build instuctions can successfully build the
project without hitting roadblocks or guessing Grid's dependencies.
=> BACKPORT 0.3: Add prerequisites to readme build instructions

sdk/Cargo.toml, sdk/src/backend/splinter.rs
This change updates the SplinterBackendClient to so that it will
pass on error messages from Splinter error responses, and not
incorrectly mark them as internal errors.
It also adds a number of tests to verify the output in various
scenarios.
=> BACKPORT 0.3: Add handling for Splinter error responses

.github/workflows/publish-docker-branch.yaml
These images are published on a nightly schedule and not on every merge
so `main` tag is incorrect.
=> Tag images nightly instead of main

cli/tests/data_validation.rs, docker/compose/grid-tests.yaml
Previously the tests used $CARGO_MANIFEST/tmp as a temporary directory
by default. This change updates the tests to instead create and use a
dir grid-integration-tests/ in the standard Rust environment temp
directory.
This change also updates the tests to optionally use an environment
variable for the cache directory, and updates the test dockerfile to set
the variable to /var/cache/grid. This should allow CI to persist the
cache from a stable and standard location between runs.
Backport of: https://github.com/hyperledger/grid/pull/1305
=> BACKPORT 0.3: Update grid integration test cache dirs

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs, sdk/src/batch_tracking/store/diesel/operations/mod.rs, sdk/src/batch_tracking/store/mod.rs
This implements the `get_batch_status` operation for the Batch Tracking
store. This operation returns the current batch status for a batch with
a given ID and service ID. This PR also contains several other small but
necessary updates to the models to make this work.
=> Add `get_batch_status` db operation

sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/mod.rs
This adds a batch status variant: `DELAYED` to the `BatchStatus` enum.
This type will be used when a batch cannot be resubmitted quite yet but
should be queued to do so once any prerequisites are met.
=> Add `DELAYED` batch status type

contracts/purchase_order/src/handler.rs
This change fixes a clippy warning from Rust 1.60. For more information
on this clippy lint, see:
https://rust-lang.github.io/rust-clippy/master/index.html#iter_overeager_cloned
=> Fix over-eager clone

contracts/purchase_order/src/handler.rs
This change fixes a clippy warning from Rust 1.60. For more information
on this clippy lint, see:
https://rust-lang.github.io/rust-clippy/master/index.html#iter_overeager_cloned
=> Backport 0-3: Fix over-eager clone

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs, sdk/src/batch_tracking/store/diesel/schema.rs, sdk/src/batch_tracking/store/mod.rs, sdk/src/migrations/diesel/postgres/migrations/2022-04-14-215932_add_batch_tracking_tables_2/down.sql, sdk/src/migrations/diesel/postgres/migrations/2022-04-14-215932_add_batch_tracking_tables_2/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-04-14-215500_add_batch_tracking_tables_2/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-04-14-215500_add_batch_tracking_tables_2/up.sql
This updates the database schema for the batch tracking tables by
adding batch/transaction ID columns. These columns are intended to be
the primary keys for a table and consist of a hash of the batch/txn
header and the service ID. Columns for the service ID and batch/txn
headers are also included for deserialization sake. This is a necessary
change because diesel does not fully support composite keys.
Specifically, it does not implement the `BelongsToDsl` trait for
composite keys and they do not intend to implement this functionality,
as stated in https://github.com/diesel-rs/diesel/issues/1413.
=> Update batch tracking migrations

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch_status.rs, sdk/src/batch_tracking/store/diesel/schema.rs, sdk/src/migrations/diesel/postgres/migrations/2022-04-19-160501_undo-batch-tracking-key-changes/down.sql, sdk/src/migrations/diesel/postgres/migrations/2022-04-19-160501_undo-batch-tracking-key-changes/up.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-04-19-160454_undo-batch-tracking-key-changes/down.sql, sdk/src/migrations/diesel/sqlite/migrations/2022-04-19-160454_undo-batch-tracking-key-changes/up.sql
Previously, the migrations for the batch tracking tables were updated
to use a surrogate key composed of the id and service id due to Diesel's
incomplete support for composite foreign keys. This change switches the
primary key back to a composite primary key as well as the related
foreign keys and operations that need to filter based on those foreign
keys will use raw sql via the `sql_query` function.
=> Undo batch_tracking migrations key changes

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/mod.rs, sdk/src/batch_tracking/store/diesel/operations/update_batch_status.rs, sdk/src/batch_tracking/store/mod.rs
This adds an operation to update a batch's batch status. This operation updates the `batch_statuses` table as well as updating any associated transaction receipts. This also updates the batch tracking migrations to automatically generate timestamps which greatly simplifies this and other operations.
=> Add `update_batch_status` operation

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/get_batch.rs, sdk/src/batch_tracking/store/diesel/operations/get_unsubmitted_batches.rs, sdk/src/batch_tracking/store/diesel/operations/mod.rs, sdk/src/batch_tracking/store/mod.rs
This implements the `get_unsubmitted_batches()` operation for the
batch tracking store. This operation gets all batches that have not yet
been sumbitted. This is used by the batch queuer.
=> Add `get_unsubmitted_batches` operation

sdk/Cargo.toml, sdk/src/backend/splinter.rs
Switch from tokio to actix-rt for actix async tests so the versions
don't clash with tokio's version.
=> Use actix-rt library for testing actix async

sdk/src/batch_tracking/store/mod.rs, sdk/src/lib.rs, sdk/src/scope_id/mod.rs, sdk/src/scope_id/service/id/circuit.rs, sdk/src/scope_id/service/id/mod.rs, sdk/src/scope_id/service/id/qualified.rs, sdk/src/scope_id/service/id/service.rs, sdk/src/scope_id/service/mod.rs
Adds the `ScopeId` trait and the `GlobalScopeId` and `ServiceScopeId` structs. Also adds batch structs specific to the scope IDs and code from Splinter 0.6 for `FullyQualifiedServiceId`.
These will be required in future sub-components.
Resolves: #1406
=> Add scope_id and specific batch structs

sdk/Cargo.toml, sdk/src/rest_api/resources/mod.rs, sdk/src/rest_api/resources/submit/v2/error.rs, sdk/src/rest_api/resources/submit/v2/mod.rs, sdk/src/rest_api/resources/submit/v2/payloads/location.rs, sdk/src/rest_api/resources/submit/v2/payloads/mod.rs, sdk/src/rest_api/resources/submit/v2/payloads/pike.rs, sdk/src/rest_api/resources/submit/v2/payloads/product.rs, sdk/src/rest_api/resources/submit/v2/payloads/purchase_order.rs, sdk/src/rest_api/resources/submit/v2/payloads/schema.rs
This adds a v2 to the `submit` module which contains structs used to deserialize REST API JSON requests into smart contract actions. Mainly, this adds the infrastructure needed to create Batches based on Grid's smart contracts.
A few specifics for deserializing: 
- Adds interim `DeserializableXPayload` structs for the Pike and Location modules. These structs assist in determining which action is specified in the JSON. 
- Updates the `CreateAgentAction` to be deserialized from the `CreateAgentActionBuilder`. This allows for errors relating to malformed actions to be more specific as to what is wrong with the payload, rather than attempting to deserialize directly into the `Action` itself. This generates the error from the builder's `build` method, rather than the JSON parsing.
- Adds tests …
=> Add JSON payload infrastructure

sdk/src/batch_tracking/store/diesel/mod.rs, sdk/src/batch_tracking/store/diesel/models.rs, sdk/src/batch_tracking/store/diesel/operations/add_batches.rs, sdk/src/batch_tracking/store/diesel/operations/clean_stale_records.rs, sdk/src/batch_tracking/store/diesel/operations/mod.rs, sdk/src/batch_tracking/store/mod.rs
This adds an operation to clean batch tracking records that were created
before a specified time. This works by removing batch records with a
`created_at` value less than the specified timestamp. As the other
batch tracking tables all use foreign keys derived from the batch_id and
that use cascading deletes, this will remove the batch record and any
associated "child" records.
=> Add `clean_stale_records` operation

sdk/src/batch_submission/mod.rs
Adds the struct that represents a batch submission. This will be used by
the future submitter and queuer components.
=> Add submission struct

sdk/src/batch_tracking/store/mod.rs
This updates the doc comments for the batch tracking store methods to be
up to date with the current implementation.
=> Update batch tracking store doc comments

daemon/src/splinter/app_auth_handler/mod.rs
The `find` Iterator method takes a closure, which returns a boolean, and
the method then returns the first object that evaluates to true as an
Option, otherwise it returns None. Previously, we were doing this
specification manually in the `find_map` method.
This issue was caught by clippy, for more information on this lint,
see: https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_find_map
=> Backport 0-3: Use `find` instead of `find_map`

.github/workflows/integration-tests.yaml, .github/workflows/lint-grid-ui.yaml, .github/workflows/lint-grid.yaml, .github/workflows/lint-openapi.yaml, .github/workflows/test-grid-ui.yaml, .github/workflows/unit-test-grid.yaml
These were introduced inadvertently as a copy/paste error. Not only would
this behavior be undesired, but because the workflow runs in the context
of the forked repository there is no access to the secrets required.
=> Remove slack alerts from pull request workflows

sdk/Cargo.toml, sdk/src/rest_api/resources/submit/v2/handler/mod.rs, sdk/src/rest_api/resources/submit/v2/handler/reqwest.rs, sdk/src/rest_api/resources/submit/v2/mod.rs, sdk/src/rest_api/resources/submit/v2/payloads/batch.rs, sdk/src/rest_api/resources/submit/v2/payloads/mod.rs
This adds a trait for a component of the REST API that submits batches. It will take in a generic bytes representation of the batch to be submitted (or batch list) and other information pertaining to the batch to be persisted by Grid. This will be used by endpoints that accept batches, in order to process generic `TransactionPayload`s to store them as batches in Grid's DB, or to send them to an upstream server for further handling.
=> Add REST API batch submission handler trait

CODEOWNERS, MAINTAINERS.md
This change retires @chenette and @eloaverona as maintainers and
codeowners for Grid.
=> Retire chenette and eloaverona

.github/workflows/0-3-integration-tests.yaml, .github/workflows/0-3-lint-grid-ui.yaml, .github/workflows/0-3-lint-grid.yaml, .github/workflows/0-3-lint-openapi.yaml, .github/workflows/0-3-test-grid-ui.yaml, .github/workflows/0-3-unit-test-grid.yaml
These were introduced inadvertently as a copy/paste error. Not only would
this behavior be undesired, but because the workflow runs in the context
of the forked repository there is no access to the secrets required.
=> BACKPORT 0-3: Remove slack alerts from pull request workflows

sdk/Cargo.toml, sdk/src/lib.rs, sdk/src/threading/lifecycle.rs, sdk/src/threading/mod.rs
This change adds a threading module, which contains a lifecycle trait
for handling a thread shut down.
The threading module is available behind the experimental `lifecycle`
feature.
=> Add Shutdown trait

cli/src/actions/agent.rs, cli/src/actions/organization.rs, cli/src/actions/purchase_order.rs, sdk/src/client/reqwest/mod.rs, sdk/src/lib.rs
This makes several changes necessary to remove all Clippy lint warnings introduced in the 1.62.0 rust release. The two main changes are: 
1. Allowing unused lifetimes in Diesel macros. 
2. Remove unnecessary allocations made when appending to an existing string
=> Fix clippy lint introduced in 1.62.0

griddle/Cargo.toml, griddle/src/main.rs, griddle/src/rest_api/actix_web_4/api.rs, griddle/src/rest_api/actix_web_4/builder.rs, griddle/src/rest_api/actix_web_4/mod.rs, griddle/src/rest_api/actix_web_4/runnable.rs, griddle/src/rest_api/error.rs, griddle/src/rest_api/mod.rs
This adds a rest api with a builder, runnable, and running instances. This allows for the rest api to be stood up and taken down more easily. The running instance of the rest api implements the `ShutdownHandle` trait from the threading::lifecycle module.  
Technically, this also updates Griddle to use actix web 4. The rest api module is behind the experimental `rest-api` feature.
=> Add REST API module to griddle

README.md
Replaced postgres with libpq / libpq-dev, as a full postgres
installation is not strictly necessary.
For Ubuntu: Replaced insufficient libprotobuf-dev with the more accurate
protobuf-compiler dependency. Added required openssl, libsasl2-dev,
libxml2-dev, libsqlite3-dev, pkg-config, and build-essential.
Signed-off-by: Amelia Bradley <bradley@bitwise.io>
=> Update Ubuntu / OS X build dependencies

justfile
The GHA provided runners have limited free space so after building Docker
images necessary for the test they can easily run out of disk, causing the
test to fail. Removing unecessary prepopulated Docker images and some
large android libraries ensures there's plenty of headroom for our builds.
Link to list of pre-installed software:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
=> Update ci-test just recipe so unit-tests pass in GHA

examples/sawtooth/docker-compose.yaml
Updates the sawtooth example sabre image version to match the version
used in Grid contracts.
=> Upgrade sabre image version in sawtooth example
